- userguide/image_classifier/introduction.md
Fixed load images section to make sure that data was the SFrame being returned by tc.image_analysis.load_images
> Fix sample code for loading image data

- userguide/image_classifier/introduction.md
> Fix documentation typo

- INSTALL_ISSUES.md
The previous syntax for the install issues is inconsistent a probably wrong, so I fixed by adding quotes to the error message and include the full title sentence in a code snippet.
> Fix issue in inline code snippets

- src/unity/python/turicreate/data_structures/gframe.py
- src/unity/python/turicreate/data_structures/sframe.py
- src/unity/python/turicreate/extensions.py
- src/unity/python/turicreate/test/test_linear_regression.py
- src/unity/python/turicreate/test/test_python_decision_tree.py
(cherry picked from commit 63a8f26)
> Don’t compare boolean values to True or False using ==:
> 
> Yes:
> if greeting:
>
> No: 
> if greeting == True:
>
> Worse: 
> if greeting is True:
[source](http://pep8.org/#programming-recommendations)
> Simplify boolean variable checks

- src/unity/python/turicreate/test/test_evaluation.py
- Use numpy for random generation (consistent between py2/py3, unlike
the stdlib package `random`).
- Avoid scores too close to turicreate's fixed AUC thresholds - this can
cause tests to fail simply by having a bad seed since tests compare
against scikit-learn results (which does not use fixed thresholds). I tested
this locally be for-looping seeds, which before was broken but now works.
- Avoid deprecation warnings in scikit-learn for <0.18 and fix broken test
cases in 0.18>= (`test_missing_values` and `test_fbeta_binary_score`)
- Expose shadowed test: `test_none_prec_recall_scores` had two
definitions! The previous one looks like a binary version of the latter,
so I renamed it accordingly.
- Remove deprecation warnings in unittest: `assertEquals` -> `assertEqual`
- Tidying up some …
> Make evaluation tests more robust

- scenario-tests/tests/single_test_driver.py
- src/nnvm/tvm/python/tvm/contrib/xcode.py
- src/unity/python/turicreate/cython/cy_pylambda_workers.pyx
> Fix formatting errors detailed in #39

- src/unity/python/turicreate/meta/bytecodetools/disassembler_.py
Updates the meta subpackage to work with Python 3.4+.
I have tested this on Python 2.7 (all tests still pass, macOS 10.13 and Ubuntu 16.04) and Python 3.6 (relevant tests pass together with other forthcoming changes). 
Note: Byte code op sizes changed in 3.6 which will affect `instr.offset`. As a result it is important to also test this on 3.4 or 3.5. I defer testing on <=3.3 until a decision has been made on supported versions (#2).
> Update part of meta package to work on Python 3.4+

- src/unity/toolkits/coreml_export/MLModel/src/NeuralNetworkValidator.cpp
> Fix build failure

- src/unity/python/turicreate/data_structures/sframe.py
> Support DBAPI row types other than list or tuple

- userguide/image_classifier/advanced-usage.md
As noted by @jrosebr1 in https://github.com/apple/turicreate/issues/139#issuecomment-354650502
> Typo in set_num_gpus() call

- src/unity/python/turicreate/toolkits/_image_feature_extractor.py
- src/unity/python/turicreate/toolkits/_mxnet_to_coreml/_mxnet_converter.py
- src/unity/python/turicreate/toolkits/activity_classifier/_activity_classifier.py
- src/unity/python/turicreate/toolkits/object_detector/object_detector.py
This is just preparation for when coremltools gains Python 3 support.
> Make sure generators aren't passed to coremltools (in Python 3)

- src/unity/python/doc/source/conf.py
- src/unity/python/doc/source/turicreate.data_structures.rst
> Add load_sframe and load_sgraph to API docs

- src/unity/lib/visualization/histogram.cpp
- src/unity/lib/visualization/vega_spec.cpp
- src/unity/lib/visualization/vega_spec/summary_view.json
- src/unity/python/turicreate/data_structures/sarray.py
- src/unity/python/turicreate/visualization/show.py
- src/visualization/Turi Create Visualization/table_view.css
Test
``` python
import turicreate as tc 
array = tc.SArray(range(1, 20000))  
array.show(title = "my title", ylabel = "", xlabel = "")
```
Test
``` python
import turicreate as tc 
array = tc.SArray(range(1, 20000)) 
frame = tc.SFrame([array])
frame.show()
```
> WIP: Added some more GUI fixes

- userguide/activity_classifier/data-preperation.md
Fixes https://github.com/apple/turicreate/issues/209
> Fix AC UG data preperation

- src/unity/python/turicreate/test/test_sentence_classifier.py
- src/unity/python/turicreate/toolkits/sentence_classifier/_sentence_classifier.py
String target for sentence classifier would perform feature extraction on the target.
> Fixes #235. Sentence classifier string target.

- src/unity/python/turicreate/test/test_coreml_export.py
- src/unity/toolkits/coreml_export/mldata_exporter.cpp
- src/unity/toolkits/coreml_export/xgboost_exporter.cpp
Fixes #55 
@alonpal @hoytak Please review.
> Fixed an issue with export to coreml.

- src/unity/python/turicreate/data_structures/sframe.py
Added some more details to fix #120
> Fixes a doc bug in groupby

- src/unity/python/README.rst
- src/unity/python/setup.py
> Update readme and setup.py for Python 3

- src/unity/python/turicreate/test/test_image_similarity.py
- src/unity/python/turicreate/toolkits/image_similarity/image_similarity.py
- src/unity/toolkits/nearest_neighbors/nearest_neighbors.cpp
- src/unity/toolkits/nearest_neighbors/nearest_neighbors.hpp
- src/unity/toolkits/nearest_neighbors/unity_nearest_neighbors.cpp
- Adds CoreML export to Image similarity
Requires:
- Test cases
- Documentation
- Extract reference data from the model
> Image similarity export to CoreML

- userguide/activity_classifier/README.md
- userguide/activity_classifier/data-preperation.md
- userguide/clustering/dbscan.md
- userguide/clustering/kmeans.md
- userguide/datasets.md
- userguide/image_classifier/README.md
- userguide/image_similarity/README.md
- userguide/recommender/README.md
- userguide/sframe/sframe-intro.md
- userguide/supervised-learning/boosted_trees_classifier.md
- userguide/supervised-learning/boosted_trees_regression.md
- userguide/supervised-learning/decision_tree_classifier.md
- userguide/supervised-learning/decision_tree_regression.md
- userguide/supervised-learning/random_forest_classifier.md
- userguide/supervised-learning/random_forest_regression.md
Adding datasets to documentation so its easier for users to follow along.
> Added more documentation datasets

- src/unity/lib/unity_sframe.cpp
- src/unity/lib/visualization/boxes_and_whiskers.cpp
- src/unity/lib/visualization/categorical_heatmap.cpp
- src/unity/lib/visualization/item_frequency.cpp
- src/unity/lib/visualization/vega_data.cpp
- src/unity/lib/visualization/vega_spec.cpp
- src/unity/lib/visualization/vega_spec.hpp
- added extra escape symbols for labels, titles, axes
> newline escaping labels, titles, axes

- src/unity/lib/visualization/vega_spec/categorical.json
- added a format to the axis value to fix the count being shown as a double
> Fixed Categorical showing count as double

- src/image/png_io.cpp
Borrowing from libpng-1.6.14/example.c
For https://github.com/apple/turicreate/issues/138
> Support palette (type P) PNG image files

- userguide/SUMMARY.md
- userguide/cpp.md
> Add C++ API usage to user guide

- userguide/sgraph/sgraph.md
> Propose fix typo

- src/unity/python/turicreate/toolkits/image_analysis/image_analysis.py
> Fixed random ordering.

- src/unity/lib/visualization/vega_spec/boxes_and_whiskers.json
- src/unity/lib/visualization/vega_spec/categorical.json
- src/unity/lib/visualization/vega_spec/categorical_heatmap.json
- src/unity/lib/visualization/vega_spec/heatmap.json
- src/unity/lib/visualization/vega_spec/histogram.json
- src/unity/lib/visualization/vega_spec/scatter.json
- src/unity/lib/visualization/vega_spec/summary_view.json
- src/visualization/Turi Create Visualization/vega_viz.html
- added fallback font for linux
- fixed scroll bar issue in linux
> Added fallback font TuriCreate and fixed scroll bar issue in linux

- src/unity/python/turicreate/data_structures/sarray.py
- src/unity/python/turicreate/data_structures/sframe.py
- src/unity/python/turicreate/visualization/plot.py
- Made Plot api plumbing for the show method
- Updated .show() method on Jupyter Notebook
- Updated Tooltips on Jupyter Notebook
- Created doc string for public methods of Plot Object
> Updated Plot Api

- src/unity/lib/unity_sframe.cpp
> Fixed build break in 4.2a1 build.

- src/unity/lib/visualization/boxes_and_whiskers.cpp
- src/unity/lib/visualization/boxes_and_whiskers.hpp
- src/unity/lib/visualization/categorical_heatmap.cpp
- src/unity/lib/visualization/categorical_heatmap.hpp
- src/unity/lib/visualization/heatmap.cpp
- src/unity/lib/visualization/heatmap.hpp
- src/unity/lib/visualization/item_frequency.cpp
- src/unity/lib/visualization/scatter.cpp
- src/unity/lib/visualization/scatter.hpp
- src/unity/lib/visualization/show.cpp
- src/unity/lib/visualization/show.hpp
- src/unity/python/turicreate/data_structures/sarray.py
- src/unity/python/turicreate/visualization/plot.py
- src/unity/python/turicreate/visualization/show.py
- updated tc.show to work in Jupyter Notebook
> Updated tc.show to work in Jupyter Notebook

- userguide/text/analysis.md
Fixed a minor typo that caused the GitHub interface to not render the h1 correctly.
> Fixed heading in analysis.md

- src/sframe/parallel_csv_parser.cpp
The `readsome` function doesn't behave the way I expected - "available"
means "already in the buffer", not "can be read from the stream", which
means typically it reads 0 bytes on a newly initialized stream (which
breaks skip_BOM). We need to use `get`, and after each call, make sure
the stream is still in a good state (or recover if it's not).
This one passes both the C++ unity_sarray.cxxtest and Python
test_sframe.py.
> Fix C++ unit test failure, attempt #2

- userguide/vis/README.md
> Mention set_target in user guide

- src/unity/python/turicreate/test/test_logistic_classifier.py
- src/unity/python/turicreate/test/test_sentence_classifier.py
- src/unity/python/turicreate/toolkits/sentence_classifier/_sentence_classifier.py
Fixes #360 
Also deleted some other unused code
> Sentence Classifier - better error message with non SFrame

- src/unity/lib/unity_sarray.cpp
- fixed empty string in datetime
> Empty string fix

- src/unity/python/turicreate/toolkits/object_detector/util/_visualization.py
> Consistent color for draw_bounding_boxes

- src/unity/python/turicreate/toolkits/image_classifier/image_classifier.py
This probably changed at some point without updating the docs.
> Make docstring consistent with current behavior

- src/fileio/temp_files.cpp
- src/unity/python/turicreate/toolkits/_main.py
> Better error message for unwritable temp location

- src/visualization/Turi Create Visualization/src/user_interface/src/elements/Plot/Chart/index.js
> Added bubble opt options to vega-tooltips

- src/unity/lib/unity_sframe.cpp
- src/visualization/Turi Create Visualization/src/user_interface/src/elements/Explore/Table/index.js
- src/visualization/Turi Create Visualization/src/user_interface/src/elements/Explore/Table/sticky-table/index.js
> Added ND-array support

- src/visualization/Turi Create Visualization/src/user_interface/src/index.js
> Added zoom again

- src/visualization/Turi Create Visualization/src/user_interface/src/elements/Explore/Table/index.js
- added support for negatives and row > size
> Extended jump row for negatives and row > size

- src/unity/lib/CMakeLists.txt
- src/unity/lib/visualization/CMakeLists.txt
- src/unity/lib/visualization/columnwise_summary.cpp
- src/unity/lib/visualization/columnwise_summary.hpp
For some reason, the test build is failing on Linux/release. This seems
to fix it. I'm not sure why.
> Fix build for 4.3

- src/unity/python/turicreate/CMakeLists.txt
- src/unity/python/turicreate/visualization/_plot.py
- src/unity/python/turicreate/visualization/vg2png
> Removed Canvas Dependecy

- src/unity/lib/visualization/vega_spec/categorical.json
> Removed format d3

- src/sframe_query_engine/operators/operator.hpp
- src/sframe_query_engine/planning/optimizations/optimization_transforms.hpp
- src/unity/lib/gl_sarray.cpp
- src/unity/lib/gl_sarray.hpp
- src/unity/lib/visualization/transformation.hpp
- src/unity/toolkits/evaluation/evaluation_interface-inl.hpp
- src/unity/toolkits/ml_data_2/statistics/column_statistics.hpp
- src/unity/toolkits/nearest_neighbors/distance_functions.hpp
- src/unity/toolkits/sgd/sgd_interface.hpp
- src/unity/toolkits/sgd/sgd_solver_base.hpp
- src/unity/toolkits/sparse_similarity/sparse_similarity_lookup.hpp
- src/unity/toolkits/supervised_learning/standardization-inl.hpp
To guard against deleting an instance of a derived class via a reference to its polymorphic base
> Add virtual destructors to classes with virtual functions

- CMakeLists.txt
- scripts/make_wheel.sh
- src/toolkits/CMakeLists.txt
- src/toolkits/image_deep_feature_extractor/CMakeLists.txt
- src/toolkits/image_deep_feature_extractor/class_registrations.cpp
- src/toolkits/image_deep_feature_extractor/class_registrations.hpp
- src/toolkits/image_deep_feature_extractor/image_deep_feature_extractor_toolkit.cpp
- src/toolkits/image_deep_feature_extractor/image_deep_feature_extractor_toolkit.hpp
- src/toolkits/image_deep_feature_extractor/image_feature_extractor.hpp
- src/toolkits/image_deep_feature_extractor/mlmodel_image_feature_extractor.hpp
- src/toolkits/image_deep_feature_extractor/mlmodel_image_feature_extractor.mm
- src/unity/CMakeLists.txt
- src/unity/python/turicreate/test/test_image_classifier.py
- src/unity/python/turicreate/test/test_image_similarity.py
- src/unity/python/turicreate/toolkits/_image_feature_extractor.py
- src/unity/python/turicreate/toolkits/_pre_trained_models.py
- src/unity/python/turicreate/toolkits/image_classifier/image_classifier.py
- src/unity/python/turicreate/toolkits/image_similarity/image_similarity.py
- src/unity/server/registration.cpp
* C++ Deep Feature Extractor, exposed to Python
* Mac GPU Acceleration for Image Similarity
* Mac GPU Acceleration for Image Classification
> GPU acceleration on macOS for IC, IS

- README.md
- userguide/style_transfer/README.md
* Add missing style transfer link
* Fix GFM rendering
> Fix style transfer doc

- src/unity/python/turicreate/test/test_object_detector.py
- src/unity/python/turicreate/toolkits/object_detector/object_detector.py
Object Detector now supports non-maximal suppression in Core ML export.
> Object Detector export with NMS

- userguide/object_detection/data-preparation.md
Earlier, we mention that we want to assume that our data is in ~/Downloads/ig02
> Make the ig02 path consistent

- src/unity/python/turicreate/test/test_image_similarity.py
- src/unity/python/turicreate/toolkits/image_classifier/image_classifier.py
- src/unity/python/turicreate/toolkits/image_similarity/image_similarity.py
Fixes unreliable Image Similarity unit test by using a better comparison metric.
Adds vision feature print screen to image similarity (#705)
> Image similarity vision feature print screen

- src/unity/python/doc/source/turicreate.visualization.rst
- src/unity/python/turicreate/toolkits/recommender/__init__.py
- userguide/supervised-learning/linear-regression.md
Simple fixes for the following issues:
- https://github.com/apple/turicreate/issues/687
- https://github.com/apple/turicreate/issues/686
- https://github.com/apple/turicreate/issues/542
> Misc doc fixes

- src/unity/python/turicreate/toolkits/recommender/__init__.py
- src/unity/python/turicreate/visualization/__init__.py
Picking up from #678 but with a cleaner commit history :-)
> Bugfix for #452 and #542

- userguide/sgraph/sgraph.md
For https://github.com/apple/turicreate/issues/464
> Remove SGraph.show references

- src/visualization/Turi Create Visualization/src/user_interface/src/elements/Plot/Chart/index.js
- Added fix to Save_Vega_JSON
- Fixes #739
> added save json fix

- userguide/image_similarity/README.md
`.show` should be applied to `turicreate.Image` instead of the entire row.
> Image.show() instead of the entire row

- src/unity/lib/unity_sarray.cpp
- src/unity/python/turicreate/test/malformed.json
- src/unity/python/turicreate/test/test_json.py
> Error out when reading malformed JSON

- src/unity/python/turicreate/toolkits/_coreml_utils.py
- src/unity/python/turicreate/toolkits/object_detector/object_detector.py
- Avoiding loading the Core ML model using the coremtools.models.MLModel call
- Still need to create a PR on the `coremltools` side
> Turi Create fix for Issue #701

- src/unity/python/turicreate/test/test_object_detector.py
- src/unity/python/turicreate/toolkits/object_detector/object_detector.py
- src/unity/toolkits/tcmps/mps_graph_cnnmodule.mm
- src/unity/toolkits/tcmps/mps_layers.mm
Resolves issues encountered by running test_object_detector.py in debug mode
> Some miscellaneous fixes for object detection

- src/capi/impl/capi_sframe.cpp
- test/capi/capi_sframe.cxx
- test/capi/capi_utils.hpp
* Adds C API unit tests for join (single column case so far)
* Adds a multiple column join implementation in C API
* Implements single column join in terms of multi column join, so our
single column unit test has some hope of decent coverage.
> Unit tests and adding multiple column join

- src/toolkits/image_deep_feature_extractor/mlmodel_image_feature_extractor.mm
Replace deprecated API usage with the final API for MLBatchProvider
> Adopt updated MLBatchProvider API

- scripts/install_python_toolchain.sh
- src/unity/python/turicreate/data_structures/image.py
> Add doc string image.save

- src/unity/toolkits/supervised_learning/logistic_regression.cpp
This is a quick fix for the C-API code path. A cleaner fix, to unify the C-API path and the current Python path, is tracked by #847
AFAICT, the implementation here was inadvertently copied from `export_linear_svm_as_model_asset` instead of `export_logistic_model_as_model_asset`
> Fix copy-and-paste error in logistic_regression::export_to_coreml

- src/unity/python/turicreate/toolkits/recommender/util.py
- test/capi/capi_models.cxx
fixes #543. Also fixes some indentation in a C++ unit test.
> Fix a Docstring

- src/unity/lib/visualization/escape.cpp
> Fixes json crash in Visualization Client

- src/unity/python/turicreate/toolkits/classifier/boosted_trees_classifier.py
- src/unity/python/turicreate/toolkits/classifier/decision_tree_classifier.py
- src/unity/python/turicreate/toolkits/classifier/logistic_classifier.py
- src/unity/python/turicreate/toolkits/classifier/random_forest_classifier.py
- src/unity/python/turicreate/toolkits/classifier/svm_classifier.py
- src/unity/python/turicreate/toolkits/image_similarity/image_similarity.py
- src/unity/python/turicreate/toolkits/recommender/util.py
- src/unity/python/turicreate/toolkits/regression/boosted_trees_regression.py
- src/unity/python/turicreate/toolkits/regression/decision_tree_regression.py
- src/unity/python/turicreate/toolkits/regression/linear_regression.py
- src/unity/python/turicreate/toolkits/regression/random_forest_regression.py
- src/unity/python/turicreate/toolkits/sentence_classifier/_sentence_classifier.py
- src/unity/toolkits/coreml_export/coreml_extension.cpp
- added user metadata to identify TC version 
- fixes #718
> Added user metadata to identify TC Version in CoreML Models

- src/unity/python/turicreate/test/test_recommender.py
I believe this change should get us back to all-passing tests again...
> Update test_recommender.py to reflect changes from #833

- src/unity/python/turicreate/toolkits/style_transfer/style_transfer.py
This PR enables data augmentation for style transfer.
* pass content_loader_type into data iterator  
* add missing parameter in params required for data augmentation
> Enable data augmentation for style transfer

- src/unity/lib/visualization/vega_spec.cpp
- src/unity/lib/visualization/vega_spec.hpp
- src/unity/lib/visualization/vega_spec/boxes_and_whiskers.json
- src/unity/lib/visualization/vega_spec/categorical.json
- src/unity/lib/visualization/vega_spec/categorical_heatmap.json
- src/unity/lib/visualization/vega_spec/heatmap.json
- src/unity/lib/visualization/vega_spec/histogram.json
- src/unity/lib/visualization/vega_spec/scatter.json
- src/unity/lib/visualization/vega_spec/summary_view.json
- src/visualization/Turi Create Visualization/src/user_interface/package.json
- src/visualization/Turi Create Visualization/src/user_interface/src/elements/Plot/Chart/index.js
> Upgraded Vega

- scripts/requirements.txt
- src/unity/python/turicreate/cython/cy_flexible_type.pyx
- src/unity/python/turicreate/test/test_sframe.py
> Allow flexible types to take builtins types

- src/unity/lib/visualization/vega_spec/boxes_and_whiskers.json
> Updated Sorted Box-Plots

- src/unity/python/turicreate/test/test_style_transfer.py
- src/unity/python/turicreate/toolkits/style_transfer/_sframe_loader.py
- src/unity/python/turicreate/toolkits/style_transfer/style_transfer.py
This PR fixes #636 
* when the number of content images is less than the batch_size, data iterator hangs! Fixed data iterator
* remove unused variables
> Style transfer fix data iterator

- README.md
Adds a bullet point to communicate that TC requires at least 4 gigabytes of memory
> Fixes #787

- userguide/style_transfer/export-coreml.md
- Updated our export to CoreML docs for Style Transfer to not use the Vision Framework
> Updated Export Coreml Docs Style Transfer

- CMakeLists.txt
- src/unity/python/turicreate/test/test_boosted_trees.py
- src/unity/python/turicreate/test/test_coreml_export.py
- src/unity/toolkits/coreml_export/xgboost_exporter.cpp
- src/unity/toolkits/supervised_learning/logistic_regression_opt_interface.cpp
This PR adds tests for validation classes having additional classes not
seen in the training classes.  These tests exposed problems with both
the evaluation and exporting to CoreML, both of which are fixed.
> Fixed bug with validation sets having additional classes.

- userguide/activity_classifier/advanced-usage.md
- userguide/image_similarity/README.md
- userguide/object_detection/README.md
> Added documentation for GPU support in the userguide

- userguide/object_detection/data-preparation.md
It instead converts a CSV to SFrame. Code courtesy of @Kurry
Fixes #965
> Added code snippet that doesn't use masks

- src/unity/python/doc/source/turicreate.toolkits.style_transfer.rst
> add style transfer to api doc

- src/unity/python/turicreate/toolkits/style_transfer/style_transfer.py
- Updated max iterations to be based on the number of style images
- fixes #680
> style transfer toolkit update to calculate iterations based on style images

- README.md
- userguide/activity_classifier/advanced-usage.md
- userguide/object_detection/README.md
> Clarify that MPS-based toolkit implementations require a discrete GPU

- src/unity/python/turicreate/data_structures/sketch.py
> Fixed sketch summary print layout to accomodate empty strings.

- userguide/supervised-learning/logistic-regression.md
> Added to the docs examples on how to isolate FPs, FNs and mistakes

- CMakeLists.txt
Resolves https://github.com/apple/turicreate/issues/981
> Existence of -Wno-stdlibcxx-not-found is now checked on configure.

- src/unity/python/turicreate/toolkits/recommender/util.py
> Helpful message when exporting a recommender model

- src/unity/python/turicreate/test/test_style_transfer.py
> Don't use CoreML prediction on unsupported platforms

- src/unity/python/turicreate/cython/cy_flexible_type.pyx
fixes #994 
Also removed some extra whitespace.
> Do additional safety check for builtins.int

- test/capi/capi_models.cxx
> Fix permission denied test even as root on Linux

- .travis.yml
- BUILD.md
- scripts/requirements.txt
- src/generics/is_memmovable.hpp
- src/logger/error.cpp
- src/logger/error.hpp
- src/unity/python/turicreate/test/test_style_transfer.py
- test/sframe_query_engine/CMakeLists.txt
* Adds a `.travis.yml` file
* Copies the docker container definitions from https://github.com/apple/coremltools/tree/master/docker
> Initial attempt at setting up CI

- src/unity/python/turicreate/visualization/_plot.py
> Added adaqute escaping to vega

- README.md
- userguide/recommender/coreml-deployment.md
- userguide/style_transfer/README.md
> Removed all mentiones of beta in the README.

- src/unity/lib/visualization/item_frequency.cpp
- src/unity/lib/visualization/vega_spec/categorical.json
- added a percentage field in vega
> Added a percentage field in vega

- src/unity/python/turicreate/test/test_recommender.py
- src/unity/python/turicreate/toolkits/_feature_engineering/_autovectorizer.py
Fixes https://github.com/apple/turicreate/issues/1088.
> Bugfix for item content recommender bug.

- src/unity/python/turicreate/cython/cy_flexible_type.pyx
- src/unity/python/turicreate/test/test_sarray.py
Fixes https://github.com/apple/turicreate/issues/1094
> Fixes bad check with astype(None)

- src/unity/python/turicreate/data_structures/sarray.py
- src/unity/python/turicreate/test/test_sarray.py
> SArray type-casting bug fix 

- src/unity/python/turicreate/toolkits/recommender/item_content_recommender.py
This PR fixes https://github.com/apple/turicreate/issues/1097
> Fix #1097 - Item Content Recommender Documentation

- src/unity/python/turicreate/data_structures/sframe.py
- src/unity/python/turicreate/test/test_sframe.py
This reverts commit ef481672cbfb7ebd87642584a341e0673fe1cbfb.
> Revert "Const assignment to empty SFrame (#1104)"

- src/unity/python/turicreate/data_structures/sarray.py
- src/unity/python/turicreate/test/test_sarray.py
> Feature Request for filter_by() in SArray

- .travis.yml
- scenario-tests/README.md
- scenario-tests/tests/toolkits/test_image_classifier.py
- scenario-tests/tests/toolkits/test_image_similarity.py
- Moves current unit tests to scenario tests since they are more like scenario tests.
- Created simplier unit tests, similar but faster.
- Added some correctness checks to unit tests.
- Readded these unit tests to travis CI.
> Image Similarity/Classification Unit Tests

- src/ml_data/testing_utils.cpp
- src/sframe/testing_utils.cpp
- src/unity/toolkits/ml_data_2/testing_utils.cpp
- test/unity/toolkits/ml_data_2/creation_methods.cxx
These failing test cases in master were introduced by the recent ndarray
change.  As part of that PR, the random data generation code was
consolidated and one output type of that changed, causing the cxx test
failures shown.
Fixes https://github.com/apple/turicreate/issues/1198
> Fixed failing C++ test cases in master.

- LINUX_INSTALL.md
> Add libgconf-2-4 to Linux installation instructions

- src/unity/python/turicreate/test/test_sarray.py
Resolves non-deterministic test failures (that happened to pass on Travis)
> SArray test_filter_by should not assume filter_by preserves order

- CONTRIBUTING.md
- README.md
Include a mention that we are using Travis CI to test contributions.
> Update CONTRIBUTING.md for Travis CI

- src/unity/lib/visualization/vega_spec/boxes_and_whiskers.json
- src/unity/lib/visualization/vega_spec/heatmap.json
- src/unity/python/turicreate/__init__.py
- src/unity/python/turicreate/visualization/__init__.py
- src/unity/python/turicreate/visualization/show.py
- src/visualization/Turi Create Visualization/src/user_interface/package.json
- src/visualization/Turi Create Visualization/src/user_interface/src/elements/Plot/Chart/index.js
- src/visualization/Turi Create Visualization/src/user_interface/src/elements/Plot/Summary/index.js
* Fixes #1129
* Fixes #1179
* Upgrade Vega to latest version
* Switch Vega renderer to SVG (seems both faster and better rendering, at least in WebKit)
> Fix plot display for heat map and box plot

- src/unity/lib/extensions/ml_model.hpp
- src/unity/lib/extensions/model_base.cpp
- src/unity/lib/extensions/model_base.hpp
- src/unity/python/turicreate/test/test_prototype_models.py
- src/unity/python/turicreate/toolkits/_model.py
- src/unity/server/registration.cpp
- src/unity/toolkits/CMakeLists.txt
- src/unity/toolkits/prototype/CMakeLists.txt
- src/unity/toolkits/prototype/class_registrations.cpp
- src/unity/toolkits/prototype/class_registrations.hpp
- src/unity/toolkits/prototype/sparse_nn.cpp
- src/unity/toolkits/prototype/sparse_nn.hpp
A simple implementation of an extremely efficient brute-force nearest neighbors algorithm meant for single-query nearest neighbors query with Jaccard distance over categorical variables.  
This also is a simple implementation meant to demonstrate the ease of using the extensions to create a minimal model.  A new directory, prototype, is designed for these simple implementations.  
In addition, a few bugs preventing the proper saving and loading of pure extension models were fixed.
> Prototype of a Sparse NN model for pure categorical features

- src/unity/toolkits/neural_net/CMakeLists.txt
- src/unity/toolkits/neural_net/TCMPSImageAugmenting.h
- src/unity/toolkits/neural_net/TCMPSImageAugmenting.m
- src/unity/toolkits/neural_net/cnn_module.cpp
- src/unity/toolkits/neural_net/float_array.cpp
- src/unity/toolkits/neural_net/float_array.hpp
- src/unity/toolkits/neural_net/image_augmentation.cpp
- src/unity/toolkits/neural_net/image_augmentation.hpp
- src/unity/toolkits/neural_net/mps_factory.hpp
- src/unity/toolkits/neural_net/mps_factory.mm
- src/unity/toolkits/neural_net/mps_image_augmentation.hpp
- src/unity/toolkits/neural_net/mps_image_augmentation.mm
- src/unity/toolkits/object_detection/object_detector.cpp
- src/unity/toolkits/object_detection/od_data_iterator.cpp
- src/unity/toolkits/object_detection/od_data_iterator.hpp
- test/unity/toolkits/neural_net/CMakeLists.txt
- test/unity/toolkits/neural_net/test_mps_image_augmentation.cxx
Just a WIP for now because I still want to add some tests. I'm not expecting any further modifications to the existing changes here though....
> Implement data augmentation pipeline for object detection using Core Image

- src/lambda/worker_pool.hpp
Referencing issue https://github.com/apple/turicreate/issues/1156#issue-373507542
- Less confusing error message
> Clarify error message

- src/unity/python/turicreate/test/test_text_analytics.py
- src/unity/python/turicreate/toolkits/text_analytics/_util.py
Fixes #1268 
Also adds a unit test for tokenization. There were not any unit tests for tokenization.
> Bug Fix: tokenization

- src/unity/toolkits/neural_net/cnn_module.hpp
- src/unity/toolkits/neural_net/mps_graph_cnnmodule.h
- src/unity/toolkits/neural_net/mps_graph_cnnmodule.mm
- src/unity/toolkits/object_detection/object_detector.cpp
- test/unity/toolkits/object_detection/test_object_detector.cxx
Implements for the new C++ toolkit [the logic implemented for Python](https://github.com/apple/turicreate/blob/86c65447504be4e4bdd3378d88957c6f1b0d4d63/src/unity/python/turicreate/toolkits/_internal_utils.py#L624)
> Report names of GPU(s) used as feedback in C-API object detector

- src/unity/python/turicreate/toolkits/image_classifier/image_classifier.py
Attempted to my add the logistic regression's parameters to the image classifier toolkit. This is probably not correct, as I'm inexperienced.
> Added logistic parameters to image classifier

- src/unity/python/turicreate/toolkits/object_detector/object_detector.py
> Plumbed through IOU and Confidence to evaluate and predict

- src/unity/python/turicreate/toolkits/object_detector/object_detector.py
Updated the confidence value for the od evaluate function
> updated the confidence value for the od evaluate function

- src/optimization/lbfgs.cpp
There was a bug in the new implementation that was triggering a frequent recomputation of the optimum step size.  This fixes that bug. 
In addition, a simple scaling rule of the step size is added to prevent it from staying at a very small value for too often.  If the step size is below 1, which should work in most cases due to scaling considerations, then it is slowly increased to 1.
> Updates to the line search trigger conditions in LBFGS.

- test/unity/toolkits/object_detection/test_object_detector.cxx
Added test for Non Maximum Suppression feature implementation for the Object Detector in PR #1265.
Test asserts correct field population of the Non Maximum Suppression model.
> Test for Non Maximum Suppression feature in OD

- src/capi/TuriCreate.h
- src/unity/lib/visualization/vega_spec.cpp
> Add a default label parameter value to plot C API

- src/capi/TuriCreate.h
- src/unity/lib/visualization/plot.cpp
> Add small, medium, & large plot size to C API

- src/unity/python/doc/source/conf.py
Fixes #1345 
- Import wasn't added to sphinx config.
> Added import to the conf.py file to correctly generate sphinx docs

- scenario-tests/tests/toolkits/test_image_classifier.py
- scenario-tests/tests/toolkits/test_image_similarity.py
- userguide/image_classifier/how-it-works.md
These were the failing tests in Image Similarity and Image Classifier:
```
=================================== FAILURES ===================================
____________________ VisionFeaturePrintScreenTest.test_get _____________________
self = <test_image_classifier.VisionFeaturePrintScreenTest testMethod=test_get>
def test_get(self):
model = self.model
for field in self.fields_ans:
ans = model._get(field)
self.assertTrue(self.get_ans[field](ans),
>                   '''Get failed in field {}. Output was {}.'''.format(field, ans))
E           AssertionError: False is not true : Get failed in field model. Output was VisionFeaturePrint_Scene.
toolkits/test_image_classifier.py:227: AssertionError
_______________ VisionFeaturePrintScreenTest.test_save_and_load ________________
self = …
```
> Fixes #1371

- src/logger/CMakeLists.txt
- src/logger/logger.hpp
This way nothing gets printed without a check.
> Added CTRL-C interupt checking to logging command 

- .travis.yml
- CMakeLists.txt
- LINUX_INSTALL.md
Resolves https://github.com/apple/turicreate/issues/1419
> 19 02 remove lapack blas deps

- test/optimization/optimization_interface_test.cxx
Fixes https://github.com/apple/turicreate/issues/1425
> Update to failing test.

- CMakeLists.txt
Addresses https://github.com/apple/turicreate/issues/1272
> Switched CMakeLists.txt to use CXX_STANDARD instead of manual flags.

- src/unity/python/turicreate/toolkits/image_classifier/_evaluation.py
- src/visualization/Turi Create Visualization/src/user_interface/src/elements/Explore/Evaluation/Components/TCEvaluationConfusionTable/TCEvaluationConfusionHeader/TCEvaluationConfusionHeaderCells/index.scss
- src/visualization/Turi Create Visualization/src/user_interface/src/elements/Explore/Evaluation/Components/TCEvaluationConfusionTable/TCEvaluationConfusionHeader/index.js
- src/visualization/Turi Create Visualization/src/user_interface/src/elements/Explore/Evaluation/Components/TCEvaluationFooter/index.js
- src/visualization/Turi Create Visualization/src/user_interface/src/elements/Explore/Evaluation/Components/TCEvaluationFooter/index.scss
- src/visualization/Turi Create Visualization/src/user_interface/src/elements/Explore/Evaluation/Components/TCEvaluationImageViewerContainer/index.js
- src/visualization/Turi Create Visualization/src/user_interface/src/elements/Explore/Evaluation/Components/TCEvaluationOverview/index.js
- src/visualization/Turi Create Visualization/src/user_interface/src/elements/Explore/Evaluation/Components/TCEvaluationTable/TCEvaluationHeader/TCEvaluationHeaderCell/index.scss
- src/visualization/Turi Create Visualization/src/user_interface/src/elements/Explore/Evaluation/index.js
- Changed the UI paradigm for predicted values to match the paradigm for actual values
- Added more descriptive labels for the tables
> Initial Bug Fixes

- scripts/requirements.txt
- src/unity/python/setup.py
- src/unity/python/turicreate/__init__.py
- src/unity/python/turicreate/test/test_audio_functionality.py
- src/unity/python/turicreate/toolkits/audio_analysis/__init__.py
- src/unity/python/turicreate/toolkits/audio_analysis/audio_analysis.py
- src/unity/python/turicreate/toolkits/sound_classifier/__init__.py
- src/unity/python/turicreate/toolkits/sound_classifier/_audio_feature_extractor.py
- src/unity/python/turicreate/toolkits/sound_classifier/mel_features.py
- src/unity/python/turicreate/toolkits/sound_classifier/sound_classifier.py
- src/unity/python/turicreate/toolkits/sound_classifier/vggish_input.py
- src/unity/python/turicreate/toolkits/sound_classifier/vggish_params.py
Adds `turicreate.sound_classifier.create(...)` and `turicreate.load_audio(...)`, plus relevant unit tests.
> Sound Classifier -- Initial Version

- src/unity/lib/annotation/annotation_base.cpp
- Added a pragma to only define the asserts in debug mode rather than release
> Image Classifier Check the DataSet

- src/unity/toolkits/coreml_export/MLModel/Requirements.txt
> Drop requests dependency from coremltools

- src/objc/AudioPreprocessing.h
- src/objc/AudioPreprocessing.m
- src/objc/CMakeLists.txt
- src/unity/python/turicreate/test/test_audio_functionality.py
* External code: VGGish preprocessing
* Core ML custom model doing the same preprocessing
* Unit test to make sure they produce the same results
> Audio Preprocessing

- src/capi/TuriCreate.h
- src/capi/impl/capi_visualization.cpp
- src/unity/lib/visualization/plot.hpp
- src/unity/lib/visualization/plot_macos.mm
- test/capi/capi_visualization.cxx
And some unit test coverage for high-level and low-level plot rendering
through C API.
> Add low-level Vega rendering C API

- src/objc/AudioPreprocessing.m
- src/unity/python/turicreate/test/test_audio_functionality.py
- src/unity/python/turicreate/toolkits/_pre_trained_models.py
- src/unity/python/turicreate/toolkits/sound_classifier/_audio_feature_extractor.py
- src/unity/python/turicreate/toolkits/sound_classifier/sound_classifier.py
* Feature preprocessing for exported Core ML models
* Ability to download models (still not actually hosting them)
* Export to Core ML working on Linux
* Fixes Linux only bug
* Fixes bad error handling
> Sound Classifier Improvements

- src/unity/python/turicreate/toolkits/drawing_recognition/drawing_recognition.py
We were importing mxnet in sframe_loader, deferred the imports of sframe_loader in drawing_recognition.py
> Fixed the fire of delaying mxnet

- src/unity/python/turicreate/toolkits/drawing_recognition/util/__init__.py
- src/unity/python/turicreate/toolkits/drawing_recognition/util/_visualization.py
Fixes #1439
Note that this PR has a sequential dependency on #1449 and must be merged only after #1449 is merged in.
> turicreate.drawing_recognition.util.draw_strokes

- scripts/make_wheel.sh
- names that wheel file with manylinux1 instead of linux
> Changes in make_wheel.sh to create wheels that are pip installable. Fixes #927

- src/unity/python/turicreate/test/test_audio_functionality.py
- src/unity/python/turicreate/toolkits/_pre_trained_models.py
We are now hosting the needed models.
> Sound Classifier: download model files

- userguide/image_classifier/README.md
- userguide/supervised-learning/decision_tree_classifier.md
- userguide/supervised-learning/decision_tree_regression.md
- userguide/supervised-learning/linear-regression.md
- userguide/supervised-learning/logistic-regression.md
- userguide/supervised-learning/random_forest_classifier.md
- userguide/supervised-learning/random_forest_regression.md
- userguide/supervised-learning/svm.md
- fixes relative links to sections on different pages of documentation
> Correcting anchor tags for relative links to work correctly. Fixes #1143

- src/unity/python/turicreate/test/test_recommender.py
- src/unity/python/turicreate/toolkits/recommender/util.py
> Exclude parameter of recommend checks user_id type and uses it

- src/unity/python/turicreate/toolkits/_internal_utils.py
- src/unity/python/turicreate/toolkits/drawing_classifier/_sframe_loader.py
- src/unity/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py
- src/unity/python/turicreate/toolkits/drawing_classifier/util/_visualization.py
> Drawing Classifier: added docstrings and cleaned up code

- src/unity/toolkits/activity_classification/ac_data_iterator.cpp
- src/unity/toolkits/activity_classification/ac_data_iterator.hpp
- src/unity/toolkits/activity_classification/activity_classifier.cpp
- src/unity/toolkits/activity_classification/activity_classifier.hpp
- src/unity/toolkits/evaluation/metrics.cpp
- src/unity/toolkits/evaluation/metrics.hpp
For now, prediction only supports output_frequency == 'per_row'
Fixes #1498 
Fixes #1499
> Implement C++ Activity Classifier prediction and evaluation

- src/unity/python/turicreate/toolkits/_pre_trained_models.py
> Renamed pretrained model path

- userguide/drawing_classifier/README.md
- userguide/drawing_classifier/data-preparation.md
> Drawing Classifier User Guide Polish

- src/unity/python/turicreate/test/test_drawing_classifier.py
- src/unity/python/turicreate/toolkits/_pre_trained_models.py
- src/unity/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py
Activated the pretrained model as default for training, and added unit tests as well.
> Drawing Classifier: Activated the pretrained model

- src/unity/python/turicreate/test/test_drawing_classifier.py
- src/unity/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py
> Drawing Classifier: Added predict_topk and output_type to predict

- src/unity/python/turicreate/toolkits/_pre_trained_models.py
- src/unity/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py
> Drawing Classifier: Improved error handling for Validation Set

- src/unity/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py
> Drawing Classifier: Last batch in training and eval was not being loaded in all contexts.

- README.md
Add back links to toolkits which are now launched.
Fixes #1585
> Add back README user guide links

- src/unity/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py
> Drawing Classifier: Non-negativity checks for batch_size, max_iterations

- src/unity/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py
> Drawing Classifier: Modified evaluate error message if target column is not present.

- userguide/drawing_classifier/data-preparation.md
"Rendered drawings" image is placed correctly now.
> Drawing Classifier Userguide Enhancement

- CMakeLists.txt
- src/objc/AudioPreprocessing.h
- src/objc/AudioPreprocessing.m
- src/objc/TuriCreateObjC.h
- src/objc/TuriCreateObjC.m
- src/toolkits/image_deep_feature_extractor/mlmodel_image_feature_extractor.mm
> Changing deployment target to iOS 10.0

- src/unity/toolkits/coreml_export/mlmodel_include.hpp
- src/unity/toolkits/recsys/CMakeLists.txt
- src/unity/toolkits/recsys/models/itemcf.cpp
- src/unity/toolkits/recsys/models/itemcf.hpp
- src/unity/toolkits/recsys/recsys_model_base.cpp
- src/unity/toolkits/recsys/recsys_model_base.hpp
This helps make the exporting of CoreML models much easier.
> Changed some of the lower level API for recsys

- src/unity/python/turicreate/test/test_audio_functionality.py
- src/unity/python/turicreate/toolkits/sound_classifier/sound_classifier.py
- userguide/sound_classifier/advanced-usage.md
> Sound Classifier: allow user to control custom neural network structure

- src/unity/toolkits/activity_classification/activity_classifier.cpp
> Adding training accuracy to Activity Classifier

- test/fileio/fixed_size_cache_manager_test.cxx
Fix for https://github.com/apple/turicreate/issues/1667
> Fixed a compiler warning.

- src/sframe/parallel_csv_parser.cpp
- test/sframe/sframe_csv_test.cxx
Addresses #1692.
The newline delimiting logic when quote characters are used works
by computing the "quote parity" for every new line character, accepting
only new line characters where quote parity is False. This permits
parsing of files of the form
```
user_id, review
123, "good food"
456, "hello
world"
678, "moof"
```
To simplify end of file handling, a new line character is always
inserted into the buffer if not already there when EOF is hit. However,
if there is a mismatched quotechar, this is not recognized as a valid
new line resulting in lines being left in the buffer and ignored
entirely.
The patch is simple, the final new line character at EOF is *always*
a valid new line (flagged with quote_parity=False)
> Fixes CSV parsing for unmatched quotes extending past last line

- src/unity/toolkits/activity_classification/activity_classifier.cpp
- src/unity/toolkits/activity_classification/activity_classifier.hpp
> Adding per_window functionality to C-API Activity Classifier 

- src/unity/python/turicreate/toolkits/_supervised_learning.py
- src/unity/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py
- src/unity/python/turicreate/toolkits/sound_classifier/sound_classifier.py
> Require an exact split for auto validation set generation

- src/unity/python/turicreate/toolkits/recommender/util.py
- src/unity/toolkits/ml_data_2/indexing/column_indexer.hpp
- src/unity/toolkits/ml_data_2/indexing/column_unique_indexer.cpp
- src/unity/toolkits/ml_data_2/indexing/column_unique_indexer.hpp
- src/unity/toolkits/recsys/recsys_model_base.cpp
- src/unity/toolkits/recsys/recsys_model_base.hpp
> Got indexer to correctly index inputs in prediction_recall_by_user API

- src/unity/toolkits/object_detection/object_detector.cpp
- src/unity/toolkits/object_detection/object_detector.hpp
- test/unity/toolkits/object_detection/test_object_detector.cxx
> object_detector::train should take a last pass over all the data to compute model metrics

- src/unity/python/turicreate/toolkits/image_classifier/_evaluation.py
- src/unity/python/turicreate/visualization/__init__.py
- src/unity/python/turicreate/visualization/_plot.py
Fixes #1548
- Fixes the issue where the Window doesn't steal focus when it originally opens.
> Focus Function for the GUI of the Evaluation UI

- src/toolkits/image_deep_feature_extractor/mlmodel_image_feature_extractor.mm
> Image feature extractor - error on bad download

- src/unity/python/turicreate/test/test_audio_functionality.py
- src/unity/python/turicreate/toolkits/sound_classifier/_audio_feature_extractor.py
- src/unity/python/turicreate/toolkits/sound_classifier/sound_classifier.py
> Sound clips less than 975ms should never cause sound classifier crash

- src/unity/python/doc/source/turicreate.toolkits.sound_classifier.rst
- userguide/SUMMARY.md
- userguide/image_classifier/advanced-usage.md
- userguide/sound_classifier/advanced-usage.md
This covers both reusing deep features and tuning the custom neural network configuration. Both of these features will be a part of our next release. This pull request finishes up #1639.
The new Advanced Usage Section is staged here:
https://tobyroseman.github.io/turicreate/docs/userguide/sound_classifier/advanced-usage.html
@madebysasha @jamois @coolioxlr @rplom @yulingtianxia - Please let us know what you think of these new features. We would also be very interested in any other feedback you have about the Sound Classifier Toolkit. Thanks!
> User Guide - Sound Classifier Advanced Usage 

- src/unity/python/turicreate/toolkits/audio_analysis/audio_analysis.py
- src/unity/toolkits/activity_classification/activity_classifier.cpp
- src/unity/toolkits/activity_classification/activity_classifier.hpp
> Adding Validation Accuracy and Loss to C-API of Activity Classifier

- .travis.yml
> Remove sudo tag from travis config

- userguide/text_classifier/README.md
[Reference](https://github.com/apple/turicreate/issues/1297)
> Added dataset and edited code to use it (Text classification)

- src/unity/lib/visualization/vega_spec.cpp
> Correct the axis labels for 1d distribution plots

- src/unity/python/turicreate/toolkits/image_classifier/_evaluation.py
- src/unity/python/turicreate/toolkits/image_classifier/image_classifier.py
> Fixed hard-coded column name in Evaluation

- src/unity/python/turicreate/toolkits/image_classifier/image_classifier.py
> Updated vector to list for Python 3 support

- src/unity/python/turicreate/data_structures/sframe.py
- src/unity/python/turicreate/mx/_mx_sframe_iter.py
Fixes #1739. We seem to only be making this mistake in one place.
> Fix python 3 exception handling

- src/unity/python/turicreate/toolkits/image_classifier/_evaluation.py
- src/unity/python/turicreate/visualization/_plot.py
> Added integer support for Explore

- src/unity/toolkits/activity_classification/activity_classifier.cpp
- src/unity/toolkits/coreml_export/neural_net_models_exporter.cpp
- Provides named inputs. Fixes #1704 
- Merges cellIn and hiddenIn. Fixes #1703
> Changes made in CoreML model exported by C-API activity classifier

- src/unity/python/turicreate/toolkits/style_transfer/_model.py
- src/unity/python/turicreate/toolkits/style_transfer/style_transfer.py
fixes #666 
fixes #1341
- Updated Reflective Padding for Transformer Model
- Updated number of iterations for training the model
- Updated the default loading of pre-trained weights.
> Added Style Transfer Training Improvements

- userguide/text_classifier/README.md
Use training data for training so that predicting and evaluating test data is reasonable (text classification)
> Modify use training data for training (Text classification)

- src/unity/lib/version_number.hpp
- src/unity/python/setup.py
- src/unity/python/turicreate/version_info.py
> Bump version from 5.4 to 5.5

- src/unity/toolkits/activity_classification/ac_data_iterator.cpp
- src/unity/toolkits/activity_classification/ac_data_iterator.hpp
- src/unity/toolkits/activity_classification/activity_classifier.cpp
- src/unity/toolkits/activity_classification/activity_classifier.hpp
- fixes #1766 
- fixes the double print statements
> Refactoring C-API for Activity Classifier 

- src/visualization/Turi Create Visualization.xcodeproj/project.pbxproj
- src/visualization/Turi Create Visualization/Base.lproj/Main.storyboard
- src/visualization/Turi Create Visualization/src/CustomWebKitView.swift
- src/visualization/Turi Create Visualization/src/VegaContainer.swift
- src/visualization/Turi Create Visualization/src/ViewController.swift
> Removed the keypress sound from the TuriCreate Visualization Window

- src/unity/toolkits/activity_classification/activity_classifier.cpp
- src/unity/toolkits/evaluation/metrics.cpp
- src/unity/toolkits/evaluation/metrics.hpp
- src/unity/toolkits/evaluation/unity_evaluation.cpp
- test/unity/toolkits/test_evaluation.cxx
> Add C-API 'compute_classifier_metrics'

- .gitlab-ci.yml
- scenario-tests/run_scenario_tests.sh
- scripts/Dockerfile-Ubuntu-10.04
- scripts/create_docker_images.sh
- scripts/get_docker_image.sh
- scripts/make_wheel.sh
- scripts/python_env.sh
- scripts/run_cpp_tests.py
- scripts/test_wheel.sh
I set it up on gitlab.com using a mirror of GitHub, and now that it's
active and we have a .gitlab-ci.yml file in the repo, it's actually
running on every commit. Hooray!
Except it's broken. This should fix it.
> Fix Gitlab.com CI

- src/unity/python/turicreate/toolkits/_mxnet/_mxnet_to_coreml/_layers.py
- src/unity/python/turicreate/toolkits/_mxnet/_mxnet_to_coreml/_mxnet_converter.py
- src/unity/python/turicreate/toolkits/style_transfer/_model.py
- Updated Padding Technique for MxNet 1.1.0
- Updated CoreML export for new Padding Layer
> Reflective Padding updated for MxNet 1.1.0

- src/unity/python/turicreate/test/test_drawing_classifier.py
- src/unity/python/turicreate/toolkits/_pre_trained_models.py
- src/unity/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py
> Error handling for warm_start + fix for warm_start="quickdraw_245_v0"

- src/unity/toolkits/evaluation/metrics.cpp
- src/unity/toolkits/evaluation/metrics.hpp
- src/unity/toolkits/evaluation/unity_evaluation.cpp
- src/unity/toolkits/neural_net/image_augmentation.hpp
- src/unity/toolkits/object_detection/object_detector.cpp
- src/unity/toolkits/object_detection/od_data_iterator.cpp
- src/unity/toolkits/object_detection/od_data_iterator.hpp
- src/unity/toolkits/object_detection/od_evaluation.cpp
- src/unity/toolkits/object_detection/od_evaluation.hpp
- test/unity/toolkits/object_detection/test_od_evaluation.cxx
> C-API for computing Object Detection metrics from labeled data and predictions

- src/image/numeric_extension/perspective_projection.hpp
> Added Linear Algebra for Transformation Matrix

- src/image/numeric_extension/perspective_projection.hpp
- src/unity/toolkits/drawing_classifier/data_preparation.cpp
- src/unity/toolkits/object_detection/one_shot_object_detection/CMakeLists.txt
- src/unity/toolkits/object_detection/one_shot_object_detection/mapping_function.hpp
- src/unity/toolkits/object_detection/one_shot_object_detection/one_shot_object_detector.cpp
- src/unity/toolkits/object_detection/one_shot_object_detection/parameter_sampler.cpp
- src/unity/toolkits/object_detection/one_shot_object_detection/parameter_sampler.hpp
> Constructing annotations based on the Parametrized Transform

- src/unity/python/turicreate/toolkits/object_detector/util/_visualization.py
> Reporting row number on a draw_bounding_boxes crash

- src/image/image_type.cpp
- src/image/image_type.hpp
> Added constructor for flex_image from boost::gil::rgba8

- .clang-format
- src/unity/toolkits/activity_classification/activity_classifier.cpp
- src/unity/toolkits/activity_classification/activity_classifier.hpp
> C-API of Activity Classifier fixes error in prediction

- src/unity/python/turicreate/toolkits/clustering/dbscan.py
> Fix incorrect name in documentation

- src/unity/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py
> Fixes logs in Drawing Classifier 

- src/unity/python/turicreate/test/test_audio_functionality.py
- src/unity/python/turicreate/toolkits/sound_classifier/_audio_feature_extractor.py
- src/unity/python/turicreate/toolkits/sound_classifier/sound_classifier.py
> Sound Classifier: put sample rate in Core ML metadata

- src/unity/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py
> Fixed a small bug in how class types are handled.

- src/unity/python/turicreate/toolkits/_data_zoo.py
- src/unity/python/turicreate/toolkits/_image_feature_extractor.py
- src/unity/python/turicreate/toolkits/_pre_trained_models.py
- src/unity/python/turicreate/toolkits/one_shot_object_detector/one_shot_object_detector.py
> Added logic to download background files from docs-assets.developer.apple.com

- userguide/drawing_classifier/advanced-usage.md
> Clarifying warm_start in Drawing Classifier user guide

- src/unity/python/turicreate/test/test_drawing_classifier.py
- src/unity/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py
fixes #1941
fixes #1943
fixes #1919
fixes #1931
> Fixes some bugs for drawing classifier

- src/unity/python/turicreate/toolkits/one_shot_object_detector/one_shot_object_detector.py
Per our in-person discussion today.
> Prefix get_augmented_images with an underscore

- src/unity/python/doc/source/turicreate.toolkits.drawing_classifier.rst
- src/unity/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py
Removes list from predict and predict_topk 
fixes #1942
Updating API docs to include draw_strokes
fixes #1952
> Fixes API docs for drawing classifier

- userguide/drawing_classifier/export-coreml.md
> CoreML documentation added for drawing classifier

- src/unity/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py
> Fixes evaluation console, drops missing values before training and fixes time elapsed in training

- src/unity/python/turicreate/toolkits/sound_classifier/sound_classifier.py
> Sound classifier small bug fixes

- src/unity/python/turicreate/toolkits/_internal_utils.py
- src/unity/python/turicreate/toolkits/one_shot_object_detector/one_shot_object_detector.py
- src/unity/python/turicreate/toolkits/one_shot_object_detector/util/__init__.py
- src/unity/python/turicreate/toolkits/one_shot_object_detector/util/_augmentation.py
- src/unity/python/turicreate/toolkits/one_shot_object_detector/util/_error_handling.py
> Added repr and summary.

- src/unity/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py
Unit tests on master should now be passing.
> Fixed tests on master.

- src/unity/python/turicreate/toolkits/_internal_utils.py
> class_name=auto should pick up automatically

- src/unity/lib/annotation/image_classification.cpp
> Ignore existing undefined labels when annotating

- src/unity/python/turicreate/toolkits/drawing_classifier/__init__.py
- added drawing classifier annotate
> Added drawing classifier annotate

- src/unity/toolkits/neural_net/mps_image_augmentation.mm
Any C++ class public or protected method that uses Objective C should have an autorelease pool. Also applies to any functors dispatched to other threads.
> Add autorelease pools to mps_image_augmentation.mm

- .travis.yml
> Remove OSOD unit tests from Travis CI

- BUILD.md
Adding extra information to guide people choosing to use Ninja to build the source.
> add more info in terms of building source with Ninja

- BUILD.md
- src/core/storage/query_engine/planning/optimizations/source_transforms.hpp
- src/python/turicreate/data_structures/sframe.py
- src/python/turicreate/test/test_sframe.py
- test/capi/capi_sarray.cxx
bug fix for https://github.com/apple/turicreate/issues/1716
> bug fix for filter_by None

- src/python/turicreate/toolkits/style_transfer/style_transfer.py
> style transfer docstring update

- src/core/storage/sframe_data/sframe.cpp
- src/core/storage/sframe_interface/unity_sframe_builder.hpp
- src/python/turicreate/data_structures/sframe_builder.py
- src/python/turicreate/test/test_sframe_builder.py
resolved issue #1912. adding error checking logic when writing from const ref object into sframe.
> fix sigfault when appending size mismatched row into SFrameBuilder

- .gitignore
ignore docs generated by doxygen under the root dir
> update gitignore for doxygen

- src/python/turicreate/test/test_drawing_classifier.py
- src/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py
> Fix unit test failures in drawing_classifier 

- src/toolkits/object_detection/object_detector.cpp
Brings the C++ implementation to parity with the Python changes for #2053
> C++ object detector should allow user to specify detection grid size

- src/toolkits/coreml_export/neural_net_models_exporter.cpp
Previously the fact that these inputs are optional was captured only in the text description. They should also be encoded using the `isoptional` field of the `FeatureDescription` proto.
> Exported Non-Maximum Suppression model should describe threshold inputs as optional

- src/core/storage/sframe_interface/unity_sframe.cpp
This gets around the stupid issue with the compiler warning flags.
> Updated code in unity_sframe to not use boost::optional.

- CMakeLists.txt
- src/ml/neural_net/style_transfer/mps_style_transfer.h
- src/ml/neural_net/style_transfer/mps_style_transfer.m
- src/ml/neural_net/style_transfer/mps_style_transfer_utils.h
- src/ml/neural_net/style_transfer/mps_style_transfer_utils.m
- added api Availability for 10.15
> API avaliability

- src/python/turicreate/_sys_util.py
Resolves https://github.com/apple/turicreate/issues/2165.
> Removed an unnneeded C locale override.

- src/python/turicreate/data_structures/sframe.py
- src/python/turicreate/toolkits/image_classifier/_evaluation.py
- src/python/turicreate/visualization/_plot.py
> Inline explore jupyter

- src/core/storage/fileio/fileio_constants.hpp
- src/core/storage/fileio/get_s3_endpoint.cpp
- src/python/turicreate/config/__init__.py
add the doc for `TURI_S3_REGION`.
> add the doc TURI_S3_REGION

- userguide/object_detection/data-preparation.md
Closes #2096 
Removed `~` to make path absolute.
> OD example data path error

- userguide/recommender/coreml-deployment.md
- userguide/sound_classifier/export-coreml.md
Fixes: https://github.com/apple/turicreate/issues/2050.
> Update docs to mention framework packaging

- .travis.yml
Install virtualenv before running build-script.
> Fixed travis Python 3.6 build

- src/python/turicreate/toolkits/style_transfer/style_transfer.py
Helps diagnose the problems present in #1899
> Added checkpointing functionality to the style transfer model

- userguide/drawing_classifier/how-it-works.md
> Adding information about known issue in DC in user guide

- src/visualization/client/Turi Create Visualization/src/VegaContainer.swift
* Improves JavaScript error handling and debugging; error messages in
the VegaContainer in the GUI app are now largely on par with the
VegaRenderer (backend) code, with a nicely formatted message
containing the source, line number, column number, and exception message.
* Still missing: call stacks. This is seemingly not possible in
`WKWebView` with a `file://` URL -- the exception object is undefined
and doesn't provide a stack trace (for that matter, all other JS-side
debug info is missing). In the future, if we are loading over http(s)
instead, we could potentially get call stacks on error.
> Better JavaScript error handling in GUI app

- src/python/turicreate/toolkits/activity_classifier/_activity_classifier.py
- src/python/turicreate/toolkits/activity_classifier/util.py
- userguide/activity_classifier/README.md
- userguide/activity_classifier/data-preparation.md
- userguide/drawing_classifier/data-preparation.md
Mostly documentation (API and user guide) changes.
> Minor Updates

- src/core/storage/sframe_interface/unity_sframe.cpp
- src/python/turicreate/data_structures/sframe.py
- test/unity/unity_sframe.cxx
As it is documented in #2222, I move the logic from the frontend to the backend.
> unity_sframe::append reorders sframe if needed

- src/ml/neural_net/CMakeLists.txt
- src/ml/neural_net/mps_descriptor_utils.m
- src/ml/neural_net/mps_layer_helper.h
- src/ml/neural_net/mps_layer_helper.mm
- src/ml/neural_net/style_transfer/mps_style_transfer.h
- src/ml/neural_net/style_transfer/mps_style_transfer.m
- src/ml/neural_net/style_transfer/mps_style_transfer_backend.hpp
- src/ml/neural_net/style_transfer/mps_style_transfer_backend.mm
- src/ml/neural_net/style_transfer/mps_style_transfer_decoding_node.mm
- src/ml/neural_net/style_transfer/mps_style_transfer_encoding_node.mm
- src/ml/neural_net/style_transfer/mps_style_transfer_residual_node.mm
- src/ml/neural_net/style_transfer/mps_style_transfer_utils.m
- Corrected un-initalized code in the style transfer descriptors
- Added a `model_backend` implementation for the Style Transfer network.
- Tested weight initialization for the training and inference graph
> Style Transfer Backend Code

- src/ml/neural_net/style_transfer/mps_style_transfer_backend.hpp
- src/ml/neural_net/style_transfer/mps_style_transfer_backend.mm
- changed Mac OS version checking from runtime to compile time check
> Mac OS 10.14 Compile Time Check

- .gitignore
> add more gitignore

- src/python/turicreate/toolkits/image_classifier/image_classifier.py
> Image Classifier Should Error Out Early on Bad Input

- src/python/turicreate/__init__.py
- src/python/turicreate/toolkits/recommender/__init__.py
since I have LazyCallable, now I can make recommender completely lazy-loaded, so does aggregate.
> more aggressive reduction on import time

- src/ml/neural_net/mps_graph_trainer.mm
- Added an `#ifdef` for a MacOS version lower than 10.15
> Added a fix for building on a system lower than MacOS 10.15

- src/python/turicreate/toolkits/drawing_classifier/_model_architecture.py
- src/python/turicreate/toolkits/drawing_classifier/_tf_drawing_classifier.py
- src/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py
Drawing Classifier can now train in TensorFlow using the `_advanced_usage` option `use_tensorflow`. 
- `__init__()` initializes the model architecture and train optimization and loads initial MXNET weights 
- `tf_train_model()` trains the model
- `get_weights()` fetches TF weights, performs formatting to place back in MXNET model
> Drawing Classifier TF Implementation

- src/ml/neural_net/style_transfer/mps_style_transfer_utils.m
- Here is a fix for the NaNs in TCMPS Style Transfer.
> Fixing Channel Size in VGG Network

- src/visualization/vega_renderer/TCVegaJSCanvas.m
> Fixed Logging Error VegaRenderer

- userguide/sound_classifier/export-coreml.md
https://github.com/apple/turicreate/issues/1712
Update the audio input example to chunk the data in with zero padding such that it can work with any legnth material.
> Sound Classifier predict for clips less than 975 milliseconds

- src/python/turicreate/toolkits/image_classifier/image_classifier.py
> Better error and validation for #2301

- src/visualization/server/escape.cpp
> add \x as one of the escaped sequence

- src/ml/neural_net/mps_compute_context.mm
- src/ml/neural_net/tf_compute_context.cpp
- src/python/turicreate/toolkits/object_detector/_tf_model_architecture.py
- src/python/turicreate/toolkits/object_detector/object_detector.py
- src/toolkits/object_detection/object_detector.cpp
- src/toolkits/object_detection/object_detector.hpp
Object Detector TF integration in C++
> Object Detector TF beta release

- src/python/turicreate/toolkits/style_transfer/style_transfer.py
Checks if the platform is MacOS 10.15
> Added check for MacOS Platform

- src/ml/neural_net/compute_context.cpp
- src/ml/neural_net/compute_context.hpp
- src/ml/neural_net/mps_compute_context.mm
- src/ml/neural_net/tf_compute_context.cpp
- src/python/turicreate/toolkits/_model.py
- src/python/turicreate/toolkits/activity_classifier/_activity_classifier.py
- src/toolkits/activity_classification/activity_classifier.cpp
- src/toolkits/activity_classification/activity_classifier.hpp
To check if this works  -
Also `pip install tensorflow==1.14.0` in the virtual environment 
```model = tc.activity_classifier.create(data, session_id='exp_id', target='activity', _advanced_parameters={'use_tensorflow':True})```
> Python frontend calls C++ implementation of AC/ Tensorflow

- test/CMakeLists.txt
- test/neural_net/CMakeLists.txt
- test/neural_net/style_transfer.cxx
Scaffolding for the Style Transfer MPS Tests.
> Added Scaffolding for the Style Transfer MPS tests

- src/python/turicreate/toolkits/image_classifier/_evaluation.py
* Always flush explicitly when writing to the subprocess. In Python 2,
newline characters cause flushes, and in Python 3 they don't seem to.
* Always convert to JSON and add a newline to responses while still in
Python 2 or 3's native string type.
* Always encode('utf-8'). In Python 2, this is a no-op (str is already
utf-8 encoded bytes) and in Python 3, this creates utf-8 encoded
bytes from a unicode object.
Fixes `evaluate().explore()` hanging on Python 3 due to
newline characters not flushing the I/O buffer, and subsequent crashes
due to improperly encoded string objects after fixing the hang.
> Fix evaluate().explore() on Python 3

- src/python/setup.py
Added the tensorflow so file to the `setup.py`.
> Added `.so` to setup.py

- src/python/turicreate/__init__.py
Added fix to lazily import the `config`
> Added fix to lazily import the `config`

- src/python/turicreate/toolkits/style_transfer/style_transfer.py
> Added the correct way to update weights from MPS to Python

- deps/cmake/ExternalProjectLibCurl.cmake
> Suppress warnings in libcurl dependency

- src/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py
Moved data init for forward() pass inside the TF if-condition.
> Drawing Classifier TF mxnet data init for forward pass

- src/ml/neural_net/CMakeLists.txt
- src/ml/neural_net/compute_context.hpp
- src/ml/neural_net/tf_compute_context.cpp
- src/ml/neural_net/tf_compute_context.hpp
> Fixes loading the libtctensorflow in Linux

- src/python/turicreate/test/test_one_shot_object_detector.py
- src/python/turicreate/toolkits/one_shot_object_detector/util/_error_handling.py
> Added support for single image input to OSOD, along with a unit test.

- src/python/turicreate/_deps/__init__.py
fix always true for HAS_NUMPY.
better use class_name.static_variable.
In related to #2359
> address concern in HAS_NUMPY

- src/python/turicreate/toolkits/object_detector/object_detector.py
- src/toolkits/object_detection/object_detector.cpp
Usage from Python:
`model = tc.object_detector.create(data, 'annotation', max_iterations=25, _advanced_parameters= {'mlmodel_path' : 'darknet.mlmodel', 'use_tensorflow' : True})`
> Python frontend calls C++ OD TF impl

- src/python/turicreate/__init__.py
> Removes deprecated warning on import turicreate

- src/python/turicreate/toolkits/_pre_trained_models.py
- src/python/turicreate/toolkits/object_detector/object_detector.py
* `darknet.mlmodel` hosted on `devpubs`
* Added model loading in OD
To inspect the meta data in the mlmodel file: https://docs-assets.developer.apple.com/turicreate/models/darknet.mlmodel
> Darknet mlmodel hosted and called in OD

- src/ml/neural_net/weight_init.cpp
- src/ml/neural_net/weight_init.hpp
- src/toolkits/activity_classification/activity_classifier.cpp
- src/toolkits/activity_classification/activity_classifier.hpp
close #2378 
Fix the import function for python model.
> Fix "random_seed" state not found" bug for AC import for python model

- src/toolkits/object_detection/one_shot_object_detection/util/parameter_sampler.cpp
- src/toolkits/object_detection/one_shot_object_detection/util/parameter_sampler.hpp
- test/unity/toolkits/object_detection/CMakeLists.txt
- test/unity/toolkits/object_detection/one_shot_object_detection/CMakeLists.txt
- test/unity/toolkits/object_detection/one_shot_object_detection/test_parameter_sampler.cxx
Wrote one test to sanity check the distributions of the parameters sampled. This test should catch any software bugs with regard to generating angles not in tune with the mean and standard deviation specified.
> One Shot C++ unit tests: a start

- src/ml/neural_net/model_spec.cpp
- src/ml/neural_net/model_spec.hpp
Added InstanceNorm layer to `model_spec.cpp`
> Added instance norm to the turi::model_spec

- src/ml/neural_net/compute_context.hpp
- src/ml/neural_net/mps_compute_context.hpp
- src/ml/neural_net/mps_compute_context.mm
- src/ml/neural_net/style_transfer/mps_style_transfer_backend.hpp
- src/ml/neural_net/style_transfer/mps_style_transfer_backend.mm
- src/ml/neural_net/tf_compute_context.cpp
- src/ml/neural_net/tf_compute_context.hpp
Added an implementation for creating the style transfer compute context. Had to refactor the `style_transfer_base` code to work with an externally defined command queue.
> Style Transfer Compute Context

- src/ml/neural_net/mps_compute_context.mm
- src/ml/neural_net/tf_compute_context.cpp
- Added an ifdef in the compute context for MPS to compile on systems lower than 10.15.
> Added #ifdef in Compute Context for MacOS 10.15

- test/unity/toolkits/object_detection/test_object_detector.cxx
> Added style_transfer to the mps_compute_context

- src/ml/neural_net/mps_layers.mm
Intentionally keeping the issue open, since this change doesn't really
fix it; we still need to move to a new API at some point soon.
> Suppress warning for issue #2232

- src/core/storage/query_engine/operators/lambda_transform.hpp
This PR resolves #2066 
Unclear error message in apply method when most values are None
> Unclear error message in apply method when most values are None #2066

- src/core/storage/sframe_interface/unity_sframe.cpp
> bug fix for https load failure

- src/ml/neural_net/tf_compute_context.cpp
- src/python/turicreate/toolkits/_tf_utils.py
- src/python/turicreate/toolkits/activity_classifier/_tf_model_architecture.py
- src/toolkits/activity_classification/activity_classifier.cpp
- src/toolkits/object_detection/object_detector.cpp
- src/toolkits/util/CMakeLists.txt
- src/toolkits/util/training_utils.cpp
- src/toolkits/util/training_utils.hpp
> Prints right device while training using TF

- src/python/turicreate/toolkits/image_classifier/_annotate.py
This PR resolves #1915 
Annotations should error out on empty Frame
> Annotations should error out on empty Frame

- test/unity/toolkits/neural_net/neural_net_mocks.hpp
Fix build failure in C++ tests.
> Added create_drawing_classifier to test/ml/neural_net_mocks

- src/python/turicreate/extensions.py
- src/toolkits/nearest_neighbors/distances.hpp
This PR resolves #1233 
Unclear error message when calculating jaccard distance
> Unclear error message when calculating jaccard distance

- src/python/turicreate/data_structures/image.py
This PR resolves #1269 
Image not show on Google Colab Jupyter Notebook
> Image not show on Google Colab Jupyter Notebook

- src/toolkits/drawing_classifier/drawing_classifier.cpp
- test/unity/toolkits/drawing_classifier/test_dc_serialization.cxx
a small change. let's get it in fast.
> remove model spec suffix

- src/ml/neural_net/model_spec.hpp
- src/toolkits/drawing_classifier/drawing_classifier.cpp
- src/toolkits/drawing_classifier/drawing_classifier.hpp
- test/unity/toolkits/drawing_classifier/test_dc_serialization.cxx
__MY OVERVIEW__
- save and load impl
- corresponding test
__MY SUMMARY__
[Y] provide unittest? [Y/N]
[Y] pass the test pipeline? [Y/N]
> dc save and load

- src/toolkits/style_transfer/style_transfer.cpp
- src/toolkits/style_transfer/style_transfer.hpp
- src/toolkits/style_transfer/style_transfer_data_iterator.cpp
- src/toolkits/style_transfer/style_transfer_data_iterator.hpp
- Refactored Data iterator to have a train parameter
- Added Predict to the style_transfer wrapper class
> Added style_transfer predict

- src/python/turicreate/toolkits/drawing_classifier/_tf_drawing_classifier.py
- src/toolkits/drawing_classifier/dc_data_iterator.cpp
- src/toolkits/drawing_classifier/drawing_classifier.cpp
- test/unity/toolkits/drawing_classifier/test_drawing_classifier.cxx
Currently, works with no validation data, for one iteration (until `predict` is called in drawing_classifier.cpp:570)
Repro steps:
```python
import turicreate.toolkits.libtctensorflow
data = tc.SFrame('train.sframe/')
model = tc.extensions.drawing_classifier()
model.train(data, 'label', 'image', tc.SFrame())
```
> End to end model.train for Drawing Classifier C++

- src/python/turicreate/test/test_object_detector.py
Fix the 'training_average_precision' to dictionary type.
> Fix the test case for OD test_get

- src/python/turicreate/toolkits/sound_classifier/_mx_sound_classifier.py
- src/python/turicreate/toolkits/sound_classifier/sound_classifier.py
Removed MXNet impl from Sound Classifier `create()` and `CustomModel` class into an MXNet specific class `MultiLayerPerceptronMXNetModel`. The changes also support save and load from old impl to the new one. 
Remaining MXNet not replaced yet are: MXNet data iterator and metric calculator.
> Moved MXNet implementation from Sound Classifier into a new class

- scripts/requirements.txt
- src/python/setup.py
- src/python/turicreate/test/test_activity_classifier.py
- src/python/turicreate/test/test_audio_functionality.py
- src/python/turicreate/test/test_drawing_classifier.py
- src/python/turicreate/test/test_image_classifier.py
- src/python/turicreate/test/test_image_similarity.py
- src/python/turicreate/test/test_object_detector.py
- src/python/turicreate/test/test_one_shot_object_detector.py
- src/python/turicreate/test/test_sframe_sequence_iterator.py
- src/python/turicreate/test/test_style_transfer.py
- src/python/turicreate/toolkits/_image_feature_extractor.py
- src/python/turicreate/toolkits/_mxnet/_mx_sframe_iter.py
- src/python/turicreate/toolkits/_pre_trained_models.py
- src/python/turicreate/toolkits/image_classifier/image_classifier.py
- src/python/turicreate/toolkits/image_similarity/image_similarity.py
- src/toolkits/image_deep_feature_extractor/mlmodel_image_feature_extractor.mm
This pull request does not handle batching predictions from the feature extractor. This will happen in a separate pull request.
> TensorFlow Feature Extractors for IC and IS

- src/ml/neural_net/tf_compute_context.cpp
- src/python/turicreate/toolkits/_tf_utils.py
Fix the crash for invalid conversion from Python side to vector<string>.
> OD tf fixed get_gpu_name.

- src/python/turicreate/test/test_drawing_classifier.py
> enable evaluate test

- src/python/turicreate/data_structures/sframe.py
This PR resolves #2484 
Issue for supporting Google Colab Jupyter Notebook under sframe.explore() function
> Issue for supporting Google Colab Jupyter Notebook under sframe.explore

- src/python/turicreate/visualization/_plot.py
This PR resolves #2483 
Issue for supporting Google Colab Jupyter Notebook under plot.show() function
> Issue for supporting Google Colab Jupyter Notebook under plot.show

- src/toolkits/object_detection/object_detector.hpp
- test/unity/toolkits/object_detection/test_object_detector.cxx
@nickjong As per @jakesabathia2 suggestion this default value is set to false
> Added default argument to get test_object_detector to compile.

- src/python/turicreate/test/test_models.py
- src/python/turicreate/test/test_sframe.py
- src/python/turicreate/toolkits/_model.py
> Load model from s3 path

- src/python/turicreate/test/test_object_detector.py
- src/toolkits/object_detection/object_detector.cpp
> OD two fixes.

- userguide/activity_classifier/README.md
- userguide/drawing_classifier/README.md
- userguide/image_classifier/README.md
- userguide/image_classifier/advanced-usage.md
- userguide/image_similarity/README.md
- userguide/object_detection/README.md
- userguide/one_shot_object_detection/README.md
- userguide/recommender/coreml-deployment.md
- userguide/recommender/using-trained-models.md
- userguide/sound_classifier/README.md
- userguide/style_transfer/README.md
Make updates to paths in userguide, make consistent our model naming scheme.
> Userguide updates and fixes

- src/python/turicreate/data_structures/sarray.py
- src/python/turicreate/test/test_sarray.py
This PR resolves #1761 
Wrong behavior for nan converting from float to int
> Wrong behavior for nan converting from float to int

- src/python/turicreate/toolkits/activity_classifier/_activity_classifier.py
- src/python/turicreate/toolkits/object_detector/object_detector.py
- src/python/turicreate/toolkits/style_transfer/style_transfer.py
- Fixed the return for export_coreml
> Return to CorerML should be a void function.

- src/python/turicreate/data_structures/sframe.py
- src/python/turicreate/test/test_sframe.py
This PR resolves #2569 
SFrame plus operator should append
> Enhancement_SFrame_plus_operator_should_append

- src/python/turicreate/test/test_object_detector.py
- src/python/turicreate/test/test_one_shot_object_detector.py
- src/python/turicreate/toolkits/object_detector/object_detector.py
- src/python/turicreate/toolkits/one_shot_object_detector/one_shot_object_detector.py
fix
test_get
test_export_coreml
test_create_with_single_image
test_repr
> Osod fixed

- userguide/object_detection/export-coreml.md
Fixes https://github.com/apple/turicreate/issues/798.
> Add guide of how to use confidence thresholds with the Vision framework.

- src/python/turicreate/test/test_one_shot_object_detector.py
Make the max_iteration to 1 (instead of 1000...).
> accelerate OSOD unit test

- .gitlab-ci.yml
- Added Build Python 3.7 for Linux
- Added Test Python 3.7 for Linux
> Added Python 3.7 to the gitlab.yaml build file

- src/python/turicreate/test/test_drawing_classifier.py
Enabled 2 passing tests that were accidentally marked xFailed.
> DC: Enabled the x-fail drawing test.

- src/ml/neural_net/mps_compute_context.hpp
- src/ml/neural_net/mps_compute_context.mm
- src/toolkits/style_transfer/style_transfer.cpp
> added #ifdef MacOS 10.15

- src/core/storage/sframe_interface/unity_sframe.cpp
- src/python/turicreate/test/test_sframe.py
This PR resolve #804 
Cannot export an empty SFrame
> Cannot export an empty SFrame

- src/toolkits/style_transfer/style_transfer.cpp
- Fixed small errors in loading a custom model in Style Transfer.
> Fixed Custom Model loading in Style Transfer

- src/python/turicreate/toolkits/_model.py
- need to load libtctensorflow for load model to pick it up in the compute_context
> Added import of libtctensorflow on Load Model

- .gitlab-ci.yml
Some commands in the gitlab scripts failed, but the error did not propagate to cause the task to fail.  This fixes that bug.
> Fixed random failures in .gitlab running scripts.

- src/python/turicreate/data_structures/sarray.py
- src/python/turicreate/test/test_sarray.py
This PR resolves #2390 
Appending Empty SArray Should Ignore Type
> Appending Empty SArray Should Ignore Type

- src/python/turicreate/toolkits/object_detector/_tf_model_architecture.py
fixes #2616
Passes all unit tests after the change (python and cpp)
> Changes padding for first five pooling layers TF OD

- src/python/turicreate/toolkits/drawing_classifier/_tf_drawing_classifier.py
- src/toolkits/drawing_classifier/drawing_classifier.cpp
- src/toolkits/drawing_classifier/drawing_classifier.hpp
fixes #1907 
Not breaking any python and CPP tests on my machine
> Removing training as well as validation loss for DC

- src/python/turicreate/test/test_text_analytics.py
- src/toolkits/feature_engineering/word_counter.cpp
- src/toolkits/feature_engineering/word_trimmer.cpp
This PR resolves #954 
Dictionary input to count_words
> Dictionary input to count_words

- src/core/logging/table_printer/table_element_printers.cpp
- src/core/logging/table_printer/table_element_printers.hpp
- Separated table printing from formatting for time.
> Separated out table printer printing and formatting for time

- .travis.yml
- src/python/turicreate/toolkits/_image_feature_extractor.py
- src/python/turicreate/toolkits/_tf_utils.py
- src/python/turicreate/toolkits/activity_classifier/_activity_classifier.py
- src/python/turicreate/toolkits/activity_classifier/_tf_model_architecture.py
- src/python/turicreate/toolkits/drawing_classifier/_tf_drawing_classifier.py
- src/python/turicreate/toolkits/object_detector/_tf_model_architecture.py
- src/python/turicreate/toolkits/style_transfer/_tf_model_architecture.py
> Suppress warnings for tf

- src/python/turicreate/toolkits/object_detector/object_detector.py
> OD invalid inputs

- src/python/turicreate/test/test_drawing_classifier.py
- src/python/turicreate/toolkits/drawing_classifier/_tf_drawing_classifier.py
> DC: Fixes crash when no validation_set is passed (auto)

- src/toolkits/style_transfer/style_transfer.cpp
- Added stylization to the predict method of style_transfer.cpp
> Added Progress Printing to Stylization method

- src/toolkits/style_transfer/style_transfer.cpp
- Use MPS Compute Context when MPS exists not when Apple exists.
> Change has apple to HAS_MPS when using the MPS_Compute_Context

- .travis.yml
- src/python/turicreate/toolkits/_image_feature_extractor.py
Restores the asynchronous batching mechanism from the 5.8 implementation. For reviewing convenience, the first commit is a verbatim (byte-for-byte) copy and paste of the original MXNet 5.8 implementation of `extract_features`. Then the second commit can be reviewed both as a diff from master and from the first commit.
Fixes #2639, fixes #2652
> Implement batching and pipelining for image feature extraction with TF

- src/ml/neural_net/style_transfer/mps_style_transfer.m
- src/toolkits/style_transfer/style_transfer.cpp
- added crop to Objective C in MPS
- moved progress printing table footer to the proper place
- added index to predict in MPS style transfer
> Added crop functionality to MPS Objective C

- src/toolkits/style_transfer/style_transfer.cpp
- added verbosity for setting max_iterations in style transfer
> Added printing to style transfer for verbosity on `max_iterations`

- src/python/turicreate/toolkits/one_shot_object_detector/one_shot_object_detector.py
Our travis settings ignores all errors that are ERROR in pytest which seems to happen when the class setup fails. 
```
turicreate/test/test_one_shot_object_detector.py::OneObjectDetectorSmokeTest::test__list_fields ERROR                                                                                                                                  [  5%]
turicreate/test/test_one_shot_object_detector.py::OneObjectDetectorSmokeTest::test_create_with_empty_dataset ERROR                                                                                                                     [ 11%]
turicreate/test/test_one_shot_object_detector.py::OneObjectDetectorSmokeTest::test_create_with_missing_target ERROR …
```
> Fixed error in one-shot tests.

- src/python/turicreate/test/test_one_shot_object_detector.py
- src/python/turicreate/toolkits/one_shot_object_detector/one_shot_object_detector.py
Since this code path is not checked by our Travis CI, let's merge on approval.
Fixes Python unit test failures in OSOD.
> OSOD: Removed check for ObjectDetector_beta, fixed iou_threshold range error

- src/python/turicreate/toolkits/object_detector/_tf_image_augmenter.py
> Use a fresh tf.Graph for each data augmentation batch

- src/ml/neural_net/mps_layer_instance_norm_data_loader.h
- src/ml/neural_net/mps_layer_instance_norm_data_loader.mm
- src/ml/neural_net/style_transfer/mps_style_transfer.m
- src/ml/neural_net/style_transfer/mps_style_transfer_decoding_node.mm
- src/ml/neural_net/style_transfer/mps_style_transfer_encoding_node.mm
- src/ml/neural_net/style_transfer/mps_style_transfer_residual_node.mm
- src/ml/neural_net/style_transfer/mps_style_transfer_transformer_network.mm
> Got Multiple Styles to work in MPS

- src/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py
Pass the user-requested metric to C++ to trigger error handling
> Compute user-requested metric (not auto) first

- src/python/turicreate/test/test_object_detector.py
- src/toolkits/object_detection/object_detector.cpp
- src/toolkits/object_detection/object_detector.hpp
fix https://github.com/apple/turicreate/issues/2748
> od output regression evalaution.

- src/python/turicreate/toolkits/style_transfer/_sframe_loader.py
This PR resolves #647 
use try and except block around StopIteration or avoid StopIteration completely
> StopIteration changes

- src/python/turicreate/toolkits/audio_analysis/audio_analysis.py
This PR resolves #2686 
turicreate.load_audio does not fail on invalid path
> turicreate.load_audio does not fail on invalid path

- src/python/turicreate/toolkits/activity_classifier/_activity_classifier.py
This PR resolves #2689 
Activity Classifier Name Error with Advanced Parameters
> Activity Classifier Name Error with Advanced Parameters

- src/ml/neural_net/tf_compute_context.cpp
- src/python/turicreate/test/test_object_detector.py
- src/python/turicreate/toolkits/object_detector/_tf_model_architecture.py
fixed https://github.com/apple/turicreate/issues/2768
> od grid_shape fixed for TF.

- src/python/turicreate/toolkits/_image_feature_extractor.py
- src/python/turicreate/toolkits/_tf_utils.py
- src/python/turicreate/toolkits/activity_classifier/_tf_model_architecture.py
- src/python/turicreate/toolkits/drawing_classifier/_tf_drawing_classifier.py
- src/python/turicreate/toolkits/object_detector/_tf_model_architecture.py
- src/python/turicreate/toolkits/sound_classifier/_audio_feature_extractor.py
- src/python/turicreate/toolkits/sound_classifier/_tf_sound_classifier.py
- src/python/turicreate/toolkits/style_transfer/_tf_model_architecture.py
> Suppress GPU usage in TensorFlow when TC num_gpus set to 0

- src/toolkits/object_detection/object_detector.cpp
- src/toolkits/object_detection/object_detector.hpp
fix https://github.com/apple/turicreate/issues/2786
> OD difference in predictions between MPS and MXNet

- src/python/turicreate/toolkits/object_detector/_tf_model_architecture.py
fix https://github.com/apple/turicreate/issues/2769
> od tensorflow regression

- src/python/turicreate/test/test_audio_functionality.py
- src/python/turicreate/toolkits/sound_classifier/_tf_sound_classifier.py
- src/python/turicreate/toolkits/sound_classifier/sound_classifier.py
* Changed Adam to NAG optimizer 
* Set `max_iterations` to 100 for tests which need longer to converge.
> Change Adam to NAG Optimizer in SC TF

- src/ml/neural_net/tf_compute_context.cpp
- src/python/turicreate/toolkits/_image_feature_extractor.py
- src/python/turicreate/toolkits/_tf_utils.py
- src/python/turicreate/toolkits/activity_classifier/_tf_model_architecture.py
- src/python/turicreate/toolkits/drawing_classifier/_tf_drawing_classifier.py
- src/python/turicreate/toolkits/object_detector/_tf_model_architecture.py
- src/python/turicreate/toolkits/sound_classifier/_tf_sound_classifier.py
- src/python/turicreate/toolkits/style_transfer/_tf_model_architecture.py
For Reviewers:
Changes in `src/python/turicreate/toolkits/_tf_utils.py` are just to fix tab/space inconsistency. 
Please review changes in all other files.
Fixes #2777 
Internal tests passed.
> Set the TF_CPP_MIN_LOG_LEVEL to disable TF Info Logs

- src/python/turicreate/test/test_object_detector.py
- src/python/turicreate/toolkits/object_detector/object_detector.py
- src/toolkits/object_detection/object_detector.cpp
fix https://github.com/apple/turicreate/issues/2795
> Od coreml meta

- src/python/turicreate/test/test_recommender.py
- src/python/turicreate/toolkits/recommender/util.py
- src/toolkits/recsys/models/itemcf.cpp
- src/toolkits/recsys/models/itemcf.hpp
- src/toolkits/recsys/recsys_model_base.cpp
- src/toolkits/recsys/recsys_model_base.hpp
fix https://github.com/apple/turicreate/issues/2794
> Recommender meta

- src/python/turicreate/test/test_drawing_classifier.py
- src/toolkits/drawing_classifier/drawing_classifier.cpp
#2785 #2784
early termination of a training job if data contains na. 
Also, this pr reorganized `init_training` a little bit.
> check na data at init_training

- src/python/turicreate/test/test_one_shot_object_detector.py
- src/python/turicreate/toolkits/one_shot_object_detector/one_shot_object_detector.py
fix https://github.com/apple/turicreate/issues/2817
> osod export coreml.

- src/python/turicreate/test/test_style_transfer.py
- src/python/turicreate/toolkits/style_transfer/style_transfer.py
- src/toolkits/style_transfer/style_transfer.cpp
> Fixes backcompat issue with model.__repr__() in ST.

- src/python/turicreate/test/test_style_transfer.py
- src/toolkits/style_transfer/style_transfer.cpp
fix https://github.com/apple/turicreate/issues/2810
> Style transfer

- src/python/turicreate/test/test_style_transfer.py
- Breaking unit test in master due to my final commit in #2810
> Fixed breaking unit test in master.

- src/python/turicreate/toolkits/object_detector/_tf_model_architecture.py
- Matched MxNet and TF Loss computation in OD
> OD Loss Computation

- src/python/turicreate/test/test_object_detector.py
- src/toolkits/object_detection/object_detector.cpp
- test/unity/toolkits/object_detection/test_object_detector.cxx
close https://github.com/apple/turicreate/issues/2830.
> OD predict method should ignore the annotation column if it's present in the input data.

- src/python/turicreate/test/test_object_detector.py
- src/python/turicreate/toolkits/object_detector/object_detector.py
- src/toolkits/object_detection/od_data_iterator.cpp
fix  https://github.com/apple/turicreate/issues/2827
fix https://github.com/apple/turicreate/issues/2828
> OD seg-faults when annotation labels contains "None" in them.

- src/python/turicreate/test/test_activity_classifier.py
- src/python/turicreate/toolkits/activity_classifier/_activity_classifier.py
https://github.com/apple/turicreate/issues/2837
> Validation for inputs for AC batch

- src/unsupported_python/setup.py
> Update pip unsupported error message

- src/unsupported_python/README.md
- src/unsupported_python/setup.py
Bump the version.
Document when and how to make the egg.
> More changes for generating an egg

- src/python/turicreate/test/test_object_detector.py
- src/toolkits/object_detection/od_data_iterator.cpp
https://github.com/apple/turicreate/issues/2833
> [6.1] OD bounding box co-ordinates cannot contain None values

- CMakeLists.txt
CMake 12 doesn't support CMP0077 policy
> Fix configure script.

- src/python/turicreate/toolkits/image_classifier/image_classifier.py
> Fix Image Classifier docstring link

- CMakeLists.txt
- src/capi/framework/tc_capi_exports_linux.ver
- src/capi/impl/capi_operators.cpp
This can be merged post 6.0 release.
> C API bug fixes

- src/python/turicreate/test/test_one_shot_object_detector.py
- src/python/turicreate/toolkits/one_shot_object_detector/one_shot_object_detector.py
fix https://github.com/apple/turicreate/issues/2863
fix https://github.com/apple/turicreate/issues/2862
> one-shot od model summary.

- src/python/turicreate/test/test_activity_classifier.py
- src/python/turicreate/toolkits/activity_classifier/_activity_classifier.py
https://github.com/apple/turicreate/issues/2841
> [6.1] Ac missing validation should be dropped

- src/python/turicreate/test/test_activity_classifier.py
- src/toolkits/activity_classification/ac_data_iterator.cpp
close https://github.com/apple/turicreate/issues/2844
> [6.1] Ac data with missing feature for predict/classify/predict_topk/evaluate.

- src/python/turicreate/test/test_activity_classifier.py
- src/python/turicreate/toolkits/activity_classifier/_activity_classifier.py
https://github.com/apple/turicreate/issues/2855
> [6.1] AC invalid k for predict_topk.

- src/python/turicreate/test/test_style_transfer.py
> Refactor Style Transfer Unit Test

- src/python/turicreate/test/test_style_transfer.py
- src/python/turicreate/toolkits/style_transfer/style_transfer.py
- userguide/style_transfer/how-it-works.md
> Minor Fixes for Style Transfer

- src/python/turicreate/test/test_audio_functionality.py
- src/python/turicreate/toolkits/sound_classifier/sound_classifier.py
> sc invalid k predict_topk

- src/python/turicreate/test/test_audio_functionality.py
- src/python/turicreate/toolkits/sound_classifier/sound_classifier.py
> sc invalid batch_size.

- src/python/turicreate/test/test_audio_functionality.py
- src/python/turicreate/toolkits/sound_classifier/sound_classifier.py
> sc invalid custom layers

- src/python/turicreate/test/test_audio_functionality.py
- src/python/turicreate/toolkits/sound_classifier/sound_classifier.py
> sc invalid max_iterations

- src/toolkits/style_transfer/style_transfer.cpp
> duplicated printer for the last entry of each batch

- src/toolkits/drawing_classifier/drawing_classifier.cpp
> Fixes bug in save/load in DC model

- src/python/turicreate/test/test_activity_classifier.py
- src/python/turicreate/test/test_drawing_classifier.py
- src/python/turicreate/test/test_object_detector.py
- src/python/turicreate/test/test_style_transfer.py
- src/python/turicreate/test/util.py
- src/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py
- src/python/turicreate/toolkits/object_detector/object_detector.py
- src/python/turicreate/toolkits/style_transfer/style_transfer.py
- src/toolkits/activity_classification/activity_classifier.cpp
- src/toolkits/drawing_classifier/drawing_classifier.cpp
- src/toolkits/drawing_classifier/drawing_classifier.hpp
- src/toolkits/object_detection/object_detector.cpp
- src/toolkits/style_transfer/style_transfer.cpp
- src/toolkits/style_transfer/style_transfer.hpp
- Added support for `verbose=False` in the `create` method for AC, DC, ST, OD.
- Added support for `verbose=False` in the `stylize` method for ST.
Fixes #2677
> Added support for verbose=False to C++ based Deep Learning toolkits.

- src/python/turicreate/test/test_object_detector.py
- src/toolkits/object_detection/object_detector.cpp
- src/toolkits/object_detection/object_detector.hpp
- src/toolkits/object_detection/od_data_iterator.cpp
- src/toolkits/object_detection/od_data_iterator.hpp
> warning when user-defined 'classes' contains labels not in the training data.

- userguide/one_shot_object_detection/README.md
> Fixed typo in OSOD userguide

- src/python/turicreate/toolkits/_model.py
> Fixes break on loading OSOD 

- src/python/turicreate/data_structures/sarray.py
- src/python/turicreate/test/test_sarray.py
This PR resolves #1885 
Feature request: abs()
> Add abs SArray method

- src/python/turicreate/data_structures/sframe.py
- src/python/turicreate/test/test_sframe.py
This PR resolves #2540 
Removing duplicates based on a subset of columns
> Removing duplicates based on a subset of columns

- .gitlab-ci.yml
- scripts/Dockerfile-Ubuntu-18.04
- scripts/get_docker_image.sh
- scripts/make_documentation.sh
- scripts/make_wheel.sh
- Remove documentation building from make_wheel.sh
- Create standalone script to make documentation
- Creaet standalone GitLab job
Fixes #284
> Auto generate all documentations

- .travis.yml
- scripts/requirements.txt
> bump up pytest and others

- scripts/requirements.txt
- src/python/setup.py
> Upgrade coremltools version. Unfix numpy version.

- src/python/turicreate/test/test_activity_classifier.py
- src/python/turicreate/test/test_drawing_classifier.py
- src/python/turicreate/test/test_image_classifier.py
- src/python/turicreate/test/test_image_similarity.py
- src/python/turicreate/test/test_object_detector.py
- src/python/turicreate/test/test_one_shot_object_detector.py
- src/python/turicreate/test/test_recommender.py
- src/python/turicreate/test/test_sarray.py
- src/python/turicreate/test/test_sframe.py
- src/python/turicreate/test/test_style_transfer.py
- src/python/turicreate/test/test_text_classifier.py
> Unit tests clean up temp files

- src/python/turicreate/_scripts/_pylambda_worker.py
- src/python/turicreate/toolkits/_data_zoo.py
- src/python/turicreate/toolkits/_internal_utils.py
- src/python/turicreate/toolkits/activity_classifier/_activity_classifier.py
- src/python/turicreate/toolkits/classifier/boosted_trees_classifier.py
- src/python/turicreate/toolkits/classifier/random_forest_classifier.py
- src/python/turicreate/toolkits/drawing_classifier/_tf_drawing_classifier.py
- src/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py
- src/python/turicreate/toolkits/image_classifier/_evaluation.py
- src/python/turicreate/toolkits/image_classifier/image_classifier.py
- src/python/turicreate/toolkits/image_similarity/image_similarity.py
- src/python/turicreate/toolkits/object_detector/_sframe_loader.py
- src/python/turicreate/toolkits/object_detector/object_detector.py
- src/python/turicreate/toolkits/one_shot_object_detector/one_shot_object_detector.py
- src/python/turicreate/toolkits/regression/_regression.py
- src/python/turicreate/toolkits/regression/boosted_trees_regression.py
- src/python/turicreate/toolkits/regression/decision_tree_regression.py
- src/python/turicreate/toolkits/regression/random_forest_regression.py
- src/python/turicreate/toolkits/style_transfer/_sframe_loader.py
- src/python/turicreate/toolkits/style_transfer/style_transfer.py
- src/python/turicreate/util/lambda_closure_capture.py
* Remove unused imports
* Remove unused variables
* Fix some code that will error, if it's ever executed
> Post Release Fixes

- userguide/sound_classifier/advanced-usage.md
- userguide/sound_classifier/how-it-works.md
Fix typos in Sound Classifier user guide + correct link to VGGish repo.
> Fix typos in Sound Classifier user guide

- src/python/turicreate/toolkits/sound_classifier/_audio_feature_extractor.py
- src/python/turicreate/toolkits/sound_classifier/_tf_sound_classifier.py
- src/python/turicreate/toolkits/sound_classifier/sound_classifier.py
This addresses the Sounds Classifier's part of #2928
> Sound classifier works with TF V2 behavior enabled

- src/python/turicreate/toolkits/drawing_classifier/_tf_drawing_classifier.py
Rather than initialize TensorFlow variables to zero then assign the correct values,
variables must be initialized to the correct values at the beginning.
> Drawing Classifer Compatible with TensorFlow V2 Behavior

- src/python/turicreate/test/test_object_detector.py
Still tests the functionality, but uses a much smaller dataset.
> Changed test to be far less intensive.

- src/python/turicreate/data_structures/sframe.py
- src/python/turicreate/test/test_activity_classifier.py
- src/python/turicreate/test/test_drawing_classifier.py
- src/python/turicreate/test/test_image_similarity.py
- src/python/turicreate/test/test_object_detector.py
- src/python/turicreate/test/test_one_shot_object_detector.py
- src/python/turicreate/toolkits/_data_zoo.py
- src/python/turicreate/toolkits/_image_feature_extractor.py
- src/python/turicreate/toolkits/_internal_utils.py
- src/python/turicreate/toolkits/_model.py
- src/python/turicreate/toolkits/_tf_utils.py
- src/python/turicreate/toolkits/_tree_model_mixin.py
- src/python/turicreate/toolkits/activity_classifier/_activity_classifier.py
- src/python/turicreate/toolkits/activity_classifier/_tf_model_architecture.py
- src/python/turicreate/toolkits/classifier/logistic_classifier.py
- src/python/turicreate/toolkits/classifier/svm_classifier.py
- src/python/turicreate/toolkits/drawing_classifier/_tf_drawing_classifier.py
- src/python/turicreate/toolkits/image_classifier/image_classifier.py
- src/python/turicreate/toolkits/object_detector/object_detector.py
- src/python/turicreate/toolkits/one_shot_object_detector/one_shot_object_detector.py
- src/python/turicreate/toolkits/regression/boosted_trees_regression.py
- src/python/turicreate/toolkits/regression/linear_regression.py
- src/python/turicreate/toolkits/regression/random_forest_regression.py
- src/python/turicreate/toolkits/sound_classifier/_tf_sound_classifier.py
- src/python/turicreate/toolkits/style_transfer/_tf_model_architecture.py
- src/python/turicreate/toolkits/text_classifier/_text_classifier.py
Let's enforce the python style check before the build. People like freestyle even though I provide hooks for them to use. I'd better provide a defensive way to remind people using black style.
> enforce python style check

- src/python/turicreate/toolkits/audio_analysis/audio_analysis.py
- src/python/turicreate/toolkits/image_analysis/image_analysis.py
> Use make URLs internal for load_audio and load_images

- src/toolkits/image_deep_feature_extractor/CMakeLists.txt
- src/toolkits/image_deep_feature_extractor/mlmodel_image_feature_extractor.mm
> Use eGPU if available for CoreML models in image feature extraction

- src/core/storage/fileio/s3_api.cpp
- test/fileio/CMakeLists.txt
- test/fileio/sanitize_url_test.cxx
sub-task of #2920.
modify the parse_s3url to reject the invalid domain name so sanitze_aggressive can do further work.
> put back the s3 url sanitize test

- src/python/turicreate/data_structures/sframe.py
- userguide/sframe/sframe-intro.md
> User guide and API docs: clarify what S in SFrame means

- src/python/setup.py
Temporary workaround for #3003
> Pin TensorFlow version on Linux

- src/python/setup.py
> Revert "Pin TensorFlow version on Linux"

- src/python/turicreate/data_structures/sframe.py
- src/python/turicreate/toolkits/activity_classifier/util.py
* Clarify error
* Remove dead code
> Minor Changes

- src/python/turicreate/test/test_recommender.py
- src/python/turicreate/toolkits/recommender/util.py
> Basic parameter checking in tc.recommender.util.compare_models

- scripts/requirements.txt
- src/python/turicreate/test/test_json.py
Fixes #2934
I don't think this test provides much value. Given all of the know issues with this test, I think it's best to just remove it.
> Remove buggy json test

- src/python/turicreate/test/test_image_classifier.py
> Fix Image Classifier Unit Test

- src/python/turicreate/test/test_prototype_models.py
suppress error if the file is deleted before manual clean up.
> fix test error

- src/ml/neural_net/tf_compute_context.cpp
- src/python/turicreate/test/test_object_detector.py
- src/python/turicreate/toolkits/object_detector/_tf_image_augmenter.py
- src/python/turicreate/toolkits/object_detector/object_detector.py
- src/toolkits/object_detection/object_detector.cpp
- src/toolkits/object_detection/object_detector.hpp
- src/toolkits/object_detection/od_darknet_yolo_model_trainer.cpp
- src/toolkits/object_detection/od_darknet_yolo_model_trainer.hpp
- src/toolkits/object_detection/od_model_trainer.hpp
- test/unity/toolkits/object_detection/test_object_detector.cxx
- Plumb random seed parameter from Python to data augmentation
- Plumb random seed from C++ into TensorFlow image augmenter
Incorporates some changes originally authored by Henry Tao (jakesabathia2)
Fixes #2168
> Add random_seed parameter to object_detector

- src/core/storage/fileio/s3_api.cpp
I have to admit I overlooked this one.
> support  TURI_FILEIO_ALTERNATIVE_SSL_CERT_FILE;

- src/core/storage/fileio/fs_utils.cpp
> check on parent dir instead

- src/core/storage/sframe_interface/unity_sframe.cpp
- src/python/turicreate/test/test_io_s3.py
> prevent from reading null

- src/ml/neural_net/model_spec.cpp
- src/ml/neural_net/model_spec.hpp
- src/ml/neural_net/style_transfer/mps_style_transfer_utils.h
- src/ml/neural_net/style_transfer/mps_style_transfer_utils.m
Plus some useful utilies for style transfer experimentation
> Updates to model_spec

- userguide/install.md
removed a '`' for the markdown to parse correctlyt
> typo which results in bad formatting.

- src/ml/neural_net/mps_graph_trainer.mm
> fix build on 10.14

- src/python/turicreate/toolkits/object_detector/_tf_image_augmenter.py
* Fix TensorFlow object detector evaluate always returning zero accuracy #3148
* Fix TensorFlow object detector not working for more than two objects/classes #3031
> Two Critical TensorFlow Object Detector Fixes

- scripts/install_python_toolchain.sh
- scripts/requirements-minimal.txt
- scripts/requirements.txt
- scripts/test_wheel.sh
> split minimal requirements out

- .gitlab-ci.yml
Thanks for the help from @znation!
> update docker from 18 to 19.

- src/python/turicreate/test/test_io_s3.py
> disable s3 upload test for SFrame

- src/python/turicreate/toolkits/object_detector/_tf_image_augmenter.py
- src/python/turicreate/toolkits/object_detector/_tf_model_architecture.py
The object detection part of #2928 
Also some code clean ups.
> Object detection with TensorFlow V2 functionality

- src/python/turicreate/toolkits/sound_classifier/sound_classifier.py
> Sound Classifier: shuffle data before training

- src/python/turicreate/config/__init__.py
> Clarify tc.config.set_num_gpus as much as possible without breaking API

- README.md
> Update GPU section of README

- src/python/turicreate/test/test_activity_classifier.py
- src/python/turicreate/toolkits/_tf_utils.py
- src/python/turicreate/toolkits/activity_classifier/_tf_model_architecture.py
> Activity Classifier use non-deprecated APIs

- src/python/turicreate/toolkits/_tf_utils.py
- src/python/turicreate/toolkits/activity_classifier/_tf_model_architecture.py
- src/python/turicreate/toolkits/drawing_classifier/_tf_drawing_classifier.py
- src/python/turicreate/toolkits/object_detector/_tf_image_augmenter.py
- src/python/turicreate/toolkits/object_detector/_tf_model_architecture.py
- src/python/turicreate/toolkits/sound_classifier/_audio_feature_extractor.py
- src/python/turicreate/toolkits/sound_classifier/_tf_sound_classifier.py
- src/python/turicreate/toolkits/style_transfer/_tf_model_architecture.py
> Stop Disabling TensorFlow V2 Behavior

- CMakeLists.txt
- cmake/SetupCompiler.cmake
- src/ml/neural_net/CMakeLists.txt
- src/ml/neural_net/TCMLComputeObjectDetectorDescriptor.h
- src/ml/neural_net/TCMLComputeObjectDetectorDescriptor.m
- src/ml/neural_net/TCMLComputeUtil.h
- src/ml/neural_net/TCMLComputeUtil.m
- src/ml/neural_net/TCModelTrainerBackendGraphs.h
- src/ml/neural_net/TCModelTrainerBackendGraphs.m
- src/ml/neural_net/compute_context.cpp
- src/ml/neural_net/compute_context.hpp
- src/ml/neural_net/mlc_compute_context.hpp
- src/ml/neural_net/mlc_compute_context.mm
- src/ml/neural_net/mlc_layer_weights.hpp
- src/ml/neural_net/mlc_layer_weights.mm
- src/ml/neural_net/mlc_od_backend.hpp
- src/ml/neural_net/mlc_od_backend.mm
- src/ml/neural_net/mlc_utils.hpp
- src/ml/neural_net/mlc_utils.mm
- src/ml/neural_net/mps_compute_context.hpp
- src/ml/neural_net/mps_compute_context.mm
- src/ml/neural_net/tf_compute_context.cpp
- src/toolkits/object_detection/object_detector.cpp
Merge after https://github.com/apple/turicreate/pull/3266
> Adding MLCompute as a training backend for OD 

- .gitlab-ci.yml
- README.md
- scripts/Dockerfile-CentOS-6
- scripts/Dockerfile-Ubuntu-18.04
- scripts/create_docker_images.sh
- scripts/get_docker_image.sh
- scripts/install_python_toolchain.sh
- scripts/make_documentation.sh
- scripts/make_wheel.sh
- scripts/requirements-minimal.txt
- scripts/requirements.txt
- scripts/test_wheel.sh
- src/python/setup.py
- src/python/turicreate/_cython/cy_variant.pyx
- src/python/turicreate/extensions.py
- src/python/turicreate/test/test_activity_classifier.py
- src/python/turicreate/test/test_audio_functionality.py
- src/python/turicreate/test/test_coreml_export.py
- src/python/turicreate/test/test_drawing_classifier.py
- src/python/turicreate/test/test_image_classifier.py
- src/python/turicreate/test/test_image_similarity.py
- src/python/turicreate/test/test_object_detector.py
- src/python/turicreate/test/test_one_shot_object_detector.py
- src/python/turicreate/test/test_recommender.py
- src/python/turicreate/test/test_style_transfer.py
- src/python/turicreate/test/test_svm_classifier.py
- src/python/turicreate/test/test_text_classifier.py
- src/python/turicreate/util/lambda_closure_capture.py
- src/unsupported_python/setup.py
> Python 3.8 Support

- src/python/turicreate/test/test_drawing_classifier.py
- src/toolkits/drawing_classifier/dc_data_iterator.cpp
- src/toolkits/drawing_classifier/drawing_classifier.cpp
> Drawing Classifier: resize input images

- src/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py
> Delete unused code

- scripts/make_wheel.sh
> Fix Version Info Values

- scripts/requirements.txt
- src/python/turicreate/toolkits/recommender/factorization_recommender.py
> Bug fix: tilda in export path

- src/python/turicreate/test/test_evaluation.py
- src/toolkits/evaluation/evaluation_interface-inl.hpp
> Decrease ROC Memory Usage

- src/python/doc/source/turicreate.utils.rst
- src/python/turicreate/config/__init__.py
- src/python/turicreate/test/test_boosted_trees.py
- src/python/turicreate/toolkits/classifier/boosted_trees_classifier.py
> More Doc Updates

- src/python/turicreate/toolkits/text_classifier/_text_classifier.py
- userguide/text_classifier/README.md
> Text Classifier Documentation Update

- src/visualization/client/CMakeLists.txt
> Fix CEF URL

- src/toolkits/drawing_classifier/drawing_classifier.cpp
update configuration file to support cmake 3.20.0
It is not possible for me to validate if this change works on all versions of cmake used by this project.
Please reject this PR if the change breaks other builds.d
Is there a development branch I could submit pull requests into?
> update configuration 
