apple/turicreate

- README.md
As long as `coremltools==0.6.3` is a hard dependency, we do not support macOS 10.11. This PR updates the README.
I opened up an issue to track macOS 10.11 support: #23
> Updated macOS supported versions in README

- src/unity/python/turicreate/cython/cy_flexible_type.pyx
- src/unity/python/turicreate/test/test_activity_classifier.py
- src/unity/python/turicreate/test/test_python_decision_tree.py
- src/unity/python/turicreate/toolkits/activity_classifier/_activity_classifier.py
(cherry picked from commit b3ddc2f)
There were a few instances of duplicate key/value pairs and this PR removes them.
> Remove duplicate dictionary key/value pairs

- src/unity/toolkits/activity_classification/sequence_iterator.cpp
In the sequence_iterator's prep_data() function, we've only counted the last session of each dataset
if it wasn't divisible by chunk_len.
This could theoretically lead to setting num_gpus (which depends on the number of sessions) incorrectly, and even zero.
I've fixed it so the last session is always counted.
> [AC] Bugfix - the last session was sometimes not counted

- src/unity/python/turicreate/_sys_util.py
The value `MXNET_CPU_WORKER_NTHREADS` should be automatically set to no more than 2, so as not to cause potential OpenBLAS memory issues. However, right now there are two bugs preventing this to work correctly:
- Should use `min` to set an upper bound.
- Should compare `int` and `int` (intead of `int` and `str`). This is also a fatal error in Python 3.
> Fix MXNET_CPU_WORKER_NTHREADS upper bound bug

- src/unity/python/turicreate/test/test_graph.py
Updates pandas DataFrame to use `sort_values` instead of `sort`. I tested the `test_graph.py` where this is used on two versions of pandas before and after this PR:
Before:
0.19.0  - PASSED (but with deprecation warnings)
0.21.0 - FAILED (`sort` removed)
After:
0.19.0 - PASSED
0.21.0 - PASSED
> DataFrame.sort -> sort_values (fix deprecation)

- src/unity/python/turicreate/test/test_image_classifier.py
- src/unity/python/turicreate/toolkits/_supervised_learning.py
- src/unity/python/turicreate/toolkits/classifier/logistic_classifier.py
- src/unity/python/turicreate/toolkits/image_classifier/image_classifier.py
The unit test `ImageClassifierTest::test_export_coreml_with_predict` failed with high probability. To address this, this PR increases the test tolerance and makes model creation optionally deterministic by exposing a seed parameter.
I changed the tolerance from 0.005 to the much higher 0.02. This is after running 25 trials and collecting some statistics. Only 3 times was it below 0.005 and the highest was around 0.015.
Note however that even though this tolerance seems awfully high, separate tests indicate that the error is many orders of magnitude smaller when the network is fed natural images (instead of randomly generated input as in this unit test).
> Introduce seed in image classifier and stabilize unit test

- src/unity/python/turicreate/util/cloudpickle.py
It looks like compiled Python code (and the handling thereof) changed a bit in Python 3.4. This PR updates the `cloudpickle.py` with better Python 3.4+ support by taking the latest version from: https://github.com/apache/spark/blob/master/python/pyspark/cloudpickle.py
Earlier modifications of cloudpickle have been incorporated into this new version (plugins, avoidance of transients, make sure futurize is satisfied). This passes all tests on Python 2 (confirmed on macOS 10.13 and Ubuntu 16.04).
Following is a diff between the reference file and the file in this PR, for easier understanding of what was re-incorporated:
```diff
@@ -1,3 +1,8 @@
+# -*- coding: utf-8 -*-
+# Copyright © 2017 Apple Inc. All rights reserved.
+#
+# Use of this source code is governed by a BSD-3-clause license that …
```
> Update cloudpickle.py for Python 3.4+ support

- src/unity/python/turicreate/toolkits/recommender/factorization_recommender.py
- src/unity/python/turicreate/toolkits/recommender/ranking_factorization_recommender.py
- src/unity/python/turicreate/toolkits/text_analytics/_util.py
There were three missing double quotes which this PR fixes.
I also replaced two single quotes with double-quotes for readability.
> [When a string contains single or double quote characters, however, use the other one to avoid backslashes in the string. It improves readability.](http://pep8.org/#string-quotes)
> Doctest quote characters

- src/unity/python/turicreate/test/test_nearest_neighbors.py
- src/unity/python/turicreate/util/config.py
Fix #38 
I found two more instances of raising strings (other than the two fixed by this PR) but they are both under `deps` so I was hesitant to touch them.
> Raise `RuntimeError` instead of bare strings

- src/unity/python/turicreate/extensions.py
- src/unity/python/turicreate/test/test_activity_classifier.py
- src/unity/python/turicreate/test/test_logistic_classifier.py
- src/unity/python/turicreate/toolkits/_feature_engineering/_internal_utils.py
- src/unity/python/turicreate/toolkits/_image_feature_extractor.py
- src/unity/python/turicreate/toolkits/_model.py
- src/unity/python/turicreate/toolkits/_mxnet_utils.py
- src/unity/python/turicreate/toolkits/_pre_trained_models.py
- src/unity/python/turicreate/toolkits/activity_classifier/_activity_classifier.py
- src/unity/python/turicreate/toolkits/object_detector/_sframe_loader.py
- src/unity/python/turicreate/toolkits/object_detector/object_detector.py
- src/unity/python/turicreate/util/file_util.py
A round of Python 3 fixes.
All tests still passing on Python 2.7 (tested on macOS 10.13 and Ubuntu 16.04).
> Miscellaneous Python 3 fixes

- README.md
Following discussion in https://github.com/apple/turicreate/pull/54, I updated that readme that user may use any `virtualenv` and `pip` installations, including `conda` ones. 
This is also to further clarify that the user doesn't have to user the "system" pip per-se.
> Update README.md - user may use conda venv

- src/fileio/get_s3_endpoint.cpp
- src/fileio/get_s3_endpoint.hpp
- src/fileio/s3_api.cpp
S3 Regions are not set in the S3 client. We need to set it to support
anything outside of us-east-1.
> Fix S3 Region

- userguide/object_detection/advanced-usage.md
Currently, the guide on using the object detection MLModel in Swift simply uses the variable `coordinates` and `confidence` without explaining how to retrieve them from the VNCoreMLRequest.
I added three lines of code to give a hint.
The force cast may not be best practice but everything else would be overkill for this guide in my opinion.
> Add context on how to retrieve MulitArrays

- src/unity/python/turicreate/test/test_sframe_sequence_iterator.py
The current unit test for the AC's sequence iterator only covered the `prep_data` step, and only a few of the possible edge cases.
I've re-designed the unit test to:
1. Cover more edge cases in the data preparation step
2. Test the outputs of the iterator's `next()` method - there are several non trivial conversions in the process.
> Improving the Activity Classifier's unit testing

- configure
It's quite a common situation that the python installation fails in `./configure` (often due to local experimental changes, but sometimes due to external issues). Right now, if this happens `./configure` returns 0 (no error) and the errors are not immediately visible since there is so much printed after them. As a result, I proceed with `make` and I discover that I have a broken python installation much later (usually around 97% build progress).
I keep adding this flag locally, so I think this will be useful for everyone.
> Add `set -e` to configure to make it fail early

- src/unity/python/turicreate/test/test_activity_classifier.py
- src/unity/python/turicreate/toolkits/_internal_utils.py
- src/unity/python/turicreate/toolkits/activity_classifier/_activity_classifier.py
- src/unity/python/turicreate/toolkits/image_classifier/image_classifier.py
- src/unity/python/turicreate/toolkits/image_similarity/image_similarity.py
- src/unity/python/turicreate/toolkits/object_detector/object_detector.py
This PR updates the activity classifier (AC) save/load to work with more versions of mxnet. There are still some issues with export to Core ML for newer versions of mxnet, so this PR alone does not expand support yet (#17).
The issue with the AC is that it saves and loads the network graph using mxnet json files. MXNet is pretty good at backward compatibility, but not forward compatibility. If we support more than one version of mxnet at a time, this creates a problem for us where we can't even be same-version compatible:
1. User 1 (turicreate==4.0.0 and mxnet==0.12.1) saves a model.
2. User 2 (turicreate==4.0.0 and mxnet==0.11.0) loads the model.
This won't work due to forward incompatibility in mxnet. The solution is to avoid saving and loading the graph and simply building it up and …
> Improve mxnet support for activity classifier save/load

- LINUX_INSTALL.md
On CentOS 6, when compiling from source your should `./configure --enable-shared ...` to create shared objects (`.so` files) required by unity.
Also, included instructions for checking ucs2/ucs4 from StackOverflow: https://stackoverflow.com/a/1446456/2064085
> On CentOS 6, compile Python with --enable-shared

- userguide/image_classifier/advanced-usage.md
The link for the GPU support in the main readme was not pointing to the relevant section.
> Fix link to the GPU support section in the user guide

- userguide/activity_classifier/advanced-usage.md
- userguide/activity_classifier/data-preperation.md
- userguide/activity_classifier/introduction.md
Added code to the userguide to prepare the raw HAPT data into an SFrame format expected by the activity classifier.
The walking_3_sec example in introduction.md is now more robust as the performance of the predictions is better when not looking at the beginning of a session due to transitions from a different activity.
In reference to issues https://github.com/apple/turicreate/issues/41 and https://github.com/apple/turicreate/issues/59.
> Add data preparation code to AC UG

- src/unity/python/turicreate/test/test_boosted_trees.py
- src/unity/toolkits/supervised_learning/xgboost.cpp
This change will utilise already existing code in /src/external/xgboost/src/tree/model.h (e.g lines 509-512) and expose the Gain and Cover metrics in the model json.
> Generate Gain and Cover For xgboost models

- src/unity/python/turicreate/data_structures/sarray.py
- src/unity/python/turicreate/data_structures/sframe.py
@TobyRoseman @ylow Please review, thanks!
I didn't add unit tests because the actual code is only a one-liner (it calls into SFrame stack):
```python
return _SFrame({'SArray': self}).stack('SArray',
new_column_name=new_column_name,
drop_na=drop_na,
new_column_type=new_column_type)
```
> Implement SArray.stack

- src/unity/lib/visualization/item_frequency.cpp
This would only repro on an SArray with categorical values with at least
one category that has the same count as the (hidden) "undefined" category.
Even though this doesn't repro on many real datasets, the minimal repro is:
```python
sa = tc.SArray(['x', None])
sa.show()
```
Despite ignoring undefined values lower down in this function, the
item_frequency.cpp vega_column_data function attempts to sort all
keys/values for item frequency. If there is a null key with the same
count as another value, it sorts by key, and then throws when comparing
undefined with a string value.
> Fix SArray.show with undefined categorical

- src/unity/python/setup.py
- src/unity/python/turicreate/__init__.py
- src/unity/python/turicreate/toolkits/_mxnet_to_coreml/_layers.py
- src/unity/python/turicreate/toolkits/_mxnet_utils.py
With this PR, we have support for pretty much all versions of MXNet from 0.11.
I updated the support in `setup.py` to `mxnet >= 0.11, mxnet < 1.0.0`. This PR makes 1.0.0 theoretically work, but that version causes a segfault in the object detector. This segfault seems to be fixed in every subsequent nightly release, so hopefully it will not be an issue in 1.0.1. When that version is released, we can extend official support for 1.X and remove or update the `mxnet < 1.0.0`.
> Add official support for MXNet 0.12 and unofficial support for MXNet 1.X

- src/unity/python/turicreate/test/test_activity_classifier.py
The `labels` is a generator in Python 3 and gets consumed first time its used, leaving `coreml_time1_values` an empty list.
> Python 3 fix in AC unit test

- src/unity/python/turicreate/cython/cy_unity.pyx
- src/unity/python/turicreate/cython/cy_variant.pxd
- src/unity/python/turicreate/cython/cy_variant.pyx
- src/unity/python/turicreate/toolkits/_model.py
This is an alternative to #110. This PR decodes the model state to unicode strings in Python 3 in the Cython bridge instead of as an afterthought from Python.
However, legacy models need to be decoded and unpickled using the old method, so this PR first peeks at the `archive_version` and then uses old behavior if it's 0 and new behavior if it's 1. Note, `disable_cpp_str_decode()` doesn't change anything in Python 2, however it is important in Python 3 so that we don't get a decode error when reading legacy models. This PR doesn't actually offer support of loading legacy models in Python 3 (this is hard since it involves unpickling Python 2), but it does offer a more user-friendly error message. This is why it's important to avoid the decoding error happening. An alternative to peeking at …
> Fixes model loading in Python 3

- src/unity/python/turicreate/data_structures/sarray.py
- src/unity/python/turicreate/test/test_sarray.py
SArray.value_counts() mimics pandas's Series.value_counts() method.
It returns an SFrame containing the counts of unique values in the
SArray.
Example:
```
>>> sa = turicreate.SArray([1,1,2,2,2,2,3,3,3,3,3,3,3])
>>> sa.value_counts()
Columns:
value	int
count	int
Rows: 3
Data:
+-------+-------+
| value | count |
+-------+-------+
|   3   |   7   |
|   2   |   4   |
|   1   |   2   |
+-------+-------+
[3 rows x 2 columns]
```
> Implemented SArray.value_counts()

- src/flexible_type/flexible_type.hpp
The get by reference methods did not check exact type for int and float
cases, which allowed a reference to a double to be returned as a
reference to an int and vice versa. This PR removes this looseness.
> Removed looseness in flexible_type get.

- test/unity/toolkits/sparse_similarity/test_brute_force_all_pairs.cxx
Turns out that the the TS_ASSERT_* macros are not threadsafe on linux (due to the underlying boost calls not being threadsafe).  This causes sporadic failures in some C++ tests.  The immediate workaround is to replace all these statements by builtin ASSERT statements, which raise an exception.
> Fix for not thread safe TS_ASSERT in parallel block.

- src/unity/python/turicreate/data_structures/sframe.py
- src/unity/python/turicreate/util/__init__.py
It's gone from the API; looks like setting env variables is the only way
to set AWS credentials.
> Remove set_credentials from API docs

- src/sframe/csv_writer.cpp
- src/unity/python/turicreate/test/test_json.py
- src/unity/python/turicreate/test/test_json_export.py
This fixes the formatting of the `flex_vec` (array) dtype in CSV export
from SFrame.
Still quite a few bugs lurking in the JSON export -- I also tested
inf/nan handling and it's broken. Leaving that commented out in the test
for now. I suspect other things are broken too (namely datetime or Image
types - not sure how to reasonably JSON export those).
We might want to consider extensions._json for JSON export.
> Fix JSON export of array dtype

- src/unity/lib/visualization/CMakeLists.txt
Include missing dependency `process` in the list of dependencies for the
visualization library.
Fixes test build break introduced in #179.
> Fix C++ unit test build

- src/flexible_type/flexible_type.hpp
- src/platform/user_pagefault/type_heuristic_encode.cpp
- src/sframe/sarray_v2_type_encoding.cpp
- src/sframe/sarray_v2_type_encoding.hpp
Adds 2 new methods to flexible_type
reinterpret_get<T>
reinterpret_mutable_get<T>
These two functions behave identically to get<T> and mutable_get<T> but
bypasses type checking. They are used in limited situations where it is
useful to reinterpret between integer and floating points types and to
make it clear when this is happening.
This also fixes the test failures introduced in #177
> Make explicit unsafe use of flexible_type

- src/fileio/dmlcio/s3_filesys.cc
- src/fileio/set_curl_options.cpp
- test/fileio/fs.cpp
Under some conditions S3 access on Linux does not work. This turns out to be caused by incorrect curl options resulting in CURLE_SSL_CACERT_BADFILE. Added checks to mitigate this.
> Fix S3 Certificate Issues on Linux

- src/util/test_macros.hpp
- test/flexible_type/flexible_datatype.cxx
- test/nanosockets/reqreptest.cxx
- test/parallel/atomic_ops.cxx
- test/shmipc/shmipc_test.cxx
- test/unity/toolkits/feature_engineering/random_projection_test.cxx
- test/unity/unity_sframe.cxx
- test/unity/unity_sgraph.cxx
An annoying side effect is that TS_ASSERTS are now *really* slow.
In particular for some tests that loop TS_ASSERTS millions of times,
this will degrade test performance significantly. Those tests may have
to change from:
TS_ASSERT(something);
to
if (something) {
TS_ASSERT(something);
}
It will also be problematic if TS_ASSERT blocks, in particular, in
tests of threading primitives. For instance this is not a good idea.
TS_ASSERT(wait_for_thread());
instead:
int ret = wait_for_thread();
TS_ASSERT(ret);
> Fix TS_ASSERTS to be threadsafe

- README.md
Some links in the README.md file were dead since the name of the files they were pointing to had changed.
> Fix README.md dead links

- src/unity/python/turicreate/toolkits/_internal_utils.py
Python 2 allows comparisons like `None >= (10, 13)`, which will occur for instance here:
https://github.com/apple/turicreate/blob/80e4094da5d044b0904114825869ef672f6aeb25/src/unity/python/turicreate/test/test_object_detector.py#L261
This kind of comparison is not allowed in Python 3, so the `None` is replaced with an empty tuple `()`.
> Fix Mac version check on Linux running Python 3

- src/unity/python/README.rst
The platforms are already mentioned and as the typo (10.11+ should be 10.12+) proves this is just
a more stuff to keep synchronized. This copies what the main README does, which is to not repeat the platforms since they were just listed above.
> Remove redundant line (that has typo in it)

- src/unity/python/turicreate/test/test_sentence_classifier.py
- src/unity/python/turicreate/toolkits/sentence_classifier/_sentence_classifier.py
Previously the sentence classifier would ignore ```validation_set=None``` and default to creating a validation set.
The behavior is now also more consistent with other toolkits.
> Fix validation set options for the sentence classifier

- src/unity/toolkits/coreml_export/xgboost_exporter.cpp
It turns out an fscanf statement unpacking a hex representation of float values in the export_to_coreml file ends up overrunning a local variable.  This fixes that behavior.
> Fixing overrun of variable in tree exporter.

- src/external/protobuf/CMakeLists.txt
- src/external/sparsehash/CMakeLists.txt
It turned out that when Turi Create tried to link against a library that
included another version of one of the external libraries, the symbols
would get clobbered in some of the C++ tests, causing failures.  This
change isolates the local libraries in question.
> Added translation macros of google namespace.

- userguide/supervised-learning/linear-regression.md
- userguide/supervised-learning/logistic-regression.md
Corrected "chose" to "choose" in userguide.
> Typographical errors in userguide

- BUILD.md
- src/visualization/CMakeLists.txt
* Update BUILD.md to accurately describe pre-existing dependencies vs.
supplied dependencies.
* Error out in CMakeLists.txt if npm is missing, and
TC_BUILD_VISUALIZATION_CLIENT is enabled.
> Note nodejs/npm as a build dependency on macOS

- src/flexible_type/flexible_type_converter.hpp
flexible_type.get<T>() only fails on debug mode on a type mismatch. We need to explicitly check it here.
> Raise an error on Type Mismatch in Flexible Type Converter

- src/unity/python/turicreate/test/test_json_export.py
- src/unity/python/turicreate/toolkits/image_classifier/image_classifier.py
* `sys.maxint` appears to be gone; we really just need a range of ints
here, so hardcoding a range in test_json_export.
* MergeFromString() from protobuf always takes bytes. Adding `b` prefix
to string literals in a few uses that were passing `''`.
> Fix some unit tests in Python 3

- src/unity/python/turicreate/test/test_topic_model.py
- src/unity/toolkits/text/perplexity.cpp
Topic Model perplexity computation may give different results depending
on the ordering of the input data. We fix it by enforcing the
vocabulary ordering.
> Fix Perplexity Bug

- build.sh
- configure
- gitlab_scripts/test_python.sh
- scenario-tests/additional_requirements.txt
- scenario-tests/common/base.py
- scenario-tests/common/mirror_retrieve.py
- scenario-tests/driver.py
- scenario-tests/run_scenario_tests.sh
- scenario-tests/tests/engine/test_lambda.py
- scenario-tests/tests/setup_reporter.py
- scenario-tests/tests/single_test_driver.py
- scripts/install_python_toolchain.sh
- scripts/make_wheel.sh
- scripts/requirements.txt
- src/unity/lib/version_number.hpp
- src/unity/python/dummy.c
- src/unity/python/setup.py
- src/unity/python/turicreate/test/test_topic_model.py
- src/unity/python/turicreate/version_info.py
* Remove unused spacy dependency in scenario tests
* Bump coremltools dependency to 0.8
* Use assertAlmostEqual to get better failure msg in test_perplexity
* Get scenario tests ready for Python 3 execution
* Expect wheels on Linux for scenario and unit tests
* Make wheels on Linux
* Rename make_egg -> make_wheel
* Bump version number to 4.1a1
* Use VIRTUALENV env variable in run_scenario_tests
> Build + test fixes to prepare for 4.1 release

- src/unity/python/turicreate/cython/cy_dataframe.pyx
- src/unity/python/turicreate/data_structures/sarray.py
- src/unity/python/turicreate/data_structures/sframe.py
- src/unity/python/turicreate/test/test_unicode_strings.py
* Assumes utf-8 everywhere (Python 3 already makes this assumption).
* Allow unicode column accessors in SFrame.
* Allow unicode column name in construction of SFrame.
* Allow unicode column_name_prefix in str_to_datetime and unpack.
Fixes #157
> Fix some Unicode string cases in Python 2

- src/unity/python/MANIFEST.in
- src/unity/python/setup.py
Right now, the README.rst does not show up on PyPI. This is addressed in
two ways (not sure if both are necessary, but it seems to be common
practice to do both):
- Add to manifest file
- Add to `long_description` in setup.py
> Make sure distributions contain README.rst

- README.md
... instead of minimum supported. As defined by:
https://github.com/apple/turicreate/blob/7f379e2c74b94429dd578581ef3aee353d7b9e84/src/unity/python/turicreate/__init__.py#L133-L135
> Update instructions to reflect currently recommended mxnet version

- src/flexible_type/ndarray.hpp
According to http://en.cppreference.com/w/cpp/language/static_assert the message can only be omitted starting from c++17,  so the master branch not compile for me on gcc 5.4 and c++11.
> Fix compilation issue on c++ versions less than 17

- src/unity/python/turicreate/toolkits/object_detector/_sframe_loader.py
This relies on the `resize` function to make these conversions and do the decoding. This
function is really fast when there is no resizing or channel change,
although a bit slower than the previous decoding method in speed tests.
Fixes #114
> Handle RGBA (4 channels) and L (1 channel) images in detector

- src/unity/python/turicreate/test/test_image_classifier.py
- src/unity/python/turicreate/test/test_image_similarity.py
- src/unity/python/turicreate/toolkits/image_classifier/image_classifier.py
- src/unity/python/turicreate/toolkits/image_similarity/image_similarity.py
- src/unity/toolkits/supervised_learning/logistic_regression.cpp
In addition:
* Raise `TypeError` for other input types
* Stop using `xfail` for testing error cases.
* Fix output alignment for logistic regression.
> Image Classifier & Image Similarity: take as input single image or SArray of images

- src/unity/python/setup.py
Then decode utf-8 explicitly. For some reason, otherwise we get:
```
+ VERSION_NUMBER=4.1.1
+ /builds/turi/turicreate-build/scripts/../deps/env/bin/python setup.py
bdist_wheel
Traceback (most recent call last):
File "setup.py", line 127, in <module>
long_description = f.read()
File
"/builds/turi/turicreate-build/scripts/../deps/env/lib/python3.5/encodings/ascii.py",
line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position
106: ordinal not in range(128)
```
> Use binary mode to read README.rst

- src/unity/toolkits/supervised_learning/linear_regression.cpp
- src/unity/toolkits/supervised_learning/linear_regression_opt_interface.cpp
- src/unity/toolkits/supervised_learning/linear_regression_opt_interface.hpp
- src/unity/toolkits/supervised_learning/logistic_regression.cpp
- src/unity/toolkits/supervised_learning/logistic_regression_opt_interface.cpp
- src/unity/toolkits/supervised_learning/logistic_regression_opt_interface.hpp
The models produced by linear regression included the training-set loss and RMSE, but not the validation-set metrics. Perform one more call to compute_second_order_statistics as the end of train() to populate these.
> Add validation-set statistics to resulting model for linear/logistic regression

- src/unity/python/turicreate/toolkits/_mxnet_utils.py
Right now, a Mac with a CUDA card is unnecessarily blocked.
Fixes #260
> Allow CUDA GPU to be used if available

- src/unity/toolkits/supervised_learning/linear_regression.cpp
- src/unity/toolkits/supervised_learning/linear_regression_opt_interface.cpp
- src/unity/toolkits/supervised_learning/linear_regression_opt_interface.hpp
- src/unity/toolkits/supervised_learning/logistic_regression.cpp
- src/unity/toolkits/supervised_learning/logistic_regression_opt_interface.cpp
- src/unity/toolkits/supervised_learning/logistic_regression_opt_interface.hpp
The changes for https://github.com/apple/turicreate/pull/274 were incomplete. They added validation-set fields, but populated them with recomputed training-set stats. The optimizer interface must explicitly support computing validation-set stats.
> Fix validation-set statistics saved to linear/logistic regression models

- LINUX_INSTALL.md
The Ubuntu 14.04 install instructions used outdated dependent package links - those were 404ing. This updates to newer links that don't 404.
> Fix URLs to dependent packages

- src/unity/lib/api/unity_global_interface.hpp
- src/unity/lib/unity_global.cpp
- src/unity/lib/unity_global.hpp
- src/unity/python/turicreate/config/__init__.py
- src/unity/python/turicreate/cython/cy_unity.pxd
- src/unity/python/turicreate/cython/cy_unity.pyx
This makes debugging easier. i.e. We can suggest the following for bug
reports:
```
print tc.config.get_server_log_location() + ".0"
tc.config.set_log_level(1)
```
Then send us the filename printed.
> Allow log level setting from Python

- build.sh
- src/visualization/CMakeLists.txt
* Make sure `find | xargs` in build.sh can handle spaces
* Don't error out on missing dependencies of libcef.so (these don't need
to be satisfied at build time, only at runtime).
> Fix Linux build

- src/unity/lib/visualization/vega_spec.cpp
The "double quote" parameter to escape_string doesn't behave like I
expected it to originally - it actually inserts two quotemarks (rather
than simply using double quotes to surround the string), which
terminates the string and produces invalid JSON. Seems this is intended
to be used for CSV escaping instead.
> Fix .explore on string escaping with double quotes

- src/unity/python/turicreate/test/test_object_detector.py
- src/unity/python/turicreate/toolkits/_internal_utils.py
- src/unity/python/turicreate/toolkits/object_detector/_sframe_loader.py
- src/unity/python/turicreate/toolkits/object_detector/object_detector.py
- src/unity/python/turicreate/toolkits/object_detector/util/_visualization.py
Fixes #87. Object detectors can now take in an annotation column that's just a single dictionary (if its all just 1 objects)
> Single dictionary support for OD.

- src/unity/python/turicreate/cython/cy_flexible_type.pyx
Fixes #323
Instead of printing
``` 
Could not convert python object with type <type 'numpy.ndarray'> to flexible_type.
```
It now prints
```
Could not convert python object with type ndarray('datetime64') to flexible_type.
```
> Improve error message when an ndarray type cannot be converted.

- src/visualization/CMakeLists.txt
- src/visualization/Turi Create Visualization/src/js/webpack.config.js
* Copy over missing .so files so the warnings for those missing
disappear (this also seems to improve rendering perf).
* Run webpack with NODE_ENV=production in order to suppress debug-only
console messages. Also has perf and size benefits.
> Remove some Linux viz debug output

- scripts/install_python_toolchain.sh
The word "python" got duplicated in the use of PYTHON_VERSION in
install_python_toolchain, only in the 3.x case. For Python 2.7, the
explicit assignment below makes it work.
> Fix Python 3.x build

- src/sframe/parallel_csv_parser.cpp
Fixes two issues in the skip_BOM function:
* Should not set failbit on the fstream.
* If it reads 1 or 2 chars (not 3), it should only put back 1 or 2.
> Fix C++ unit test failure

- src/image/png_io.cpp
Some PNG files produce the following error on decode:
IDAT: invalid distance too far back
Cross referencing The libpng manual http://www.libpng.org/pub/png/libpng-manual.txt
we have a one line fix.
This should fix #344
> Fix some PNG decode errors

- scripts/install_python_toolchain.sh
- scripts/make_wheel.sh
Don't rely on PY_MAJOR_VERSION env variable (this is not set
consistently). Instead, we can check the PYTHON_VERSION variable, which
is set by `./configure` before `install_python_toolchain` runs.
> Fix ./configure on Python 2.7

- src/unity/python/turicreate/cython/cy_flexible_type.pyx
- src/unity/python/turicreate/test/test_sarray.py
fixed another deprecation warning in the unit tests too.
> Fix user facing deprecation warning for panda's to_datetime usage

- src/unsupported_python/setup.py
We will use this one for erroring out on unsupported platforms, by
uploading it as an egg (source distribution). If a user's pip install
falls back to the egg (no compatible wheel) they will see this error
message.
* Fixes #27
> Add a setup.py for a source distribution

- src/flexible_type/flexible_type_detail.hpp
- src/unity/lib/unity_sarray.cpp
- src/unity/python/turicreate/data_structures/sarray.py
- src/unity/python/turicreate/test/test_flexible_type.py
- userguide/clustering/kmeans.md
Redirected from unity_sarray to go to flex_int and flex_float and added logic in flexible_type_detail to deal with invalid strings like "2hello", "INFiltrate", etc. Built and tested locally.
> Avoiding default atof behavior for integers and floats

- src/unity/python/turicreate/cython/cy_flexible_type.pyx
This causes `test_sarray.py::SArrayTest::test_ndarray_shape` to fail.
That test also fails for another reason that will be addressed separately.
Fixes #355.
> Fix slicing issue for NDArray inside SArray (Python 3)

- src/unity/extensions/additional_sframe_utilities.cpp
- src/unity/extensions/additional_sframe_utilities.hpp
- src/unity/python/turicreate/data_structures/image.py
- src/unity/python/turicreate/test/test_image_type.py
This partly addresses #380. It does not remove pillow as a dependency (that can be considered separately), but does remove PIL as a means to decode images.
Images are exported into numpy arrays in two flavors:
- In format CHW in floats (for feeding to mxnet)
- in format HWC in unsigned chars (for `pixel_data`)
I have consolidated both these extraction needs in `copy_image_to_memory`.
Also, this is technically a breaking API change. The `pixel_data` used to be able to fall back to returning `array.array` in the case numpy is not installed. I removed this since numpy is a hard dependency of turicreate, so this is only breaking API if used in a non-standard way (by delibrately uninstalling numpy). @znation What do you think? Should I mark this PR as api-breaking? Or, should I extend the …
> Do not use PIL for decoding images for pixel_data

- src/unity/extensions/additional_sframe_utilities.hpp
Not sure if this was broken for anyone else, but I was getting:
```
In file included from /Users/zach/turicreate/src/unity/extensions/additional_sframe_utilities.cpp:15:
/Users/zach/turicreate/src/unity/extensions/additional_sframe_utilities.hpp:15:32: error: unknown type name 'image_type'; did you mean 'turi::image_type'?
void image_load_to_numpy(const image_type& img, size_t outptr_addr,
^~~~~~~~~~
turi::image_type
/Users/zach/turicreate/src/image/image_type.hpp:34:7: note: 'turi::image_type' declared here
class image_type {
^
1 error generated.
```
> Fix build break

- README.md
Point to the rendered user guide (which displays math correctly) instead of the source contents of the repo.
> Update user guide links in README

- src/unity/python/turicreate/test/test_image_type.py
I did not realize that a late change I made in #393 broke the unit test. The change was that grayscale images are shape `(H, W)` and not `(H, W, 1)`.
That puts the total tally of PRs required to fix my original PR at 2 (this + #406), if anyone is counting...
> Fix broken unit test for image bit depth

- README.md
- src/unity/python/setup.py
- src/unity/python/turicreate/__init__.py
After extensive testing (on both macOS and Linux / with and without GPU), I have found no issues with MXNet 1.1.0, so this extends official support.
Note: This does not update the testing version in `scripts/requirements.txt`, which is still at our lowest supported version 0.11.
> Update supported and recommended MXNet versions

- src/unity/python/turicreate/toolkits/_image_feature_extractor.py
MXNet fatally crashes when you give zero batches to a GPU (I really don't know why they chose to make this a fatal error!), so we have to
limit the contexts based on the batch size. I believe OD and AC already do this.
This bug is caught by the recent test `test_single_image` when gpus>=2.
> Fix single-image classifier inference on multi-gpu

- cmake/UseCython.cmake
This will help compatibility of our binary distribution
with Python packages that don't `--enable-shared`.
We shouldn't directly link to libpython2.7 anyway, as per
https://www.python.org/dev/peps/pep-0513/#libpythonx-y-so-1
> Remove unnecessary Python linking

- src/unity/python/turicreate/cython/cy_flexible_type.pyx
For np.ndarray input values which are slices of a base array, the conversion
procedure to flexible_type was using the entire buffer of the base array from
the offset onwards, instead of cropping to the length of the input slice. This
caused quadratic behavior, e.g., in the import of a value list(A), where A is
an np.ndarray of shape (N, 299, 299, 3).
> Fix offset/length bug in NDArray-to-SArray

- src/lambda/graph_pylambda_master.cpp
- src/lambda/lambda_master.cpp
- src/unity/python/turicreate/config/__init__.py
- src/unity/python/turicreate/util/__init__.py
This API moved in 4.0 to within turicreate.config and is no longer
top level. The doc strings and error messages needed to be updated.
> Update get/set runtime config docs and errors

- src/fileio/fs_utils.cpp
- src/fileio/general_fstream_source.cpp
- src/fileio/union_fstream.cpp
- test/fileio/general_fstream_test.cxx
Currently, file:// is not recognized as a valid protocol for opening file urls, even though it's widely available elsewhere.
> Added support for file:// as valid url protocol.

- src/unity/python/turicreate/test/test_image_classifier.py
- src/unity/toolkits/supervised_learning/linear_regression.cpp
- src/unity/toolkits/supervised_learning/linear_regression_opt_interface.cpp
- src/unity/toolkits/supervised_learning/linear_regression_opt_interface.hpp
- src/unity/toolkits/supervised_learning/logistic_regression.cpp
- src/unity/toolkits/supervised_learning/logistic_regression_opt_interface.cpp
- src/unity/toolkits/supervised_learning/logistic_regression_opt_interface.hpp
Fix for #519 and #419. But doesn't disable validation tracking.
- Validation set is turned on
- Large number of features are present
This is escpecially a problem with image classification with large #
classes.
The second order information is being computed but never used. This is
an O(N * F * F * C * C) operation where F is the number of features
(which is around 1K) and N is the size of the validation set. This is
really, really expensive. This quadratic complexity is no longer needed.
> Fixed critical bug in logistic/linear regression with validation tracking

- CMakeLists.txt
- src/external/CMakeLists.txt
- src/external/aws-sdk-cpp/CMakeLists.txt
- src/flexible_type/flexible_type.hpp
- src/flexible_type/type_traits.hpp
- src/lambda/pylambda_function.hpp
- src/sframe_query_engine/algorithm/ec_sort.hpp
- src/sframe_query_engine/algorithm/groupby_aggregate.hpp
- src/sframe_query_engine/algorithm/sort.hpp
- src/sframe_query_engine/planning/optimizations/optimization_transforms.hpp
- src/unity/lib/unity_sarray.hpp
- src/unity/lib/unity_sframe.hpp
- src/unity/python/turicreate/cython/CMakeLists.txt
- src/unity/toolkits/factorization/factorization_model_impl.hpp
- src/unity/toolkits/nearest_neighbors/distance_functions.hpp
- src/unity/toolkits/supervised_learning/xgboost.hpp
- test/unity/toolkits/recsys/itemcf.cxx
Add -Werror for clang debug builds. Whitelists existing warnings, with the idea being that we can gradually remove warning types from the whitelist until we get down to no warnings. Then we can investigate using -Werror in other contexts (non-clang?)
> Add -Werror with most existing warnings whitelisted via -Wno-error

- src/unity/python/turicreate/data_structures/sframe.py
Looks like things have changed with the `pack_columns`, `unpack`, `stack', and `unstack`. Looks like they treat arrays a little differently and new column names are automatically based on old column names.
> updated docstring examples

- src/unity/lib/unity_sarray.cpp
There are already Materializing print statements in the underlying plot
types (histogram and item_frequency), so this one is duplicated.
Fixes #517
> Get rid of extra Materializing print statement

- src/unity/toolkits/image/image_fn_export.hpp
`IMAGE_UTIL_HPP` is used by `image_util.hpp`.
> fix duplicate preprocessor identifier

- test/capi/boost_utils.hpp
- test/capi/capi_datetime.cxx
- test/capi/capi_ndarray.cxx
- test/capi/capi_sframe.cxx
For some reason, boost::test leaves something undefined when compiled on
Linux, if you try to print `std::nullptr`. We can fix that by defining
it ourselves.
> Fix Linux C++ test build

- src/unity/lib/unity_sarray.cpp
- src/unity/lib/unity_sframe.cpp
- src/unity/lib/visualization/columnwise_summary.cpp
- src/unity/lib/visualization/histogram.cpp
- src/unity/lib/visualization/item_frequency.cpp
- src/unity/lib/visualization/show.cpp
Just print out that we are materializing, then allow the display of the
visualization to indicate to the user that it's done.
> Remove "Done" from visualization materialization

- src/unity/lib/unity_sarray.cpp
- src/unity/python/turicreate/test/test_image_type.py
This patch allows for
urls = tc.SArray(["a.png","b.jpg","file:///somewhere/a.png",
"https://someotherplace.com/image.png"])
images = urls.astype(tc.Image)
> Allow SArray of URL -> SArray of Image conversion via astype

- userguide/style_transfer/README.md
- userguide/style_transfer/how-it-works.md
- Generally tries to avoid too technical terms, like "inference"
- Removes section on hidden parameters
- Typos and minor fixes
> Style transfer user guide polish

- src/sframe/CMakeLists.txt
- src/sframe/sarray.hpp
- src/sframe/sarray_file_format_interface.hpp
- src/sframe/sarray_file_format_v2.hpp
- src/sframe/sarray_v2_block_writer.cpp
- src/sframe/sarray_v2_block_writer.hpp
- src/sframe/sframe.cpp
- src/sframe/sframe.hpp
- src/sframe/sframe_compact.cpp
- src/sframe/sframe_compact.hpp
- src/sframe/sframe_compact_impl.hpp
- src/sframe/sframe_constants.cpp
- src/sframe/sframe_constants.hpp
- src/sframe/sframe_saving.cpp
- src/unity/lib/unity_sarray.cpp
- test/sframe/sarray_test.cxx
- test/sframe/sframe_test.cxx
Implemented compaction heuristics for sframe/sarray append so that
recursive appends, or continuous appends of small sframe/sarrays do not
result in poorly organized SFrames.
The basic mechanism of the compaction process is two methods, a
sarray_fast_compact and a sarray_compact method. sarray_fast_compact
will look for contiguous segments with less than
FAST_COMPACT_BLOCKS_IN_SMALL_SEGMENT (8 by default) number of blocks,
and compact them into a single segment.
The sarray_compact method will try to perform a fast compaction, and if
unable to bring it below a threshold (SFRAME_COMPACTION_THRESHOLD =
256), will perform a full rewrite of the entire sarray.
SFrame compact is similar.
In addition, a block writing option ("disable_padding") is pushed
all the way through to sframe/sarray. This …
> Append fixes

- src/unity/python/turicreate/toolkits/sentence_classifier/_sentence_classifier.py
This small PR will add a parameter _max_iterations_ to sentence classifier which is built on top of logistic classifier. Former has this optional parameter in create function. 
There is one more consideration: 
LogisticClassifier has a parameter description as following
> max_iterations : **float**, optional
which we believe is a mistake as it is generally should be **int** number.
> Add fix for issue #633

- src/unity/python/turicreate/test/test_object_detector.py
- src/unity/python/turicreate/toolkits/object_detector/_sframe_loader.py
This PR makes ill-formatted annotations cause an error up-front (before any training has happened) and shows the first five offenders. It adds check for negative width/height (#552).
Fixes #552 
Fixes #588
> Pre-screen all detection annotations for early error handling

- userguide/text/analysis.md
Within this section, following the sample code produces an error because `SArray.dict_trim_by_values` expects the `dtype` to be `dict`, not `str`.
This change adds a step to first call `turicreate.text_analytics.count_words` to convert the `SFrame dtype=str` into a ` dtype=dict` before proceeding with the `trim_by_keys` and `stopwords` example.
> add missing step to fix type error in userguide/text/analysis.md

- src/unity/python/turicreate/_sys_util.py
- src/unity/python/turicreate/toolkits/_mps_utils.py
- src/unity/python/turicreate/toolkits/object_detector/_sframe_loader.py
- src/unity/python/turicreate/toolkits/object_detector/object_detector.py
- src/unity/toolkits/tcmps/mps_cnnmodule.mm
- src/unity/toolkits/tcmps/mps_graph_cnnmodule.h
- src/unity/toolkits/tcmps/mps_graph_cnnmodule.mm
- src/unity/toolkits/tcmps/mps_graph_networks.h
- src/unity/toolkits/tcmps/mps_graph_networks.mm
- src/unity/toolkits/tcmps/mps_graph_trainer.h
- src/unity/toolkits/tcmps/mps_graph_trainer.mm
- src/unity/toolkits/tcmps/mps_layers.mm
- src/unity/toolkits/tcmps/mps_utils.h
- src/unity/toolkits/tcmps/mps_weight.h
With these changes, training an object-detection model for our demo dataset takes around 31 minutes on an iMac Pro, instead of 55.
- Resolve warnings in the TC-MPS library
- Replace the synchronous API for evaluating an MPS graph with an async one
- On the Python side, use four threads: one that waits for SFrame operations, one Python-heavy one that schedules data augmentation, one that waits for data augmentation and copies into NumPy, and one that copies into MPS and waits for MPS.
We still don't keep the GPU busy all the time, but it's not clear how much farther we can get with so much logic implemented in Python and subject to the global interpreter lock.
> Object detector optimization

- src/unity/toolkits/coreml_export/coreml_export_utils.cpp
Currently, the add_metadata field for the coreml model export did not
allow updating of metadat fields without having some baseline fields
filled in.  This is problematic when additional fields had to be updated
later.
> Softened metadata update requirements for CoreML models.

- CMakeLists.txt
- src/objc/CMakeLists.txt
- Moves adjustments to COMPILER_FLAGS up before COMPILER_FLAGS is used to construct downstream CMake variables
- Use -miphoneos-version-min instead of -mmacosx-version-min when building for iOS, to avoid copious warnings about -isysroot not matching deployment target
- Update libobjc CMakeLists.txt to avoid redundant xcrun invocation
> Fix libRecommender iOS build

- CMakeLists.txt
I almost got this right the last time. In the macOS case, I had erred on the side of continuing to use CMAKE_OSX_DEPLOYMENT_TARGET, but we need to modify COMPILER_FLAGS to propagate to the external CMake invocations.
Fixes #729
> Propagate -mmacosx-version-min=10.12 to external dependencies

- scripts/install_python_toolchain.sh
- scripts/requirements.txt
- src/unity/python/turicreate/test/test_explore.py
- src/visualization/Turi Create Visualization.xcodeproj/project.pbxproj
Also adds a unit test to sanity check the visualization client, to
ensure that at least the explore view of an SFrame shows the contents of
the SFrame.
Fixes #652
> Fix visualization compatibility on 10.12 & 10.13

- BUILD.md
Note that `xxd` and X11 development libraries are required to build on Linux.
Fixes #554
> Update and clarify Linux build requirements

- src/external/google/protobuf/CMakeLists.txt
Previously, the CMakeLists.txt was including most protobuf source files,
even though we are only including the headers for the lite version.
> Use only the lite source files from protobuf

- src/unity/python/turicreate/cython/CMakeLists.txt
With macOS 10.13 and Xcode 9, I am now getting a build break on latest
master, due to the `-Werror` change that went in. I'm not sure why this
doesn't repro on macOS 10.14 beta / Xcode 10 beta, but the Cython
generated code on my machine gives warnings (now treated as error). This
change suppresses the specific warning in the compilation of the
generated code.
> Fix release build break on 10.13 / Xcode 9

- userguide/cpp.md
The build now needs `src/external` to be added to the include path,
since some of the headers now include protobuf from there.
Related to (but does not fully address) #613.
> Fix broken C++ userguide build instructions

- src/unity/python/turicreate/toolkits/_image_feature_extractor.py
- src/unity/python/turicreate/toolkits/_pre_trained_models.py
Fixes #286 
Give a useful error message to the user when we can't write to the cache path. Also only create the model caches directory in one place.
> Better error message for unwritable cache path

- src/unity/python/turicreate/toolkits/_mps_utils.py
- src/unity/toolkits/tcmps/mps_cnnmodule.h
- src/unity/toolkits/tcmps/mps_cnnmodule.mm
- src/unity/toolkits/tcmps/mps_dev.h
- src/unity/toolkits/tcmps/mps_dev.mm
- src/unity/toolkits/tcmps/mps_graph_cnnmodule.h
- src/unity/toolkits/tcmps/mps_graph_cnnmodule.mm
- src/unity/toolkits/tcmps/mps_graph_layers.h
- src/unity/toolkits/tcmps/mps_graph_layers.mm
- src/unity/toolkits/tcmps/mps_graph_networks.h
- src/unity/toolkits/tcmps/mps_graph_networks.mm
- src/unity/toolkits/tcmps/mps_graph_trainer.h
- src/unity/toolkits/tcmps/mps_graph_trainer.mm
- src/unity/toolkits/tcmps/mps_layers.h
- src/unity/toolkits/tcmps/mps_layers.mm
- src/unity/toolkits/tcmps/mps_lstm_helper.h
- src/unity/toolkits/tcmps/mps_lstm_helper.mm
- src/unity/toolkits/tcmps/mps_networks.h
- src/unity/toolkits/tcmps/mps_networks.mm
- src/unity/toolkits/tcmps/mps_trainer.h
- src/unity/toolkits/tcmps/mps_trainer.mm
- src/unity/toolkits/tcmps/mps_updater.h
- src/unity/toolkits/tcmps/mps_updater.mm
- src/unity/toolkits/tcmps/mps_utils.h
- src/unity/toolkits/tcmps/mps_utils.mm
- src/unity/toolkits/tcmps/mps_weight.h
- src/unity/toolkits/tcmps/mps_weight.mm
Our libtcmps.dylib really shouldn’t export pure C functions with names like “Init” and “Load”, which are bound to collide someday with someone who links against this library. Instead, we should add a prefix to all C functions and Objective-C classes. Going with “TCMPS” as the best fit for existing names in this code base. While we’re at it, the C++ symbols are moved into a new turi::mps namespace, instead of being declared at the top level.
Also did some miscellaneous cleanup in the top-level C interface for TCMPS. All of these changes should be behavior-preserving, although previously some Objective-C code was running outside of autorelease pools (that we know will drain).
> Clean up TCMPS symbols

- src/unity/toolkits/tcmps/mps_weight.mm
With the just-released developer seed 18A326g, MPSCNNConvolutionDataSource and MPSCNNBatchNormalizationDataSource now inherit from NSCopying. We must add conformance to our data source implementations to avoid build breakage, since we compile with -Werror.
> Add NSCopying conformance to TCMPSConvolutionWeights and TCMPSBatchNormData

- src/unity/lib/unity_sarray.cpp
@hoytak and I discussed that it'd be best to print out the size of the SArray parsed in the C++ layer as load file summary, so added code to do that.
> Added code to keep track of size of SArray, fixes #758

- src/logger/assertions.hpp
- src/unity/python/turicreate/test/test_sentence_classifier.py
- src/unity/python/turicreate/test/test_tree_tracking_metrics.py
- src/unity/python/turicreate/toolkits/_supervised_learning.py
- src/unity/toolkits/supervised_learning/supervised_learning.cpp
- src/unity/toolkits/supervised_learning/supervised_learning.hpp
- src/unity/toolkits/supervised_learning/supervised_learning_utils-inl.hpp
- src/unity/toolkits/supervised_learning/xgboost.cpp
* Uses "Training " and "Validation " (capital letter, space at the end)
as the standard header prefixes.
* Adds a concept of "metric display name", and uses the display name
whenever there is one defined when adding metric names to the progress
headers. I.e., "Log Loss" instead of "log_loss".
Fixes #757
> Clean up toolkit progress header names

- src/table_printer/table_element_printers.hpp
- src/table_printer/table_printer.cpp
- src/table_printer/table_printer.hpp
- src/toolkits/image_deep_feature_extractor/mlmodel_image_feature_extractor.mm
I really wanted to do some more cleanup in this file, but it was in danger of becoming a rabbit hole. For now, a quick fix that relies on the fact that all current table_printer uses but one have tracking enabled: have `print_footer()` just print the last tracked row if it wasn't already printed. We just need to add a little additional state so that we know when a `flex_float` actually originated from a `progress_time` or when a `flex_int` actually originated from a `bool`.
Also update the one non-tracking toolkit to print the final progress row explicitly.
Fixes #766
> Ensure that current table_printer uses always print the last line of progress

- src/unity/toolkits/tcmps/mps_graph_layers.h
- src/unity/toolkits/tcmps/mps_graph_layers.mm
- src/unity/toolkits/tcmps/mps_layers.h
- src/unity/toolkits/tcmps/mps_layers.mm
- src/unity/toolkits/tcmps/mps_weight.h
- src/unity/toolkits/tcmps/mps_weight.mm
Deeper fix for #742: adopt the newer convenience API for updating our data sources
> Adopt new MPSNNOptimizer API for updating conv and batch-norm weights

- BUILD.md
PR #823 introduced a new dependency on Xcode 10 beta 3 (which introduced some new MetalPerformanceShaders API) but neglected to update the build instructions
(Xcode 9 is still supported, since in that case we don't attempt to build the relevant code against the macOS 10.14 SDK)
> Update build instructions to reflect updated Xcode beta requirement

- src/objc/TuriCreateObjC.m
When the model uses int64 item IDs, we should use NSNumber as the key
type in the output dictionaries.
Fixes #832
> Use NSNumber for item IDs in TCRecommender

- src/unity/python/turicreate/test/test_activity_classifier.py
- src/unity/python/turicreate/toolkits/activity_classifier/_activity_classifier.py
- src/unity/python/turicreate/toolkits/activity_classifier/util.py
1. Solved two bugs in the way the train-validation split was used in the Activity Classifier (causing `create()` to crash when `validation_set='auto'`).
2. Improved the `random_split_by_session() ` mechanism. The current implementation might have broken line order - which is not allowed for the AC. The new mechanism is optimized for the typical case of 100-1000 training sessions.
3. Added explicit unit test that covers the auto validation set in all relevant cases.
> Resolve #614 - a few bug fixes in AC train-test split 

- src/numerics/armadillo.hpp
- src/optimization/accelerated_gradient-inl.hpp
- src/optimization/lbfgs-inl.hpp
- src/optimization/newton_method-inl.hpp
- src/unity/python/turicreate/test/test_logistic_classifier.py
- src/unity/python/turicreate/toolkits/_supervised_learning.py
- src/unity/toolkits/supervised_learning/logistic_regression_opt_interface.cpp
`model.get_status(...)` and `printer.print_progress_row_strs(...)` both update state. `model.get_status(...)` updates the models coefficients and values stored by the printer are used by model auto selection code. This change makes sure that both methods are called at least one, even when the initial residuals are zeros. 
Fixes #764
With this change progress printing for models training will now show an entry for the zero-th iteration, instead of starting at one. Besides fixing #734, that should be the only user facing change.
Moved an info message for FISTA so it doesn't get printed inside of the progress table.
> Ensure model state is always updated with training

- src/unity/python/turicreate/test/test_image_classifier.py
- src/unity/python/turicreate/test/test_object_detector.py
- src/unity/python/turicreate/toolkits/image_classifier/image_classifier.py
- src/unity/python/turicreate/toolkits/object_detector/object_detector.py
- Adds single-sample input to object detector
- Changes single-sample input for classification to unpack the return
Addresses #342.
Previous classifier behavior:
```python
>>> cc.predict(image)
dtype: str
Rows: 1
['bike']
```
New behavior:
```python
>>> cc.predict(image)
'bike'
```
Since this breaks current behavior, this should not be merged yet.
> Single-sample input gives single-sample results

- src/capi/impl/capi_sframe.cpp
In capi_sframe.cpp, there is a comparison between signed and unsigned:
```
/builds/turi/turicreate/src/capi/impl/capi_sframe.cpp: In function 'tc_sframe* tc_sframe_join_on_single_column(tc_sframe*, tc_sframe*, const char*, const char*, tc_error**)':
/builds/turi/turicreate/src/capi/impl/capi_sframe.cpp:206:13: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
if (added == -1) { assert(false); return NULL; } // error should be populated already
```
For some reason, this only shows up as an error on Linux and not macOS.
> Fix Linux build break

- src/unity/python/turicreate/toolkits/_internal_utils.py
Due to tests exercising different import patterns
> Fixes some unit test failures introduced by #864

- src/unity/python/turicreate/toolkits/_internal_utils.py
- src/unity/python/turicreate/toolkits/_supervised_learning.py
- src/unity/python/turicreate/toolkits/regression/_regression.py
- src/unity/toolkits/supervised_learning/supervised_learning_utils-inl.hpp
- src/unity/toolkits/supervised_learning/xgboost.cpp
Fixes the failing test_classifier.py
The Python implementation of automatic classification should attempt to query tr
aining_accuracy, not just validation_accuracy, directly from the model state. (Tree-based models recently stopped incorrectly storing 0 for validation metrics, instead not storing these fields at all, due to #864). 
In addition, xgboost.cpp should write metrics to the progress table using the up
dated display name (propagating changes for #818), so that tree-based models now
have e.g. "Validation Accuracy" instead of "Validation accuracy".
Finally, also fixes another bug in #864: when the user explicitly specifies validation_set=None (as in some tests), the auto-classifier path runs the validation set through `_validate_data` twice. The first call was converting None to an …
> Fix accuracy metrics used by automatic classification

- src/table_printer/table_printer.hpp
There is no reason the table printer shouldn't have a default
constructor
> Add default constructor to table printer

- src/optimization/lbfgs-inl.hpp
Calibrating the solver can take a long time.  This prints a warning when
this happens.
> Added helpful timing message to lbfgs solver

- src/unity/python/turicreate/toolkits/object_detector/object_detector.py
I thought I fixed this before, but perhaps it was reverted. This fixes a common eyesore when using a CUDA GPU that looks like this:
```
Note that increasing the degree of parallelism also increases the memory footprint.
+--------------+--------------+--------------+
| Iteration    | Loss         | Elapsed Time |
+--------------+--------------+--------------+
[09:32:07] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:107: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
| 1            | 6.386        | 18.9         |
| 10           | 6.558        | 25.4         |
```
This PR places the all warnings happening at the beginning of training above the table instead.
> Make warnings appear above OD training progress table

- userguide/recommender/coreml-deployment.md
Fixes #867 and #799 until we release TuriCreate and create different `libRecommender`s that are called `libRecommender`.
> Added instructions to rename and add libRecommender to various places

- src/unity/python/turicreate/test/test_tree_tracking_metrics.py
- src/unity/toolkits/supervised_learning/supervised_learning.cpp
- src/unity/toolkits/supervised_learning/supervised_learning.hpp
Reverts #746, since the functionality added with this change appears to be unused. The parameter added to `api_evaluate()` wasn't even being exposed to the C API. All this change did was remove metrics from models and break unit tests for a month.
Updates test_tree_tracking_metrics to incorporate changes for #818 and #868 
Fixes #831 
With these changes there are still test failures in test_recommender.py, but I'll leave that for a separate issue. I'm hoping someone more familiar with that toolkit can look at those.
> Fix metrics-related failures in unit tests

- src/fileio/fs_utils.cpp
- src/fileio/fs_utils.hpp
- src/fileio/general_fstream.cpp
- src/fileio/union_fstream.cpp
- src/logger/CMakeLists.txt
- src/logger/error.cpp
- src/logger/error.hpp
- src/logger/logger.hpp
- src/serialization/dir_archive.cpp
- src/unity/lib/unity_global.cpp
- test/capi/capi_models.cxx
* Adds a turi::error namespace and io_error class. This can be used to
distinguish between ios_base::failure coming from the C++ standard
library, and I/O errors we throw ourselves with a crafted message.
* Use the new io_error from our own log_and_throw macros.
* In some key places related to model saving, avoid handling and
throwing a new error when we already have a turi::error.
The result is that in a few cases, the previous user-facing error
message about unknown errors has been replaced with meaningful error
messages on model save:
* When the directory path already exists as a file.
* When the directory fails to be created, and does not exist at all.
> Clean up error messages on model save

- src/logger/logger.hpp
Missed a trailing backslash to continue the macro.
> Fix build break caused by #862

- src/unity/python/turicreate/toolkits/object_detector/_sframe_loader.py
Got rid of the raw image column while shuffling. 
Using the data that @dhgokul sent to us, we noticed that just the raw image column was causing the size of the SFrame to blow up (from around 40 MB to around 760 MB) because of which `shuffle` was taking a long (but finite) amount of time. 
Since that was the bottleneck, we now get rid of the raw image column just during the shuffle. After a lightning fast shuffle, we add the raw image column back and training proceeds like before.
Consequently, training time for that model went down from 79 minutes to 39 minutes for Turi Create 4.3.2 on a GPU in Linux.
> Fixes #608

- test/unity/unity_sarray.cxx
- test/unity/unity_sframe.cxx
#862 revealed that `test_save_load()` in the C++ SArray and SFrame tests was not actually saving and loading the model. Using `get_temp_name()` instead of `"cache://testdir"` appears to do the trick
> Use get_temp_name() in SArray and SFrame test_save_load()

- src/unity/python/turicreate/toolkits/object_detector/object_detector.py
It's not  entirely  clear today if a detector was exported with NMS. This adds so that if it's included, the description reflects it:
> Make clear if mlmodel has NMS

- src/unity/python/turicreate/toolkits/_model.py
Adopts in CustomModel.save() the same canonicalization code used in Model.save()
Fixes #593
> Normalize save paths given to CustomModel instances

- src/unity/python/turicreate/data_structures/sarray.py
- src/unity/python/turicreate/test/test_sarray.py
Operations on a numpy.matrix object yield another numpy.matrix object, and each instance always has two-dimensional shape. When our SArray type-deduction or data-loading code attempts to traverse this data structure recursively, we get an unbounded recursion. The simplest solution seems to be to guard explicitly against numpy.matrix and convert to numpy.ndarray up front.
Fixes #357
> Support for initializing SArray using numpy.matrix

- src/unity/python/turicreate/toolkits/_internal_utils.py
- src/unity/python/turicreate/toolkits/_mxnet_utils.py
- src/unity/python/turicreate/toolkits/object_detector/object_detector.py
- src/unity/python/turicreate/toolkits/style_transfer/style_transfer.py
- src/unity/python/turicreate/util/__init__.py
This PR primarily introduces warnings if a user tries to use a CUDA GPU with insufficient free memory. This may happen if for instance Tensorflow has allocated the memory unbeknownst the user. 
- Note, the estimated memory requirements are experimental estimates. These experiments were conducted by first allocating a specific amount of memory and then trying to train the model. I did this for values that the should influence the memory usage (batch size, and number of style in ST) and then fit a simple line to it. Since it's only an estimate, I don't want to cause a fatal error, so this is just a warning that should help the user understand if there is subsequent fatal error.
- Also show name of CUDA GPUs (just like for MPS)
- Consolidate device printing code between OD/ST
- Provide …
> Warning for CUDA GPUs if not enough free memory

- src/unity/python/turicreate/cython/cy_flexible_type.pyx
- src/unity/python/turicreate/data_structures/sarray.py
- src/unity/python/turicreate/test/test_sarray.py
The C++ backend represents all empty ndarray values as 0-dimensional: it assumes that each element of the shape array is positive. This design is enshrined in our serialization, so we should avoid changing it.
We use `numpy.asarray` on a buffer-protocol wrapper around the backend to reconstitute a `numpy.ndarray` value, but `asarray` does something unexpected when given a zero-dimensional buffer: it creates a one-dimensional, size-1 value read from undefined memory.
Instead, we canonicalize empty backend values to `array([])`. This is consistent with how scalar inputs round-trip to 1-d, size-1 values (e.g., `np.array(3.0)` becomes `np.array([3.0])`). (That behavior is due to the C++ ndarray constructor. Given an empty shape vector, it infers a 1-d shape from the flattened (size-1) data …
> Convert empty numpy.ndarray values to array([]) in SArray initializer

- LINUX_INSTALL.md
The existing links were removed from the apt repository. Updating with
the newest (working) links.
Fixes #903
> Fix the links in the Linux build instructions.

- userguide/object_detection/export-coreml.md
Also fixes the link markdown syntax and the link itself to the app.
Fixes #877 - this takes a stab at address the confusion in this issue. However, I think we should also see if we can get the folks behind the Vision example app to add an error/warning if someone replaces their default model with one that does not produce results as `VNRecognizedObjectObservation` objects.
> Clarify Vision example app behavior

- src/unity/toolkits/tcmps/mps_cnnmodule.h
- src/unity/toolkits/tcmps/mps_cnnmodule.mm
- src/unity/toolkits/tcmps/mps_layers.h
- src/unity/toolkits/tcmps/mps_layers.mm
Adopts some suggestions and new API from the MPS team. Collectively, these changes seem to yield a 10-12% speedup on tested MacBook Pro and iMac Pro configurations. The biggest improvements owe to using new API optimizing `MPSImageBatch` operations, and to removing a workaround for a bug in using temporary images for the dropout layer.
Note: this PR depends on API introduced in developer seed 4, 18A336e
Fixes #748, fixes #749
> Performance tweaks for activity classifier (MPS implementation)

- src/unity/python/turicreate/cython/cy_flexible_type.pyx
The `builtins.long` and `builtins.unicode` types don't appear to exist (at least in Python 3.6).
> Fix import in Python 3

- src/unity/lib/image_util.cpp
- test/unity/image_util.cxx
* When collecting files from a user-provided directory with format='auto', ignore files from which the 'auto' implementation will not deduce a format
* If the logic above ignores all regular files in the provided directory, emit a warning.
* Stat the user-provided path, so that we can consistently throw if the path does not exist. Before, relative paths to non-existent files silently returned an empty SFrame
Fixes #641
> Clean up load_images logic surrounding format='auto'

- src/capi/CMakeLists.txt
The CAPI object build must depend on its requirements (since in
the case of boost, that creates even the header files), even
though there is no linking stage with the dependencies yet.
Fixes #996
> Add missing build order dependency

- src/unity/python/turicreate/test/test_activity_classifier.py
- src/unity/python/turicreate/toolkits/activity_classifier/_activity_classifier.py
- src/unity/python/turicreate/toolkits/activity_classifier/util.py
We expose tc.activity_classifier.util.random_split_by_session as public API, so it should perform the split unconditionally. The logic to only create an auto validation set if we have 100 sessions belongs in the activity_classifier.create function itself
Fixes #964
> Move activity_classifier logic for whether to create an auto validation set to create function

- src/unity/python/turicreate/toolkits/style_transfer/style_transfer.py
Avoids call to `coremltools.models.MLModel`.
As a sanity check, the unit test in question passes on macOS 10.14. Need to test on macOS 10.13.
> Fixes #995 -- fix is similar to #778

- src/unity/python/turicreate/test/test_activity_classifier.py
- src/unity/python/turicreate/test/test_evaluation.py
- src/unity/python/turicreate/toolkits/activity_classifier/_activity_classifier.py
- src/unity/python/turicreate/toolkits/evaluation.py
- src/unity/toolkits/evaluation/metrics.cpp
The log loss, ROC curve, and AUC metrics support multiclass classification by accepting probability vectors as predictions. They infer the semantics of the probability vector by sorting all the labels found in their targets input. If the number of distinct labels is smaller than the probability vectors' length, these metrics throw an error.
With this change, these metrics support an explicit mapping from label to index into the probability vector. The activity classifier's evaluate method adopts this new API, making it robust to evaluation data that doesn't span all the training labels.
Fixes #969, fixes #1007 
Note: if we aren't comfortable committing to this new API for the evaluation toolkit (at the last minute before cutting 5.0), we could instead implement it on an interval version …
> Enhance evaluation toolkit to accept explicit index map

- CMakeLists.txt
- src/unity/python/turicreate/test/test_style_transfer.py
- src/unity/python/turicreate/toolkits/style_transfer/style_transfer.py
- Avoids call to `coremltools.models.MLModel`
- Only runs flexible shape code if macOS version is >= 10.14
> Fixes #995

- src/unity/python/turicreate/toolkits/distances/_distances.py
This fixes the DeprecationWarning for invalid escape sequences when using
nearest neighbors in Python.
Fixes #948
> Fix escape sequences in math comments

- src/unity/toolkits/activity_classification/sequence_iterator.cpp
Use size_t instead of int in `vec_mode` so that the comparison
between `histogram.size()` and the value doesn't conflict with
respect to sign. The values should always be natural numbers
(array indices) so size_t is appropriate.
> Fix build break on Linux

- src/unity/python/turicreate/test/test_json.py
Make sure we open a NamedTemporaryFile in a way that allows writing
strings (not just bytes). In Python 3, string literals are unicode.
> Fix test_json failure in Python 3

- src/unity/python/turicreate/test/test_sframe_sequence_iterator.py
The golden output before assumed that the mode of [3, 2] is 3. The new algorithm (introduced in #1005), using a histogram, always returns the first index with maximal count, in this case, 2.
> Update activity classifier SFrame iterator test to reflect updated computation of mode

- src/toolkits/image_deep_feature_extractor/mlmodel_image_feature_extractor.mm
Otherwise, a corrupted model cache will leave the machine in a state where feature extraction will repeatedly fail, across process launches, until the corrupted files are removed from the temporary directory
Fixes #1065
> mlmodel_image_feature_extractor should delete and replace cached models that cannot be loaded successfully

- src/unity/python/turicreate/data_structures/sframe.py
- src/unity/python/turicreate/test/test_sframe.py
Fixes #1102 
When SFrame is empty, the original assignment maps constant values to SArray of size 0 - now it maps to size 1.
> Const assignment to empty SFrame

- test/capi/capi_models.cxx
I didn't remove the test entirely since I want to believe we'll figure out the right way to do this someday :smile:
> Comment out test for expected failure that we can't trigger in all CI environments

- src/unity/python/turicreate/cython/cy_flexible_type.pyx
- src/unity/python/turicreate/test/test_flexible_type.py
Casts lists and arrays to tuples when they are the keys for a dictionary type.
> Fix for #1096

- .travis.yml
We need to get our Travis CI build under two hours more reliably. We can skip the OD tests for now, since I'll likely be running then manually a bunch anyway in the near future (aside from any other CI coverage).
Builds on the black list we already added to cover issues with style transfer (see #1031)
> Skip object detector unit tests in Travis CI for now

- userguide/text_classifier/README.md
- A swift function can not be called till after it is defined.
- The NSLinguisticTagger does not convert to lowercase.
> User Guide: update swift code to tokenize text

- src/unity/python/turicreate/toolkits/_mps_utils.py
- src/unity/toolkits/tcmps/CMakeLists.txt
- src/unity/toolkits/tcmps/mps_cnnmodule.h
- src/unity/toolkits/tcmps/mps_cnnmodule.mm
- src/unity/toolkits/tcmps/mps_float_array.cpp
- src/unity/toolkits/tcmps/mps_float_array.hpp
- src/unity/toolkits/tcmps/mps_graph_cnnmodule.h
- src/unity/toolkits/tcmps/mps_graph_cnnmodule.mm
- src/unity/toolkits/tcmps/mps_graph_layers.h
- src/unity/toolkits/tcmps/mps_graph_layers.mm
- src/unity/toolkits/tcmps/mps_graph_networks.h
- src/unity/toolkits/tcmps/mps_graph_networks.mm
- src/unity/toolkits/tcmps/mps_graph_trainer.h
- src/unity/toolkits/tcmps/mps_graph_trainer.mm
- src/unity/toolkits/tcmps/mps_layers.h
- src/unity/toolkits/tcmps/mps_layers.mm
- src/unity/toolkits/tcmps/mps_networks.h
- src/unity/toolkits/tcmps/mps_networks.mm
- src/unity/toolkits/tcmps/mps_trainer.h
- src/unity/toolkits/tcmps/mps_trainer.mm
- src/unity/toolkits/tcmps/mps_utils.h
- src/unity/toolkits/tcmps/mps_utils.mm
These changes clean up how TCMPS receives input data and how it imports/exports network weights. They should make it easier to reason about memory management and simplify future C++ toolkit development.
It may be helpful to look at the diffs for each of the three commits individually. Each one introduces some new code and has a bunch of corollary boilerplate/mechanical changes.
Fixes #762
> Object-oriented interface for TCMPS inputs and parameters

- CMakeLists.txt
- src/platform/parallel/pthread_tools.hpp
- src/unity/toolkits/coreml_export/MLModel/src/NeuralNetworkShapes.hpp
- src/unity/toolkits/coreml_export/MLModel/src/NeuralNetworkValidator.cpp
- src/unity/toolkits/coreml_export/MLModel/src/Utils.cpp
Tested on Ubuntu 18.04 with gcc 7.3.0
The gcc7 build seems to have broken (further) since #108 went in.
This change fixes various build breaks in gcc7 due to a combination
of new warnings, warnings as error, and misuse of cache variables
in CMake.
> Fix build on gcc7

- src/unity/python/turicreate/toolkits/_mps_utils.py
- src/unity/python/turicreate/toolkits/object_detector/object_detector.py
- src/unity/toolkits/tcmps/mps_float_array.cpp
- src/unity/toolkits/tcmps/mps_float_array.hpp
- src/unity/toolkits/tcmps/mps_graph_cnnmodule.h
- src/unity/toolkits/tcmps/mps_graph_cnnmodule.mm
- src/unity/toolkits/tcmps/mps_graph_networks.h
- src/unity/toolkits/tcmps/mps_graph_networks.mm
- src/unity/toolkits/tcmps/mps_graph_trainer.h
- src/unity/toolkits/tcmps/mps_graph_trainer.mm
- src/unity/toolkits/tcmps/mps_trainer.h
- src/unity/toolkits/tcmps/mps_trainer.mm
- src/unity/toolkits/tcmps/mps_utils.h
- src/unity/toolkits/tcmps/mps_utils.mm
Before these changes, clients of the TCMPS backend (for graph-API-based models, such as object detection) had to reason about the backend as having a consumer queue of inputs and a producer queue of outputs, leaving it to the client to track with output corresponds to which input.
With these changes, submitting an input to the backend immediately returns an object that will hold the future output.
I originally wanted to get the low-level-API side too, for activity classification, but I wanted to focus on OD work for now since I'm behind schedule. (I'd rather get one model completely converted sooner and the other later, than have both finish simultaneously later.) For that reason, this addresses only half of #755 (although it includes the work common to both cases).
> Refactor TCMPS interface for object detection

- src/flexible_type/string_parser.hpp
- src/unity/python/turicreate/test/test_json.py
When there are exactly 128-char strings within a nested JSON
structure, they were silently dropped due to an off-by-one
comparison. This change fixes the bug, and adds a unit test to
ensure correct behavior. (Verified that this test failed prior
to this change, and passes now with this change.)
> Fix strange JSON parsing bug

- src/unity/lib/gl_sframe.hpp
- src/unity/python/turicreate/data_structures/sarray.py
- src/unity/python/turicreate/data_structures/sframe.py
- userguide/README.md
There are several places we still refer to a "Turi Server" in the
API docs and user guide. This commit removes that wording (at this
point it's very confusing and not clear what it refers to), and in
some places, adds clarification that network filesystems should
work with SFrame/SArray.
> Remove "Turi Server" from documentation

- scripts/requirements.txt
- src/unity/python/turicreate/test/test_json.py
This adds a "test_arbitrary_json" test to SFrame JSON parsing.
Using the `hypothesis` module, we can generate test cases of
valid JSON, and compare the results of SFrame's parser to
Python's built-in JSON module.
This test uncovered 3 bugs, but they are documented in the
test as known issues and the test passes.
> Comprehensively test JSON parsing using hypothesis

- CMakeLists.txt
- src/logger/error.cpp
- src/logger/error.hpp
gcc on travis and clang on mac OSX differ in whether std::exception has the noexcept decorator on the what() method.  Normally this is a warning, but with -Werror it fails to compile.  This adds a compile-time check for this behavior
> Added check for noexcept on what() in exceptions.

- src/unity/lib/visualization/plot.cpp
- src/unity/lib/visualization/vega_data.cpp
- src/unity/lib/visualization/vega_spec.cpp
- src/unity/python/turicreate/visualization/_plot.py
With this change, the C++ plot API matches the Python plot API,
which returns Vega-compatible spec and data JSON objects. Only
in the case of the show method (in either Python or C++) should
we prepend each with "vega_spec" or "data_spec" containers, as
those are specific to the way data is handled in tcviz. Prior
to this change, the outputs from C++ plot API were not
compatible with Vega without removing those containers.
> Refactor vega_spec and data_spec munging into show method

- CMakeLists.txt
- src/logger/error.cpp
- src/logger/error.hpp
- src/unity/lib/extensions/ml_model.cpp
- src/unity/lib/extensions/ml_model.hpp
- src/unity/lib/toolkit_class_macros.hpp
- src/unity/toolkits/supervised_learning/boosted_trees.hpp
- src/unity/toolkits/supervised_learning/decision_tree.hpp
- src/unity/toolkits/supervised_learning/linear_regression.hpp
- src/unity/toolkits/supervised_learning/linear_svm.hpp
- src/unity/toolkits/supervised_learning/logistic_regression.hpp
- src/unity/toolkits/supervised_learning/random_forest.hpp
- src/unity/toolkits/supervised_learning/supervised_learning.hpp
- test/toolkits/supervised_learning/supervised_learning_mock_test_model.cxx
This PR adds in a method for registering class methods of extension
classes when the method is defined in a base class of the class
registered as an extension type.
Two new macros are provided, BEGIN_BASE_CLASS_MEMBER_REGISTRATION()
and IMPORT_BASE_CLASS_REGISTRATION.
BEGIN_BASE_CLASS_MEMBER_REGISTRATION takes no arguments and creates a
registration block with the same form as
BEGIN_CLASS_MEMBER_REGISTRATION but taking no class name.  Then, any
classes inheriting from this can include
IMPORT_BASE_CLASS_REGISTRATION(base_class) as part of their registration
block, which causes the base class registration to be executed.
>  Add in mechanism for registering base class methods in extension types.

- .travis.yml
For more breathing room under the two-hour timeout, pending the upcoming test refactoring
> Disable test_image_classifier.py and test_image_similarity.py in Travis

- src/unity/python/turicreate/toolkits/_mps_utils.py
- src/unity/python/turicreate/toolkits/object_detector/object_detector.py
- src/unity/toolkits/neural_net/CMakeLists.txt
- src/unity/toolkits/neural_net/float_array.hpp
- src/unity/toolkits/neural_net/mps_graph_cnnmodule.mm
- src/unity/toolkits/neural_net/mps_graph_layers.mm
- src/unity/toolkits/neural_net/mps_graph_trainer.h
- src/unity/toolkits/neural_net/mps_graph_trainer.mm
- src/unity/toolkits/neural_net/mps_utils.h
- src/unity/toolkits/neural_net/mps_utils.mm
We can push the MXNet-to-MPS-to-MXNet conversions into TCMPS, where this particular transpose can be implemented as a conversion between planar and "chunky" float images. In this way, we can standardize on the CoreML layouts where possible, for consistency, leaving our MPS usage of NHWC as an implementation detail.
> Adopt CoreML/MXNet data layout (NCHW) at library interfaces (for object detection)

- userguide/image_similarity/README.md
Fixing a syntax highlight issue in the README of the image similarity when saving the model
Issue https://github.com/apple/turicreate/issues/1172
> image similarity README fix save model syntax highlight

- BUILD.md
Be explicit about user-installed dependencies on Linux, including some that we forgot to mention like lapack and Python headers.
> Clarify Linux build requirements

- src/unity/toolkits/neural_net/CMakeLists.txt
- src/unity/toolkits/neural_net/coreml_import.cpp
- src/unity/toolkits/neural_net/coreml_import.hpp
- src/unity/toolkits/neural_net/float_array.hpp
- src/unity/toolkits/neural_net/mps_cnn_module_factory.mm
- src/unity/toolkits/object_detection/object_detector.cpp
- src/unity/toolkits/object_detection/object_detector.hpp
- test/unity/toolkits/CMakeLists.txt
- test/unity/toolkits/neural_net/CMakeLists.txt
- test/unity/toolkits/neural_net/test_coreml_import.cxx
- test/unity/toolkits/object_detection/CMakeLists.txt
- test/unity/toolkits/object_detection/test_object_detector.cxx
The very first step of the `train` method will be to import the pre-trained (darknet) model parameters from a provided CoreML file. For now, this import is just a mapping from layer names to float_array values.
In addition, the object_detector class is structured in such a way as to facilitate dependency injection for proper unit testing.
> Implement initialization of pre-trained model for C-API object detector

- src/unity/python/turicreate/extensions.py
The type and quantity of the extenions arguments is checked rigorously
in the C++ part of the code after the default arguments have been filled
in, so the python check is not needed.  As the python check is not aware
of default arguments, it's better to just let the check happen in the
C++ layer.
> Fix to allow default arguments to extension types to work in python.

- src/unity/python/turicreate/test/test_json.py
The test for `(str, unicode)` should be done instead using
`six.string_types` since there is no `unicode` type in
Python 3.
> Fix test_json.py failure in Python 3

- userguide/recommender/coreml-deployment.md
Since 5.0b3, we have distributed the dylibs in a zip file under two directories for each variant - this clarifies the wording in the user guide so it matches the way we are distributing the files.
> Fix wording around renaming libRecommender dylibs

- src/unity/toolkits/neural_net/CMakeLists.txt
- src/unity/toolkits/neural_net/float_array.cpp
- src/unity/toolkits/neural_net/float_array.hpp
- src/unity/toolkits/neural_net/image_augmentation.cpp
- src/unity/toolkits/neural_net/image_augmentation.hpp
- src/unity/toolkits/object_detection/CMakeLists.txt
- src/unity/toolkits/object_detection/object_detector.cpp
- src/unity/toolkits/object_detection/object_detector.hpp
- src/unity/toolkits/object_detection/od_data_iterator.cpp
- src/unity/toolkits/object_detection/od_data_iterator.hpp
- test/unity/toolkits/neural_net/CMakeLists.txt
- test/unity/toolkits/neural_net/test_image_augmentation.cxx
- test/unity/toolkits/object_detection/CMakeLists.txt
- test/unity/toolkits/object_detection/test_object_detector.cxx
- test/unity/toolkits/object_detection/test_od_data_iterator.cxx
With these changes, I can now train a model on the data from our "breakfast" demo:
```
data = tc.SFrame('breakfast-data.sframe')
m = tc.extensions.object_detector()
m.train(data, 'annotation', 'image', {'mlmodel_path':'/Users/jong/Desktop/od-init.mlmodel', 'max_iterations' : 1000})
```
I get output like:
```
+--------------+--------------+--------------+
| Iteration    | Loss         | Elapsed Time |
+--------------+--------------+--------------+
| 1            | 7.98467      | 10.86s       |
| 2            | 7.9668       | 14.37s       |
| 3            | 7.96799      | 17.87s       |
...
| 999          | 0.560803     | 1h 1m        |
| 1000         | 0.630218     | 1h 1m        |
+--------------+--------------+--------------+
```
I can't actually export the model …
> Implement basic training for the new C++ implementation of object detection

- src/unity/lib/unity_sframe.cpp
- src/unity/server/registration.cpp
The macro TC_BUILD_VISUALIZATION_CLIENT should only be used for the
client (tcviz app on macOS or Linux); the C API for visualization
should work regardless as it's purely data structure transformations
and doesn't depend on any client app.
> Allow visualization server to build without client

- src/unity/python/turicreate/toolkits/object_detector/object_detector.py
It should be possible to set `confidence_threshold=0.0` and not have it silently fall back to 0.25.
> Fix object detector export parameters when set to 0

- src/image/jpeg_io.cpp
- src/unity/python/turicreate/test/test_image_type.py
- src/unity/python/turicreate/toolkits/object_detector/_sframe_loader.py
Fixes #1046. Placed resizing functionality from image_analysis to support conversion of 1-channel (Grayscale) and 4-channel (RGBA) images to 3-channel (RGB) images.
* Currently supported color spaces (and their conversions to RGB) are Grayscale, palette, RGB, and RGBA.
* PNG supports Grayscale, RGB and RGBA. ([LibPng](http://www.libpng.org/pub/png/libpng-1.2.5-manual.html))
* JPEG supports Grayscale and RGB, along with additional colorspaces such as CMYK, YCCK, and YCbCr. [LibJpeg](https://github.com/Windower/libjpeg/blob/master/libjpeg.txt) does not support conversion of YCCK or CMYK to RGB.
* Since we expect image format to be a 3-channel RGB, I added an error check for the jpeg image to be in the acceptable format. (Note: Conversion from CMYK to RGB can still happen using the resizing …
> Handle resizing of channels of input images 

- src/unity/toolkits/coreml_export/CMakeLists.txt
- src/unity/toolkits/coreml_export/mlmodel_wrapper.cpp
- src/unity/toolkits/coreml_export/mlmodel_wrapper.hpp
- src/unity/toolkits/coreml_export/neural_net_models_exporter.cpp
- src/unity/toolkits/coreml_export/neural_net_models_exporter.hpp
- src/unity/toolkits/neural_net/model_spec.cpp
- src/unity/toolkits/neural_net/model_spec.hpp
- src/unity/toolkits/object_detection/CMakeLists.txt
- src/unity/toolkits/object_detection/object_detector.cpp
- src/unity/toolkits/object_detection/object_detector.hpp
- src/unity/toolkits/object_detection/od_yolo.cpp
- src/unity/toolkits/object_detection/od_yolo.hpp
- src/unity/toolkits/recsys/models/itemcf.cpp
- test/unity/toolkits/neural_net/test_model_spec.cxx
- test/unity/toolkits/object_detection/CMakeLists.txt
- test/unity/toolkits/object_detection/test_od_yolo.cxx
(Non-maximal suppression still to be implemented)
Note that the logic for the layers appended to the trained NN layers was lifted directly from the [Python implementation](https://github.com/apple/turicreate/blob/7dbe30e53bfb784091f1aff4b93dc59d50584e4d/src/unity/python/turicreate/toolkits/object_detector/object_detector.py#L1234).
When exporting the initial model (without any training), the only differences between the C++ and Python (with NMS disabled) versions are the metadata, the randomly initialized weights, and AFAICT the `alpha`, `epsilon`, and `scale` parameters written here in the Python version are spurious, so I omitted them:
```
layers {
name: "__tc__internal__rel_wh_sp"
input: "__tc__internal__raw_rel_wh_sp"
output: "__tc__internal__rel_wh_sp"
unary {
type: EXP
alpha: 1.0 …
```
> Implement object_detector::export_to_coreml

- userguide/object_detection/export-coreml.md
This is included in our deployment code for iOS 11, but missing from iOS 12. This option is important for correct handling of input.
Fixes #1016 (!!)
> OD: Make sure setting imageCropAndScaleOption is included in example code

- build_capi.sh
It was trying to pass `--with-ios` to `./configure`, but the correct
flag is actually `--target-ios`.
> Fix iOS flag passed from build_capi.sh

- src/logger/logger.hpp
Seems that perhaps we were relying on undefined behavior, and the
behavior has changed in newer compilers. (Unclear cause.)
The result is that in debug mode, the expression
`endltype(f) == endltype(std::endl)` always returns false,
even when the modifier passed in is in fact std::endl.
As a result, in debug mode, we never flush the stream.
This fix is to ignore which modifier is being passed in, and
always flush the stream as though it's std::endl. In practice,
it's likely to be endl most of the time, so the performance hit
from flushing more often should not be too bad.
> Fix logger output in debug builds

- src/fileio/libhdfs_shim.cpp
- src/unity/server/unity_server_init.cpp
Currently, libhdfs search paths do not look for libhdfs.dylib, and several important search paths are missing.  This PR makes this process more robust.
> Improved libhdfs search paths.

- src/table_printer/table_printer.cpp
- src/table_printer/table_printer.hpp
* All types that are passed into table printer are handled.
* Logs start, header, values, and end.
* Apple-platform only; on others, this will no-op.
> Call os_log from table_printer

- src/unity/lib/visualization/boxes_and_whiskers.cpp
- src/unity/lib/visualization/categorical_heatmap.cpp
- src/unity/lib/visualization/categorical_heatmap.hpp
- src/unity/lib/visualization/columnwise_summary.cpp
- src/unity/lib/visualization/groupby.hpp
- src/unity/lib/visualization/heatmap.cpp
- src/unity/lib/visualization/heatmap.hpp
- src/unity/lib/visualization/histogram.cpp
- src/unity/lib/visualization/histogram.hpp
- src/unity/lib/visualization/item_frequency.cpp
- src/unity/lib/visualization/item_frequency.hpp
- src/unity/lib/visualization/summary_view.cpp
- src/unity/lib/visualization/summary_view.hpp
- src/unity/lib/visualization/transformation.hpp
This change picks up two commits from a branch that were conceptually
necessary for other recent changes, but somehow didn't break the
build, or fail any tests, or break anything in practice except for
issue 1248. The necessary commits were:
https://github.com/znation/turicreate/commit/616de4b641389ce7ccc4e621850996af8d82781
https://github.com/znation/turicreate/commit/3e02db92ed685414f1be25f21bf23a0b9af3d32c
Fixes #1248
TBD: what specific commit went in that broke this? It worked in the 5.1
release.
> Fix plot get_data for SFrame summary view

- src/table_printer/table_printer.cpp
The os_log subsystem should use a vendor prefix, like `com.apple`.
> Use `com.apple` prefix on os_log subsystem

- src/sframe/parallel_csv_parser.cpp
- src/util/dense_bitset.hpp
- test/sframe/sframe_csv_test.cxx
This is a long awaited feature. This PR implements support for newlines
appearing inside a string field in a CSV.
For instance, this allows the parsing of
```
user, review
a, "this is a good string"
b, "This is a
gooder string"
c, "yet another string"
```
> Support newlines in CSV Strings

- src/unity/python/turicreate/test/test_evaluation.py
- src/unity/toolkits/evaluation/metrics.cpp
This PR fixes a bug in how the precision-recall was calculated in the recommender.util.precision_recall_by_user function when multiple cutoffs were present.
> 12 12 user exclude indexing

- userguide/object_detection/data-preparation.md
```
$ python annotation_to_sframe.py
Finished parsing file /Users/kyo/projects/choose-a-payment/ML/data/eval/out.csv
Parsing completed. Parsed 66 lines in 0.051303 secs.
------------------------------------------------------
Inferred types from first 100 line(s) of file as
column_type_hints=[str,int,str,int,int,int,int]
If parsing fails due to incorrect types, you can correct
the inferred type list above and pass it to read_csv in
the column_type_hints argument
------------------------------------------------------
Finished parsing file /Users/kyo/projects/choose-a-payment/ML/data/eval/out.csv
Parsing completed. Parsed 66 lines in 0.008484 secs.
Traceback (most recent call last):
File "annotation_to_sframe.py", line 25, in <module>
sf_images = …
```
> Fix typo in data-preparation.md

- src/unity/toolkits/evaluation/CMakeLists.txt
This fixes a linker error (missing symbols) from metrics.cpp in
unity_evaluation. It seems to have been introduced by #1262.
> Fix link error in metrics.cpp

- src/flexible_type/flexible_type_spirit_parser.cpp
- src/flexible_type/flexible_type_spirit_parser.hpp
- src/flexible_type/string_escape.cpp
- src/flexible_type/string_escape.hpp
- src/flexible_type/string_parser.hpp
- src/logger/logger.cpp
- src/logger/logger.hpp
- src/sframe/csv_line_tokenizer.cpp
- src/sframe/csv_line_tokenizer.hpp
- src/sframe/parallel_csv_parser.cpp
- src/unity/lib/unity_sarray.cpp
- src/unity/lib/unity_sframe.cpp
- src/unity/python/turicreate/cython/cy_test_utils.pyx
- src/unity/python/turicreate/data_structures/sframe.py
- test/capi/capi_sframe_csv.cxx
- test/sframe/sframe_csv_test.cxx
- Allow escape_char to be optional: push a use_escape_char option all the
way through all code.
- Add csv parsing options true_values and false_values which accept a list of strings to interpret as the numeric value 1, and the numeric value 0 respectively.
- pushed through na_values to the recursive parsers so that missing values inside of dict/lists are handled correctly.
- Filled in the read_json parsing options to correctly map na_values = ["null"], true_values=["true"] and false_values=["false"]
- Better parser diagnostics on parser failure. For instance:
```
Unable to interpret ""hello"" as a integer
Parse failed at token ending at:
2,"hello"^
Successfully parsed 1 tokens:
0: 2
```
> More CSV Parsing Improvements

- src/unity/toolkits/neural_net/mps_graph_cnnmodule.mm
I'm speculating that some of the reports of NAN results we're seeing may be due to errors that we're currently ignoring. This won't fix the issue, but may improve diagnostics.
> Propagate Metal errors in object detector (instead of returning garbage data)

- scripts/make_wheel.sh
- src/unity/python/turicreate/cython/cy_flexible_type.pyx
Initial commit: Don't put import numpy behind a try/catch.
Since we're immediately going to fail anyway if numpy is missing, let's just
import it whether it'll fail or not, and let it fail with a proper stack
trace if it's going to. That should at least give us more information in CI.
> Fix Travis CI failure on assert(HAS_NUMPY)

- src/unity/lib/visualization/CMakeLists.txt
- src/unity/lib/visualization/vega_spec.cpp
- src/unity/lib/visualization/vega_spec.hpp
- src/unity/lib/visualization/vega_spec/boxes_and_whiskers.json
- src/unity/lib/visualization/vega_spec/categorical.json
- src/unity/lib/visualization/vega_spec/categorical_heatmap.json
- src/unity/lib/visualization/vega_spec/config.json
- src/unity/lib/visualization/vega_spec/heatmap.json
- src/unity/lib/visualization/vega_spec/histogram.json
- src/unity/lib/visualization/vega_spec/scatter.json
- src/unity/lib/visualization/vega_spec/summary_view.json
- src/unity/python/turicreate/visualization/show.py
* Implements a simpler plot templating system that allows for named and optional template parameters.
* Shares [Vega config](https://vega.github.io/vega/docs/config/) among all plots (except summary view).
* Fixes plot title display issues (as mentioned in #1296) and corresponding Python API docs.
> Simplify plot config and autosize

- src/unity/toolkits/object_detection/object_detector.cpp
- src/unity/toolkits/object_detection/od_yolo.cpp
For some reason, the version of clang++ in Xcode 9 gives warnings (as
error) like:
```
../src/unity/toolkits/object_detection/od_yolo.cpp:38:9: error: suggest
braces around initialization of subobject [-Werror,-Wmissing-braces]
{ 1, anchor_boxes.size(), (5 + num_classes), num_spatial });
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
{                                                     }
../src/unity/toolkits/object_detection/od_yolo.cpp:42:26: error: suggest
braces around initialization of subobject [-Werror,-Wmissing-braces]
{ 0, 2, 1, 3 });
^~~~~~~~~~
{         }
```
Not sure why later versions of Xcode don't give this warning, as it
seems to be valid and correct as far as I can tell (i.e. we should in
fact be using double braces in these places).
> Fix build in Xcode 9

- README.md
Using the Markdown exported from Travis CI, we can see (and get a link to) the latest build status on Travis.
> Include master build status in README.md

- src/capi/TuriCreate.h
- src/capi/impl/capi_visualization.cpp
- src/unity/lib/visualization/plot.cpp
- src/unity/lib/visualization/plot.hpp
- test/capi/capi_visualization.cxx
* Creates a enum to describe plot variations in C API.
* Passes the enum into C++ API to allow the logic to determine the spec from the variations.
* Uses the plot variation enum to determine Vega spec (Not yet implemented in this commit).
This change will eventually allow for small/medium/large and light/dark variations of each plot.
Depends on #1308.
> Allow plots to vary in size/color/etc.

- src/capi/TuriCreate.h
- src/unity/lib/visualization/CMakeLists.txt
- src/unity/lib/visualization/dark_mode.cpp
- src/unity/lib/visualization/dark_mode.hpp
- src/unity/lib/visualization/plot.cpp
- src/unity/lib/visualization/plot.hpp
- src/unity/lib/visualization/vega_spec.cpp
- src/unity/lib/visualization/vega_spec.hpp
- src/unity/lib/visualization/vega_spec/config.json
- src/unity/python/turicreate/visualization/_plot.py
Completed in this change:
* C and C++ API for retrieving and showing dark mode Vega spec for a Plot object
* macOS support
Not yet implemented (will come in future changes):
* Python API for retrieving and showing dark mode Vega spec for a Plot object
* Linux support (TBD: can this be done w.r.t. popular desktop
environments or via a standard?)
* Proper UX support for dark mode (i.e. the native app changes
background color and switches appropriately in real time).
Depends on #1309.
> Implement dark mode plot API

- src/unity/lib/visualization/vega_spec.cpp
- src/unity/lib/visualization/vega_spec/boxes_and_whiskers.json
- src/unity/lib/visualization/vega_spec/categorical.json
- src/unity/lib/visualization/vega_spec/categorical_heatmap.json
- src/unity/lib/visualization/vega_spec/heatmap.json
- src/unity/lib/visualization/vega_spec/histogram.json
- src/unity/lib/visualization/vega_spec/scatter.json
Fixes the various title display issues across the different plots. Now
the behavior is:
* Default plot titles (unspecified) are plot-specific generated strings.
* None/null plot titles don't take up any space (the plot expands to
fill the height).
* Empty string titles explicitly take up space but don't display anything.
* User-provided string titles work as expected.
Depends on #1318
> Fix empty space on null plot title

- src/unity/lib/visualization/item_frequency.cpp
- src/unity/lib/visualization/vega_spec.cpp
- src/unity/lib/visualization/vega_spec.hpp
- src/unity/lib/visualization/vega_spec/categorical.json
* Count null values in an "Other (missing)" category instead of
discarding them.
* Limit default views to 12 categories (still 10 in Summary view, was
200 in SArray views).
* When the max categories is hit, combine all remaining counts in an "Other
(n labels combined)" label.
Depends on #1324
> Categorical histogram improvements

- src/unity/lib/visualization/histogram.cpp
- src/unity/lib/visualization/vega_spec/histogram.json
Previously, all null values were ignored. With this change, if there are
any missing values (true None, not NaN), they get counted separately in
a categorical bin that is separated from the X axis.
This change does not yet account for NaN/inf values. Those are still
being ignored.
Depends on #1324
> Handle null values in numeric histogram

- test/unity/toolkits/CMakeLists.txt
- test/unity/toolkits/coreml_export/CMakeLists.txt
- test/unity/toolkits/coreml_export/test_neural_nets_model_exporter.cxx
- test/unity/toolkits/object_detection/test_object_detector.cxx
Bleargh, in some Linux configurations the new test was failing to compile because test_object_detector.cxx wasn't being compiled with the magic incantations to avoid errors in protobuf headers.
Rather than allow this weirdness to spread to test_object_detector.cxx, I just moved the test to a new file, which makes some sense anyway since the code under test is actually defined in unity_coreml_export, not unity_object_detection.
> Move test_object_detector_export_coreml_with_nms to its own file with the appropriate protobuf workarounds

- test/flexible_type/new_flexible_type_test.cxx
This new warning in Xcode 10.2 beta causes an error in our build (since
we have `-Werror` on), but the thing we're trying to test only makes
sense in the presence of compilers that don't have this error/warning.
So for now, let's just suppress the warning in this test.
> Add clang warning suppression on self assignment

- src/unity/lib/visualization/plot.cpp
- src/unity/lib/visualization/plot.hpp
- src/unity/lib/visualization/vega_spec/boxes_and_whiskers.json
- src/unity/lib/visualization/vega_spec/categorical.json
- src/unity/lib/visualization/vega_spec/categorical_heatmap.json
- src/unity/lib/visualization/vega_spec/heatmap.json
- src/unity/lib/visualization/vega_spec/histogram.json
- src/unity/lib/visualization/vega_spec/scatter.json
- src/unity/lib/visualization/vega_spec/summary_view.json
- src/unity/python/turicreate/visualization/_plot.py
This change adds C++ API to include (streaming) data in the Vega spec
returned by the Plot.
This was previously implemented only in Python. Implementing in C++ is
both more efficient, and will allow API consumers beneath Python to have
this functionality.
> Move Vega spec including data down to C++

- src/unity/lib/visualization/show.cpp
When the axes are flipped from what the user intended (because we only
have a vertical-layout box plot currently), we also need to flip the
axis titles.
> Fix axis title bug in Box & Whisker plot

- src/external/aws-sdk-cpp/CMakeLists.txt
Current master doesn't compile in release mode on clang edge.
> Updated a compiler flag to get external lib to compile under clang edge.

- src/unity/toolkits/neural_net/image_augmentation.cpp
- src/unity/toolkits/neural_net/image_augmentation.hpp
- src/unity/toolkits/neural_net/mps_image_augmentation.mm
- src/unity/toolkits/object_detection/CMakeLists.txt
- src/unity/toolkits/object_detection/object_detector.cpp
- src/unity/toolkits/object_detection/object_detector.hpp
- src/unity/toolkits/object_detection/od_data_iterator.cpp
- src/unity/toolkits/object_detection/od_data_iterator.hpp
- src/unity/toolkits/object_detection/od_evaluation.cpp
- src/unity/toolkits/object_detection/od_evaluation.hpp
- src/unity/toolkits/object_detection/od_yolo.cpp
- src/unity/toolkits/object_detection/od_yolo.hpp
- test/unity/toolkits/neural_net/test_image_augmentation.cxx
- test/unity/toolkits/neural_net/test_mps_image_augmentation.cxx
- test/unity/toolkits/object_detection/CMakeLists.txt
- test/unity/toolkits/object_detection/test_object_detector.cxx
- test/unity/toolkits/object_detection/test_od_data_iterator.cxx
- test/unity/toolkits/object_detection/test_od_evaluation.cxx
- test/unity/toolkits/object_detection/test_od_yolo.cxx
Using the Python bindings, for the following script (for a partially trained model):
```
data = tc.SFrame('breakfast-data.sframe')
m = tc.extensions.object_detector()
m.train(data, 'annotation', 'image', {'mlmodel_path':'/Users/jong/Desktop/darknet.mlmodel', 'max_iterations' : 1000})
print(m.evaluate(data))
```
I get
```
Using GPU to create model (AMD Radeon Pro 560)
Setting 'batch_size' to 32
+--------------+--------------+--------------+
| Iteration    | Loss         | Elapsed Time |
+--------------+--------------+--------------+
| 1            | 7.46523      | 3.14s        |
[...]
| 1000         | 2.98155      | 17m 27s      |
+--------------+--------------+--------------+
{'average_precision_50': {'Coffee': 0.3338097333908081, 'Croissant': 0.5798972845077515, …
```
> Implement object_detector::evaluate (C-API)

- src/external/aws-sdk-cpp/CMakeLists.txt
Fixes #1383
This adopts the CMake pattern for checking whether a compiler flag
exists before attempting to use it. The assumption here is that:
* If clang has this flag, we want to use it to suppress the warnings.
* If clang does not have this flag, there will be no warnings to
suppress.
> Check new warning flag before using

- src/capi/CMakeLists.txt
- src/vega_renderer/CMakeLists.txt
Fixes #1384
The initial commit of `src/vega_renderer/CMakeLists.txt` was relying on
behavior new to CMake 3.12. Since we support older versions of CMake
in the build, we should not rely on it.
> Fix target linking syntax in older CMake

- test/vega_renderer/CMakeLists.txt
- Copy the proper test files to vega_render_tests, so they can properly run
> Copy proper test files to vega_render_tests

- src/unity/python/turicreate/util/__init__.py
This fixed the issue noted in the related ticket; seems the exception type is just not as expected.
> Handle exception thrown when calling `nvidia-smi` when no GPU is installed

- src/unity/python/turicreate/toolkits/_mps_utils.py
- src/unity/python/turicreate/toolkits/activity_classifier/_mps_model_architecture.py
- src/unity/toolkits/neural_net/compute_context.hpp
- src/unity/toolkits/neural_net/model_backend.hpp
- src/unity/toolkits/neural_net/mps_cnnmodule.h
- src/unity/toolkits/neural_net/mps_cnnmodule.mm
- src/unity/toolkits/neural_net/mps_compute_context.hpp
- src/unity/toolkits/neural_net/mps_compute_context.mm
- src/unity/toolkits/neural_net/mps_graph_cnnmodule.h
- src/unity/toolkits/neural_net/mps_graph_cnnmodule.mm
- src/unity/toolkits/neural_net/mps_graph_trainer.mm
- src/unity/toolkits/neural_net/mps_trainer.h
- src/unity/toolkits/neural_net/mps_trainer.mm
- src/unity/toolkits/neural_net/mps_utils.h
- src/unity/toolkits/neural_net/mps_utils.mm
- src/unity/toolkits/object_detection/object_detector.cpp
- src/unity/toolkits/object_detection/object_detector.hpp
- test/unity/toolkits/object_detection/test_object_detector.cxx
This is the first step towards creating a C++ implementation of the AC toolkit, to parallel the new OD implementation. I had to generalize the `neural_net::cnn_module` interface I had created for OD, since AC requires an additional input (weights) for each training batch, and the training model returns both the forward output and the loss. To this end, I made the interface more like the MPS and CoreML interfaces, in that they take named inputs and return named outputs. Along the way, I renamed `cnn_module` to `model_backend`, since "CNN" was always a bit of a misnomer.
Note, this constitutes a dramatic narrowing of the interface for the "low-level" MPS backend. AFAICT much of this interface surface supported debugging and testing during the original development, but should not generally …
> Re-factor Activity Classifier MPS backend to adopt same backend interface as Object Detection

- CMakeLists.txt
- configure
Prior to this PR, we claimed to be compatible with:
* CMake 2.8.3 (checked in `CMakeLists.txt`)
* CMake 3.5.0 (printed by `./configure`).
* CMake 3.5.1 (actually checked by `./configure`).
Since we provide 3.9.3 in the repo, and rarely test with anything below
that, it doesn't really make sense to claim (wildly and inconsistently)
that we support any particular versions below that. This PR updates all
claims to match what we actually build & test with most commonly, which
is 3.9.3.
For existing users of various CMake versions:
* Below 3.9.3, builds will now start using the CMake provided in deps,
which will ensure consistent builds with what we're testing in CI.
* At or above 3.9.3, this change will have no effect on existing users.
> Make CMake compat requirements consistent

- CMakeLists.txt
- configure
PR #1388 went a bit too far in bumping the min version of CMake to 3.9.3.
Our Travis CI build uses 3.9.2, so since that PR went in, we have been
building CMake from source in Travis builds.
With this PR, builds should succeed on Travis without needing to build
CMake from source.
> Make 3.9.2 the required version of CMake

- src/fileio/fs_utils.cpp
S3 has no directories, hence create_directory always succeeds when used on S3 filesystems.
create_directory_or_throw should therefore not check file status when S3 is used.
> Fixes S3 write path for SFrames

- src/sframe/sarray_reader.hpp
- src/sframe/sarray_reader_buffer.hpp
- src/sframe/sarray_v2_block_manager.cpp
- src/sframe/sarray_v2_block_manager.hpp
- src/sframe/sframe_reader.hpp
- src/unity/lib/gl_sframe.cpp
- src/unity/lib/gl_sframe.hpp
- src/unity/lib/unity_sframe.cpp
- src/unity/lib/unity_sframe.hpp
- test/optimization/optimization_interface_test.cxx
- test/unity/gl_sframe.cxx
gl_sframe had a cache invalidation bug that caused old data to be referenced by iterators that were not cleared up properly after sort.  This PR cleans up this layer as well as some messy code in the sarray reader and file handle cache layers.
> gl_sframe cache invalidation bug

- deps/src/boost_1_68_0/tools/build/src/engine/jamgram.c
- deps/src/boost_1_68_0/tools/build/src/engine/jamgram.h
This is done by regenerating parser and lexers using byacc instead of
bison.
> Eliminates GPL-adjacent code from boost parsers.

- configure
Installing cmake as an OSX app doesn't always install the command line utilities into the path.  This checks the default cmake app installation for cmake as well.
> Added in check for cmake install as an osx app.

- src/platform/parallel/execute_task_in_native_thread.hpp
- src/unity/lib/visualization/process_wrapper.cpp
Our minimum GCC version to build is currently 5.4. With this PR, we can build on GCC 4.8, which comes out of the box in Ubuntu 14.04.
> Enable building on GCC 4.8

- CMakeLists.txt
Turns out the default one was REALLY old.
> Updated default compiler flags to enable newer architectures.

- README.md
Currently, our build status badge links to whatever happens to be the "current" build, which is usually a random pull request build. This commit changes that to link to the branch overview page (which lists the default branch, master, separately and first). I couldn't find a better direct link for just the master branch.
> Link build status badge to branch overview

- src/unity/toolkits/drawing_recognition/data_preparation.cpp
This is a temporary patch that will be fixed completely by #1449.
> Fixed a build error because of type mismatch between `int` and `size_t`

- src/unity/python/turicreate/test/test_coreml_export.py
This will suppress the failure in #1332. When that issue is fixed, we
should remove the xfail.
> Temporarily mark CoreML export test as xfail

- src/unity/python/turicreate/toolkits/_mps_utils.py
- src/unity/toolkits/activity_classification/activity_classifier.cpp
- src/unity/toolkits/activity_classification/activity_classifier.hpp
- src/unity/toolkits/coreml_export/neural_net_models_exporter.cpp
- src/unity/toolkits/coreml_export/neural_net_models_exporter.hpp
- src/unity/toolkits/neural_net/model_spec.cpp
- src/unity/toolkits/neural_net/mps_layers.mm
- src/unity/toolkits/neural_net/mps_trainer.h
- src/unity/toolkits/neural_net/mps_trainer.mm
- src/unity/toolkits/neural_net/mps_utils.h
- src/unity/toolkits/neural_net/mps_utils.mm
The Python toolkit was assuming NHWC at the interface with TCMPS, but we should adopt NCHW for consistency with the Core ML representation. Note that this didn't matter before, since on the weights loaded into TCMPS were random, and the weights exported from TCMPS weren't being consumed. Now they're being exported further to the .mlmodel file.
> Implement Core ML export for C++ activity classifier

- src/unity/toolkits/drawing_classifier/data_preparation.cpp
Looks like the compiler was not happy with m_x and m_y staying uninitialized. In theory, it could happen that we make a point with m_x and no m_y or vice versa, but in practice, we would throw an error if any of the "x" or "y" coordinates was missing.
> Fix build errors (warnings)

- src/unity/lib/visualization/batch_size.cpp
> Prevent divide-by-zero crash in .show

- src/unity/python/setup.py
The version of `coremltools` we use also requires `"six >= 1.10.0"`
Finishes the fix for #1417.
> Added six as a depedency to setup.py

- src/unity/lib/visualization/heatmap.cpp
- src/unity/lib/visualization/vega_spec/heatmap.json
- src/unity/lib/visualization/vega_spec/scatter.json
Fixes #1194 by setting `zero: false` and using padding on scatter plot.
Also fixes heat map Y axis labels -- they were appearing relative to
Y-min, not absolute. No issue appears to be tracking this however.
> Fix scatter plot and heat map axes

- src/unity/python/turicreate/data_structures/sarray.py
The method is actually called `pixel_array_to_image`.
> Fix method name in error message

- src/util/bitops.hpp
- test/util/CMakeLists.txt
- test/util/bitops.cxx
Turns out uint64_t(1) << 64 isn't actually well defined.
> Fix for bit mask to make corner case more portable.

- src/unity/python/turicreate/test/test_evaluation.py
- src/unity/toolkits/evaluation/evaluation_interface-inl.hpp
- userguide/evaluation/classification.md
As per the conversation with @hoytak , we want to return the precision and not the accuracy when `average=None` is passed into `tc.evaluation.accuracy`.
As of this change, when the input is:
```
import turicreate as tc 
y    = tc.SArray(["cat", "dog", "foosa", "cat"])
yhat = tc.SArray(["cat", "dog", "cat", "dog"])
print(tc.evaluation.accuracy(y, yhat, average = "micro"))
print(tc.evaluation.accuracy(y, yhat, average = "macro"))
print(tc.evaluation.accuracy(y, yhat, average = None))
```
The output is:
```
0.5
0.6666666666666666
{'foosa': None, 'dog': 0.5, 'cat': 0.5}
```
> Fixes #1407

- src/unity/python/turicreate/_scripts/_pylambda_worker.py
- src/unity/python/turicreate/test/test_lambda.py
Added environment variables in the lambda workers to try to prevent multithreaded execution by common frameworks on lambda workers.
> Prevent multithreaded execution within lambda workers. 

- scripts/requirements.txt
- src/unity/python/setup.py
The latest versions of [numba](https://pypi.org/project/numba/#files) and [llvmlite](https://pypi.org/project/llvmlite/#files) now both have wheels for Python 3.5. So I think it's safe to remove these pins.
> numba and llvmlite now have Python 3.5 wheels on PyPI

- src/unity/python/turicreate/data_structures/sarray_builder.py
If `dtype` is `type(None)`, `self._builder.init(num_segments, history_size, dtype)` fails with error message `RuntimeError: Must specify a valid type.`. So I've removed that case.
> SArray Builder: doc string fix + minor clean up

- src/unity/toolkits/supervised_learning/supervised_learning.cpp
Linear Regression accepts 'int' and 'float' target values. Previously `check_target_column_type()` which checks the type of target values was called on the validation set. Validation set is only created for a dataset size 100 or larger. For cases when data with fewer than 100 examples was given, the check was not applied and target values of type string were being accepted and handled incorrectly. 
The check for target values type is now applied on the target column of the data passed in. Fixes https://github.com/apple/turicreate/issues/1298
> Check Linear Regression target column data type

- src/unity/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py
> API docs for Drawing Classifier evaluate have a tab indent now

- userguide/SUMMARY.md
Earlier, the Advanced Usage section was not accessible to users.
> Added Advanced Usage section to Userguide Summary page

- src/unity/python/turicreate/test/test_audio_functionality.py
- src/unity/python/turicreate/toolkits/audio_analysis/audio_analysis.py
- src/unity/python/turicreate/toolkits/sound_classifier/__init__.py
- src/unity/python/turicreate/toolkits/sound_classifier/_audio_feature_extractor.py
- src/unity/python/turicreate/toolkits/sound_classifier/sound_classifier.py
- userguide/sound_classifier/advanced-usage.md
Fixes #1601
- Add tc.sound_classifier.get_deep_features.
- Change sound classifier (create & predict) to use get_deep_features.
- Allow sound classifier (create & predict) to use deep features directly.
-----------------------------------------
- Use SArrayBuilder to construct deep features
- Logging: print header info only if printing progress info.
- Any function which could result in deep feature extraction should have `verbose` flag.
- Allow predict to do parameter checking. Rather than doing it, not as well, in a bunch of other
places that just call predict anyways.
- classify/evaluate/predict_topk should allow SFrame or dict input, in addition to SArray.
-----------------------------------------
- Unit tests: test deep feature reuse.
- Unit tests: copy data rather than regenerate …
> Sound Classifier: Allow Reusing Deep Features

- src/unity/python/doc/source/turicreate.toolkits.image_classifier.rst
Fixes https://github.com/apple/turicreate/issues/1645
The new docs will need to be [pushed live](https://apple.github.io/turicreate/docs/api/index.html) once they're built.
> Add image_classifier.annotate method to pydocs

- src/unity/python/turicreate/data_structures/sarray.py
- src/unity/python/turicreate/test/test_sarray.py
- src/unity/python/turicreate/test/test_sframe.py
> Allow SArray to be created with a map or filter type -- Python 3

- src/flexible_type/flexible_type_spirit_parser.cpp
- src/flexible_type/flexible_type_spirit_parser.hpp
- src/flexible_type/string_parser.hpp
- src/sframe/csv_line_tokenizer.cpp
- src/sframe/csv_line_tokenizer.hpp
- src/unity/lib/unity_sarray.cpp
- src/unity/lib/unity_sframe.cpp
- src/unity/python/turicreate/data_structures/sframe.py
- src/unity/python/turicreate/test/test_json.py
- test/sframe/sframe_csv_test.cxx
More generally, implements a hidden CSV parsing option called
_only_raw_string_substitutions which forces true,false,na substitutions
to compare *only* on the unprocessed buffer before dequoting, escaping, etc.
This is considered a private option for now since I am unsure how to
document it for public consumption.
Fixes #1695
> Correct handling of quoted "true", "false" values in JSON

- src/unity/toolkits/object_detection/object_detector.cpp
- src/unity/toolkits/object_detection/object_detector.hpp
- test/unity/toolkits/object_detection/test_object_detector.cxx
OD data iterators for evaluation must use class labels from training
OD evaluation should return values using flexible_type, not variant_type
OD training was writing incorrect values for validation metrics
> Fixes for bugs in C-API object detector evaluation

- src/unity/python/turicreate/test/test_audio_functionality.py
Fixes #1725
Much to my surprise `unittest.TestCase.assertAlmostEqual` is not intended to work for iterable inputs. However that method returns immediately if the two inputs are equal and that does work for iterable inputs. So if you have two iterable inputs are usually equal but occasionally off by a very small amount, you get intermittent failures.
> Fix intermittent python test failure

- src/capi/impl/capi_flexible_type.cpp
Currently, getting integers and doubles requires the types to match exactly.  This PR allows integers or doubles to be cast to the other type if it can be done exactly.
> Changed C-API getters of flexible type to be better with numeric types.

- src/unity/lib/unity_sframe.cpp
- src/unity/python/turicreate/test/test_sarray.py
- src/unity/python/turicreate/test/test_sarray_sketch.py
- src/unity/python/turicreate/test/test_sframe.py
Without this change, calling `tc.SFrame.read_csv` with `quote_char=None` has no affect. The default value of `"` gets set in the C++ layer. 
This change is necessary to read non-multi line CSV files which have unmatched quotation marks.
> Read CSV: quote_char value of None should be passed to C++ layer

- scripts/requirements.txt
- src/external/coremltools_wrap/coremltools/docs_requirements.txt
- src/external/coremltools_wrap/coremltools/mlmodel/Requirements.txt
- src/unity/python/doc/Makefile
Turns out we (apparently) aren't using it anywhere. The only place it
might be used is by sphinx, in the optional `make jinja2` for sphinx
docs, but I don't think we normally run this as part of our
documentation generation process.
> Remove jinja2 dependency

- src/unity/toolkits/evaluation/metrics.cpp
The new evaluation code was always passing full probability vectors, even for binary-class evaluators that expected a single probability. It's simpler and safer just to use the multi-class versions at this point, which is what the supervised_learning toolkit does anyway
> Fix assertion error when evaluating C-API activity classifier trained with only two labels

- scripts/run_cpp_tests.py
Otherwise it contains a `\n` and breaks.
> Strip docker image name

- CODE_OF_CONDUCT.md
- README.md
Based on the latest version of the [Contributor Covenant](https://www.contributor-covenant.org).
The Code of Conduct is also linked to from the project README.md.
> Adds Code of Conduct for Turi Create.

- .gitlab-ci.yml
This makes it easier to consume them.
> Collect all Gitlab CI artifacts into one job

- LINUX_INSTALL.md
- README.md
With Docker-based builds, we can now support all the way back to GLIBC 2.10.
> Clarify runtime requirements and GLIBC version

- src/image/CMakeLists.txt
- src/image/image_type.cpp
- src/image/image_type.hpp
This will be useful for the One Shot Object Detection functionality when we want to construct a `flex_image` from Boost GIL Image Types.
Only fixes #1828
> flex_image constructor from Boost GIL Image Types

- src/unity/python/turicreate/test/test_coreml_export.py
- src/unity/toolkits/coreml_export/xgboost_exporter.cpp
Fixes #1831
Reverts the changes in `xgboost_exporter.cpp` from #1127. That appeared
to cause wrong predictions in CoreML for some exported classifiers.
> Fix CoreML export for tree classifiers

- src/flexible_type/flexible_type.hpp
Instead of throwing in debug and crashing in release, let's always
throw. That way we won't take down the user's process when we are called
through the C or C++ API.
Fixes #1835
> Always throw an exception on bad type conversion

- src/unity/toolkits/activity_classification/activity_classifier.cpp
- src/unity/toolkits/activity_classification/activity_classifier.hpp
The accuracy and loss marginally drops after the last iteration because during training the accuracy is calculated "per window" while after training is done, it is calculated using "per row".
> Fixing updating evaluation metrics after train in C-API Activity Classifier 

- scripts/install_python_toolchain.sh
Turns out there’s a weird issue with virtualenv that, when given a
relative path, actually resolves the rest of it to
include the `/Volumes/Macintosh HD` with the space in it.  the fix
is to give it an absolute path on setup.
> Workaround for virtualenv issue.

- src/unity/CMakeLists.txt
- src/unity/python/turicreate/CMakeLists.txt
The big CMake refactor that went in recently seems to have broken
the build for non-Python builds (./configure --no-python). The problem
is that unity_shared now only builds in the python directory (which
makes sense, since it's only used in Python), but the extensions all
depended on it and all were expected to build even without Python.
The fix is to move the `unity_shared` target back up from
`src/unity/python/turicreate` into `src/unity`. Now it builds with
non-Python builds again.
> Fix broken build with `--no-python`

- test/annotation/utils_tests.cxx
The use of the C++ featurizer API will only compile on Apple platforms,
it seems. The test execution was scoped to `ifdef __APPLE__` but probably
the definition of the tests should be as well.
Otherwise we get:
```
../test/annotation/utils_tests.cxx: In member function ‘void utils_test::test_featurize_images()’:
../test/annotation/utils_tests.cxx:41:9: error: ‘featurize_images’ is not a member of ‘turi::annotate’
turi::annotate::featurize_images(image_gl_sarray);
^
../test/annotation/utils_tests.cxx: In member function ‘void utils_test::test_most_similar_items()’:
../test/annotation/utils_tests.cxx:71:9: error: ‘featurize_images’ is not a member of ‘turi::annotate’
turi::annotate::featurize_images(image_gl_sarray);
^
```
> Fix linux-only test build break

- src/unity/toolkits/evaluation/unity_evaluation.cpp
I must have "cleaned up" the C++ function signature before pushing, without adjusting the C-API registration to match. And the unit tests only test the C++ level.
> C-API bindings for new "compute_classifier_metrics" functions had the arguments in the wrong order, sigh

- src/unity/python/turicreate/toolkits/image_classifier/_annotate.py
Once again, we are importing mxnet on turicreate import. Seems the place
it's being imported is not even used (at all). Removing it.
We have a unit test for this, but it's flaky due to some lambda worker
issues, so it's not running at the moment.
> Fix mxnet being imported on turicreate import

- src/unity/toolkits/neural_net/mps_cnnmodule.h
- src/unity/toolkits/neural_net/mps_cnnmodule.mm
- src/unity/toolkits/neural_net/mps_command_queue.hpp
- src/unity/toolkits/neural_net/mps_compute_context.hpp
- src/unity/toolkits/neural_net/mps_compute_context.mm
- src/unity/toolkits/neural_net/mps_graph_cnnmodule.h
- src/unity/toolkits/neural_net/mps_graph_cnnmodule.mm
- src/unity/toolkits/neural_net/mps_trainer.mm
- Facititates better dependency injection for activity_classifier and object_detector
- Use MTLCommandQueue instead of MTLDevice, since the former includes the latter anyway
> Allow mps_compute_context to wrap an arbitrary MTLCommandQueue

- src/unity/python/turicreate/toolkits/_mps_utils.py
- src/unity/toolkits/activity_classification/activity_classifier.cpp
- src/unity/toolkits/activity_classification/activity_classifier.hpp
- src/unity/toolkits/neural_net/float_array.cpp
- src/unity/toolkits/neural_net/float_array.hpp
This functionality is not wired into turicreate.load_model() yet, since the Python toolkit is still the default. Eventually, we'll need to wire in two paths there, one for loading models saved by the original Python CustomModel implementation, and one for loading models saved from C++. For now, this code should aid in developing the C++ toolkit by comparing the behavior of a model trained from Python, loaded into each implementation.
Fixes #1710 
For now, loading a model saved from Python as `ac.model`:
```
m = tc.extensions.activity_classifier()
m.import_from_custom_model(tc._connect.main.get_unity().load_model('ac.model')['side_data'], 2)
```
Saving a model:
```
m = tc.extensions.activity_classifier()
m.train(...)
class Wrapper:
def …
```
> Implement model save/load for C++ activity classifier

- BUILD.md
* Clarifies required compiler toolchain minimum versions.
* Adds some dependencies that aren't installed by default on some Linux
distributions (but are required).
Fixes #1669
> Update Linux build requirements

- test/annotation/CMakeLists.txt
- test/annotation/utils_tests.cxx
The fix in 09802508b4118b82fd1426f28227c0217092168b
was not quite right -- this test still fails, now with:
```
Test setup error: test tree is empty
```
This commit fixes the issue by skipping building that test entirely when
not on an Apple platform.
> Fix utils_tests.cxxtest failure on Linux

- src/unity/python/turicreate/data_structures/image.py
- src/unity/python/turicreate/data_structures/sframe.py
- src/unity/python/turicreate/test/test_image_classifier.py
- src/unity/python/turicreate/toolkits/image_classifier/_evaluation.py
- src/unity/python/turicreate/toolkits/image_classifier/image_classifier.py
- src/unity/python/turicreate/visualization/_plot.py
Fixes #1866
* Use `list()` to get the same behavior from filter on 2 & 3
* Use `six.iteritems()` to get `iteritems()` in 2 and `items()` in 3
* Removes roc_curve and confusion_matrix from the serialized data (it
was inadvertently added in #1891, and causes serialization errors)
> Fix evaluate().explore() in Python 3

- src/visualization/CMakeLists.txt
- src/visualization/Turi Create Visualization/src/CustomWebKitView.swift
Fixes #1803
* In the key handler code, always return the value from the super class
(default handler), unless the key combination pressed is Cmd+/Cmd-.
* Adds CustomWebKitView to the CMake build tracking (fixes incremental
build of tcviz app when this file is changed).
> Fix key press handler in tcviz app

- src/unity/python/turicreate/toolkits/image_classifier/_evaluation.py
There was a metric coming in as `np.float32`, which is not JSON
serializable for some reason. Converting it to a regular float fixes it.
Fixes #1975
> Fix JSON serialization for DC evaluate.explore

- src/unity/python/turicreate/test/test_drawing_classifier.py
> Temporarily mark drawing classifier tests as xfail

- src/unity/python/turicreate/toolkits/image_classifier/_evaluation.py
This is an important line of code. It was accidentally deleted in #1976.
> Put back accidentally-deleted line

- src/unity/python/turicreate/toolkits/object_detector/object_detector.py
- src/unity/python/turicreate/toolkits/one_shot_object_detector/one_shot_object_detector.py
```
[[model.evaluate(data,"label")
Predicting 3/3
Out[10]: 
{'average_precision_50': {'[{"coordinates":{"y":158.92, "x":171.362, "height":217.371, "width":258.216}, "label":"Waffle"}]': 0.0,
'[{"coordinates":{"y":194.416, "x":206.98, "height":211.006, "width":386.04}, "label":"Waffle"}]': 0.0,
'[{"coordinates":{"y":222.581, "x":166.935, "height":154.399, "width":164.956}, "label":"Waffle"}]': 0.0},
'mean_average_precision_50': 0.0}]]
```
> Adding export_coreml and fixed evaluate for One Shot Object Detector

- src/unity/python/turicreate/toolkits/one_shot_object_detector/util/_augmentation.py
- src/unity/toolkits/object_detection/one_shot_object_detection/one_shot_object_detector.cpp
This will give the user some feedback while augmentation is happening.
There is still quite a delay (30s to 1m in debug) before the table even
shows, which I am not sure how to account for, but it's a lot better
than without any table printing.
Fixes #2019
> Add progress printing for one-shot augmentation

- src/core/data/flexible_type/flexible_type.hpp
The flexible_type assert statements cause a 50% slowdown for numerical flexible type operations, as well as a 10-30% slowdown on many other operations such as groupby and sarray ops.  We should move these asserts to debug-only.
> Moved flexible type asserts to debug only

- src/core/data/flexible_type/flexible_type_spirit_parser.cpp
- src/core/data/flexible_type/flexible_type_spirit_parser.hpp
- test/sframe/sframe_csv_test.cxx
The lost lasting issue is that there doesn't seem to be an easy way to
disble the skip parser in boost spirit. A hack is to use qi::eoi as the
skip parser, but that is not ideal; under certain circumstances when
the parser calls the skip parser at the end of the line, this can cause a hang
since the eoi parser does not consume any characters.
What seems to work is to use !eps as the parser. eps just returns true.
!eps thus returns false. And that works to fully disable the skip
parser.
> Fixes a hang in CSV parsing when parsing a token of a single '['

- BUILD.md
- src/core/storage/query_engine/planning/optimizations/source_transforms.hpp
- test/capi/capi_sarray.cxx
Big thanks to @hoytak and @ylow for helping me fixing this bug.
[start_val, ....   end_val]
^                      ^
begin_idx.       end_idx
The is issue is caused by the query optimizer will treat two different sequences as the same by only using begin and end index to identify sequence identity. All binary operations are affected by this.
As @ylow points out, head value of a sequence should also be involved to identify whether two sequence are the same and should be fused during the optimization phase.
> fix for range sequence operation bug

- src/python/turicreate/data_structures/sarray.py
- src/python/turicreate/data_structures/sframe.py
- src/python/turicreate/test/test_sarray.py
- src/python/turicreate/test/test_sframe.py
bug fix for issue #2088
this pr also supports generator types; before any type inference and passing data to the cpp proxy, transform the data from generator/map/filter to a valid list first.
This issue is caused by a patch for #1716. The internal test is triggered.
> bug fix for sarray constructor not accepting map/filter if dtype is explicitly set

- src/python/turicreate/toolkits/object_detector/util/_visualization.py
Format the exception ToolkitError message at [line](https://github.com/apple/turicreate/blob/44556085d01eef01a1188eb13f64487c5ed3b4e1/src/python/turicreate/toolkits/object_detector/util/_visualization.py#L155).
Fixes #2094
> Fix OD viz exception error message

- src/toolkits/object_detection/object_detector.cpp
- test/unity/toolkits/object_detection/test_object_detector.cxx
Adding the functionality to split provided dataset into validation in C-API Object Detector. A test is also added to check its functionality.
> Automatically splitting data into train and validation for C-API Object Detector

- src/python/turicreate/test/test_sframe_builder.py
- Updated the testing syntax for Python 2.7 and 3.6 Build Breaks in master.
> Updated syntax for Python 2.7 and 3.6 Build Breaks

- BUILD.md
Removed a couple of references to the no longer existing `unity` directory in our build readme.
> Update BUILD.md to reflect code restructuring

- scripts/Dockerfile-Ubuntu-10.04
- scripts/Dockerfile-Ubuntu-18.04
- scripts/get_docker_image.sh
* Adds Python 3.7 to the Ubuntu 10.04 and 18.04 images
* Adds libffi (installed from source) and pkg-config to the 10.04 image (needed to build Python 3.7 from source)
* Switches some `CMD`s to `RUN` since that seems to have closer to the intended behavior.
* Drops `apt-get clean` since apparently the official Ubuntu images (upon which ours are based) do this automatically: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
> Add Python 3.7 to docker images

- src/toolkits/activity_classification/ac_data_iterator.cpp
- src/toolkits/activity_classification/ac_data_iterator.hpp
- src/toolkits/activity_classification/activity_classifier.cpp
- src/toolkits/activity_classification/activity_classifier.hpp
In activity classification, say prediction window is 100 and lstm sequence length is 20, so the batch row is 20 x 100 = 2000 and there are 32 batch rows in a batch (if the batch size is 32). So per batch we have 32 x 100 x 20 x #features for features and 32 x 20 labels (majority voting done in every prediction window). Originally (without data augmentation), we would preprocess it in chunks of 100 x 20 x #features features and 20 labels. Now, the number of rows (=batch size) were picked up and passed as a batch by the iterator. So here in every epoch we were going to pick up the same chunked up data 0-1999, 2000-3999, 4000-5999 and so on.
The goal of data augmentation was to have different prediction windows in each iteration. To implement data augmentation, we have chunked up data to …
> Data Augmentation for C-API activity classifier

- deps/cmake/ExternalProjectLibCurl.cmake
On newer versions of linux, the newest version of curl needs some additional flags
to get it to compile.
> Add --without-libidn2 flag to curl

- src/visualization/vega_renderer/JSCanvas.h
- src/visualization/vega_renderer/JSCanvas.m
- test/vega_renderer/CMakeLists.txt
- test/vega_renderer/base_fixture.mm
- test/vega_renderer/examples/turicreate/simple_themed_bar_chart.vl.json
- test/vega_renderer/turicreate_example_tests.cxx
Implements the missing `fillRect(x, y, w, h)` method in `JSCanvas`. Also, fix a few import paths.
> Add support for fillRect() to JSCanvas

- src/ml/neural_net/TCMPSImageAugmenting.h
- src/ml/neural_net/TCMPSImageAugmenting.m
- src/ml/neural_net/image_augmentation.hpp
- src/ml/neural_net/mps_image_augmentation.hpp
- src/ml/neural_net/mps_image_augmentation.mm
- src/ml/neural_net/weight_init.cpp
- src/ml/neural_net/weight_init.hpp
- src/toolkits/activity_classification/ac_data_iterator.cpp
- src/toolkits/activity_classification/ac_data_iterator.hpp
- src/toolkits/activity_classification/activity_classifier.cpp
- src/toolkits/activity_classification/activity_classifier.hpp
- src/toolkits/object_detection/object_detector.cpp
- src/toolkits/object_detection/object_detector.hpp
- src/toolkits/object_detection/od_data_iterator.cpp
- src/toolkits/object_detection/od_data_iterator.hpp
- src/toolkits/supervised_learning/automatic_model_creation.cpp
- src/toolkits/supervised_learning/automatic_model_creation.hpp
Adds to the `options` argument for OD and AC (C-API) a new supported key, `"random_seed"`. This seed is used to control all randomness in the toolkit code. If left unset, one is chosen randomly using `std::random_device`.
This should allow us to experiment and test in a more reproducible way, and we can expose this parameter in Python when we adopt the C-API versions there!
> Control OD/AC (C-API) weight initialization and random sampling with seeds

- src/ml/neural_net/mps_cnnmodule.mm
By decrementing the read count manually, MPS can clean up the batch of temporary images. Otherwise, the toolkit crashes with MPS API validation enabled, when we try to deallocate the unused images
> AC on MPS: when performing inference with training network, mark the loss gradient as unused

- src/toolkits/object_detection/object_detector.cpp
- src/toolkits/object_detection/object_detector.hpp
- src/toolkits/object_detection/od_data_iterator.cpp
- src/toolkits/object_detection/od_data_iterator.hpp
- test/unity/toolkits/object_detection/test_object_detector.cxx
- test/unity/toolkits/object_detection/test_od_data_iterator.cxx
TuriCore expects each OD annotation to specify a bounding box as a dictionary with four keys: x, y, width, height. Currently, the code assumes annotations to be in pixel scale, centered at origin, with top-left image origin. We want to support conversion from any given coordinate system to one which the code consumes.
Annotation options added:
* `annotation_scale` with values`pixel` or `normalized`
* `image_origin` with values `top_left` or `bottom_left`
* `annotation_position` with values `center`, `top_left` or `bottom_left`
Default values are `annotation_scale`:`pixel`, `image_origin`:`top_left` and `annotation_position`:`center`, which is the currently assumed annotations input format. 
These options can be added in the `opts` dictionary passed in OD `train()`. At the backend, …
> Adding support for annotations coordinate transform in OD

- src/toolkits/object_detection/od_data_iterator.cpp
gcc 7.4 is quite aggressive about uninitialized variable warnings (errors in our case); this fixes a couple.
> Fix uninitialized variable warnings.

- src/visualization/vega_renderer/JSCanvas.h
- src/visualization/vega_renderer/JSCanvas.m
- test/vega_renderer/examples/turicreate/simple_themed_bar_chart.vl.json
Fixes bug where calling `setFont` with an unavailable font would cause an exception.
> JSCanvas now falls back to system font when the requested font is unavailable

- src/visualization/vega_renderer/VegaRenderer.m
Fixes bug where `_image` was being released twice; once by the caller of `CGImage` and once in `VegaRenderer`'s destructor.
> VegaRenderer no longer holds reference to CGImageRef

- src/visualization/vega_renderer/CMakeLists.txt
- src/visualization/vega_renderer/JSCanvas.h
- src/visualization/vega_renderer/JSCanvas.m
- src/visualization/vega_renderer/JSDocument.h
- src/visualization/vega_renderer/JSDocument.m
- src/visualization/vega_renderer/VegaHTMLElement.h
- src/visualization/vega_renderer/VegaRenderer.m
Expose canvas to Vega through the DOM API by partially partially implementing the `document` object.
> Change VegaRenderer to expose canvas through DOM API

- src/python/turicreate/toolkits/image_classifier/_evaluation.py
- src/python/turicreate/visualization/__init__.py
- src/python/turicreate/visualization/_plot.py
- src/visualization/client/Turi Create Visualization/src/AppDelegate.swift
- src/visualization/client/Turi Create Visualization/src/main.swift
- src/visualization/server/process_wrapper.cpp
Removes the osascript call to bring the app to front, along with the
delay (which was there to ensure the process had started by the time it
gets called). Now, the app code itself brings the window to
the front on launch.
Fixes #1834
> Eliminate delay on opening TC Vis app

- src/core/data/sframe/gl_sframe.cpp
- src/core/data/sframe/gl_sframe.hpp
- src/core/storage/sframe_interface/unity_sframe.cpp
- src/core/storage/sframe_interface/unity_sframe.hpp
- src/model_server/lib/api/unity_sframe_interface.hpp
- src/python/turicreate/_cython/cy_sframe.pxd
- src/python/turicreate/_cython/cy_sframe.pyx
- src/python/turicreate/data_structures/sframe.py
- src/python/turicreate/test/test_sframe.py
- src/visualization/annotation/annotation_base.cpp
- src/visualization/annotation/image_classification.cpp
feature request #1804 
per user request:
```
import numpy as np
data = tc.SFrame({'a':[[0, np.nan],[1,2]]})
data.dropna()
Columns:
a	array
Rows: 1
Data:
+------------+
|     a      |
+------------+
| [1.0, 2.0] |
+------------+
[1 rows x 1 columns]
data = tc.SFrame({'a':[[0, None, "sd"],[1,2]]})
data.dropna() # same result
```
when dropna is called, the program will recursively check each cell in sframe whether it contains **nan** for array type, **None** for other types. if it contains, it will be dropped.
==========update on July 11, 2019=============
user can opt in dropna with recursive check on whether nan values are contained in each cell.
```
data.dropna(recursive=True)
```
> enable recursive dropna for elements in SFrame

- .gitlab-ci.yml
The default version otherwise ends up being the latest stable version,
and the runner machines may not be running a compatible Docker. This
way, we can take control of which versions of the images we're using,
and make sure they are compatible with our runners.
> Pin Docker image versions in Gitlab CI config

- src/visualization/vega_renderer/CMakeLists.txt
- src/visualization/vega_renderer/JSCanvas.h
- src/visualization/vega_renderer/JSCanvas.m
- src/visualization/vega_renderer/JSDocument.h
- src/visualization/vega_renderer/JSDocument.m
- src/visualization/vega_renderer/VegaHTMLElement.h
- src/visualization/vega_renderer/VegaHTMLElement.m
- src/visualization/vega_renderer/VegaRenderer.m
In this PR we implement enough of the DOM API so that Vega will now attempt to add event listeners for interactivity. Our current Obj-C implementation of `addEventListener` is a no-op and will need to be expanded in a later PR; it is however being called by Vega which is promising.
The relevant changes include:
1. Expanding the `VegaHTMLElementInterface` so that it now supports calls to methods such as `addChild`, `removeChild`, `addEventListener`, etc.
2. Implementing versions of these methods in `VegaHTMLElement`.
3. Instantiating a container element which Vega will place our canvas in `VegaRenderer` and referencing this element during Vega initialization.
4. Adding the `body` property to `document`.
> Support enough of the DOM so that Vega attempts to register event listeners

- src/visualization/vega_renderer/JSDocument.m
Allows arbitrary tag names without asserting false -- if we need to
catch an unintended tag name here, we can use LogProxy (added in #2180)
to debug it. Otherwise, the vega example tests try to create span
elements and fail due to the assertion. The tests pass as is without the
assertion.
Fixes #2186
> Fix for broken unit test in vega renderer

- src/visualization/vega_renderer/CMakeLists.txt
- src/visualization/vega_renderer/JSCanvas.h
- src/visualization/vega_renderer/JSCanvas.m
- src/visualization/vega_renderer/JSConsole.h
- src/visualization/vega_renderer/JSConsole.m
- src/visualization/vega_renderer/LogProxy.h
- src/visualization/vega_renderer/LogProxy.m
- src/visualization/vega_renderer/LogProxyHandler.h
- src/visualization/vega_renderer/LogProxyHandler.m
- src/visualization/vega_renderer/VegaRenderer.m
- test/vega_renderer/CMakeLists.txt
- test/vega_renderer/log_proxy_tests.cxx
- test/vega_renderer/log_proxy_tests.hpp
- test/vega_renderer/log_proxy_tests_impl.mm
* Adds a LogProxy object, and a default implementation of
LogProxyHandler, to log to `os_log` methods when properties are
accessed or assigned to on wrapped objects.
* Adds wrap/unwrap static methods to allow objects to easily be
wrapped/unwrapped as needed.
* Unit tested for expected behavior (the LogProxy-wrapped object should not
behave differently from the original object) and for wrapping
functionality (wrapper methods get invoked as expected).
Potential uses:
* Set break points in the debugger on the getter/setter methods.
* Run `log stream --level info` to get a stream of the log.
* Insert a custom logger to get observability on a particular object.
Fixes #2158
> Make VegaRenderer more debuggable

- src/python/turicreate/test/test_style_transfer.py
- src/python/turicreate/toolkits/style_transfer/style_transfer.py
Closes #2013 
Added check for `max_iterations` in Style Transfer `create()` to ensure in integer >=0. Checking for incorrect formats: strings, floats and negative integers. Added tests.
For consistency in toolkits, input of `max_iterations=0` matches use in OD and defaults to same behavior as `max_iterations=None` i.e. automatically determine based on amount of data. (Tests where max_iterations=0 was previously set have been modified to max_iterations=1)
> Sanity check max_iterations in Style Transfer

- src/core/data/flexible_type/flexible_type.cpp
- src/core/data/flexible_type/flexible_type.hpp
- src/core/storage/sframe_interface/unity_sarray.cpp
- src/core/storage/sframe_interface/unity_sarray.hpp
- src/core/storage/sframe_interface/unity_sframe.cpp
- src/core/storage/sframe_interface/unity_sframe.hpp
- test/unity/unity_sframe.cxx
This PR updates the logic in unity_sframe and unity_sarray for dealing
with dropping missing values.
- Fixes https://github.com/apple/turicreate/issues/2170.  The root issue
there was that the dropna function was defined as a function over all
the rows instead of just the rows needed.  Thus the optimizer would
not treat it correctly.
- Eliminated duplicated code between unity_sarray and unity_sframe.
Dropna on a single column now uses unity_sarray implementation to
provide the mask column.
> Updates and optimizations to logic for dropna.

- userguide/style_transfer/README.md
- userguide/style_transfer/how-it-works.md
Closes #1953 
Added: heads up for CPU train time, caveat for use of `finetune_all_params` and link to Advanced Usage.
> Style Transfer user guide update

- test/vega_renderer/base_fixture.hpp
- test/vega_renderer/base_fixture.mm
Uses different "acceptable diff" thresholds for 10.14+ and 10.13. On 10.13 and prior, the font rendering seems a bit different, so we'll allow the rendered output to differ a bit more. Nothing seems fundamentally broken.
Fixes #2201
> Fix vega renderer tests on macOS 10.13

- src/ml/neural_net/mps_image_augmentation.mm
> Helper function wrapping std::function in ObjC block must capture by value, not by reference

- .gitlab-ci.yml
- README.md
- scenario-tests/additional_requirements.txt
- scenario-tests/run_scenario_tests.sh
- scripts/install_python_toolchain.sh
- scripts/make_wheel.sh
- scripts/requirements.txt
- scripts/run_cpp_tests.py
- scripts/test_wheel.sh
- src/python/README.rst
- src/python/setup.py
- src/python/turicreate/_sys_util.py
- src/python/turicreate/data_structures/sframe.py
- src/python/turicreate/test/test_object_detector.py
- src/python/turicreate/test/test_style_transfer.py
- src/python/turicreate/toolkits/_mxnet/__init__.py
- src/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py
- src/python/turicreate/toolkits/image_analysis/image_analysis.py
- src/python/turicreate/toolkits/object_detector/object_detector.py
- src/python/turicreate/toolkits/sound_classifier/_audio_feature_extractor.py
- src/unsupported_python/setup.py
I believe this is almost all of the changes we need (in this repository) to support Python 3.7. The only other changes that I know will be needed are in`.gitlab-ci.yml`.
Currently calling `predict(...)` on a coremltools model is broken in Python 3. This is being tracked in [an issue](https://github.com/apple/coremltools/issues/372) in the coremltools repository. We'll need to wait for that to get fixed and for a new version to be released.
All non-CoreML related unit tests pass for Python 3.7 on macOS.
This also fixes #1455
> Python 3.7 macOS Support

- src/python/doc/source/conf.py
- src/python/doc/source/turicreate.toolkits.drawing_classifier.rst
- src/python/doc/source/turicreate.toolkits.one_shot_object_detector.rst
- src/python/turicreate/toolkits/drawing_classifier/__init__.py
- src/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py
- src/python/turicreate/toolkits/one_shot_object_detector/__init__.py
- src/python/turicreate/toolkits/one_shot_object_detector/one_shot_object_detector.py
- userguide/drawing_classifier/data-preparation.md
fixes #2112 
This has some fixes for drawing classifier user guide that I found yesterday. 
I have locally built the API docs for one-shot object detector and drawing classifier. There is still one warning which I cannot get rid of. We should verify this works during 5.7 release.
> Fixes API docs 

- src/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py
- userguide/drawing_classifier/advanced-usage.md
Closes #2092 
- Changed `max_iterations` from 100 to 500.
- Added caveat in user-guide for using more epochs when training model for a larger number of classes.
> Changed default max_iterations for DC

- src/python/turicreate/visualization/show.py
Without this fix, a user passing the wrong data type to `plot` would get
a cryptic error message like:
```python
----> 1 tc.show('date', 'temp')
/Users/zach/turicreate/debug/src/python/turicreate/visualization/show.py in show(x, y, xlabel, ylabel, title)
141
142     """
--> 143     plot(x, y, xlabel, ylabel, title).show()
144
145 def scatter(x, y, xlabel=LABEL_DEFAULT, ylabel=LABEL_DEFAULT, title=LABEL_DEFAULT):
/Users/zach/turicreate/debug/src/python/turicreate/visualization/show.py in plot(x, y, xlabel, ylabel, title)
78     """
79     title = _get_title(title)
---> 80     plt_ref = tc.extensions.plot(x, y, xlabel, ylabel, title)
81     return Plot(_proxy=plt_ref)
82
/Users/zach/turicreate/debug/src/python/turicreate/extensions.pyc in <lambda>(*args, **kwargs)
168
169 def …
```
> Better error message on bad input to plot()

- src/ml/neural_net/mps_layer_helper.h
- src/ml/neural_net/mps_layer_helper.mm
- src/ml/neural_net/style_transfer/mps_style_transfer_decoding_node.mm
- src/ml/neural_net/style_transfer/mps_style_transfer_encoding_node.mm
- src/ml/neural_net/style_transfer/mps_style_transfer_residual_node.mm
- src/ml/neural_net/style_transfer/mps_style_transfer_transformer_network.mm
- src/ml/neural_net/style_transfer/mps_style_transfer_vgg_16_block_1_node.mm
- src/ml/neural_net/style_transfer/mps_style_transfer_vgg_16_block_2_node.mm
- weights key conflicts with property already existent on `MPSCNNConvolutionNode`
> Fixed namespace conflicts Obj-C

- .gitattributes
The GitHub feature that computes the language breakdown supports [adding
overrides](https://github.com/github/linguist#overrides) to the
`.gitattributes` file; we can use this to explicitly ignore code from
outside this repo.
> Enable more accurate language breakdown on GitHub

- src/visualization/annotation/annotation_base.cpp
- src/visualization/annotation/annotation_base.hpp
- src/visualization/annotation/image_classification.cpp
- test/annotation/image_classifier_tests.cxx
- userguide/image_classifier/advanced-usage.md
It depends on #2227, which will make `unity_sframe::append` work as the same as what frontend part does.
The new behavior will:
1. prohibit undefined images from being shown in the annotation GUI window.
2. will throw if no valid images there to be ready to render in GUI.
3. will return result-set including all rows having missing values in their `image` column, with the corresponding annotation column value being set as None (undefined).
```
In [6]: images = tc.SFrame("my_image/")
In [6]: images = tc.SFrame("my_image/")
In [7]: images
Out[7]:
Columns:
path    str
image   Image
Rows: 2
Data:
+-------------------------------+------------------------+
|              path             |         image          |
+-------------------------------+------------------------+
| …
```
> 1977 annotation skip invalid images

- src/core/logging/logger.hpp
- src/python/turicreate/test/test_nearest_neighbors.py
In an ideal world, the exception message should be adequate for us to locate where the exception is thrown. But many times the error reports from those exceptions are too opaque, such as "file not found".
In the current logger, `filename`, `function name` and `line number` are actually included in the logging body. Initially, I thought we don't have those in our logger. Now my work simplifies by adding those into exception message for the debug mode.
I find it's inconvenient to check the logging file all the time to find where the exception is thrown. Now if we have `filename`, `function name` and `line number` in the exception message, it's straightforward for us to look into the issue and search solutions.
Also, it's easy for users to report issues since most of them may not know where …
> adding src location info in exception messages to accelerate debugging

- src/toolkits/object_detection/one_shot_object_detection/util/parameter_sampler.cpp
> Fixed angle plumbing for theta, phi, and gamma.

- src/python/turicreate/data_structures/sframe.py
- src/python/turicreate/visualization/_plot.py
This PR resolves #2236 
Fixed Jupyter notebook inline title
> Resolves #2236: Fixed jupyter notebook inline title

- src/toolkits/object_detection/one_shot_object_detection/util/parameter_sampler.hpp
We want to bias all the angle distributions to zero for now so we do not create synthetic images with objects rotated that in the real world, cannot be. We can expose parameters to tune this at a later point.
> Angle distributions have a mean of zero

- src/ml/neural_net/mps_layer_instance_norm_data_loader.mm
Missed an offset in the Instance norm data loader on initialization of weights.
> Fixed offset for the initialization of the instance norm data loader

- .gitlab-ci.yml
Didn't update the cpp tests or the `dylib` runners because they don't depend on 10.15 api.
Plus the tests run only on 10.14 because currently we don't have tests to cover the code that is specific to 10.15.
> Updated Gitlab Builds to 10.15

- src/core/storage/sframe_interface/unity_sarray.cpp
- src/ml/neural_net/mps_graph_trainer.mm
- src/python/turicreate/data_structures/sarray.py
- src/python/turicreate/data_structures/sframe.py
- src/python/turicreate/test/test_sarray.py
- fix #89 
- update the documented behavior of read_json to allow reading JSON list with homogeneous type.
- since SFrame's read_json also depends on the modified SArray's read_json, I add assertion to make sure the JSON file read into SFrame is a list of dictionary
> New API for SArray's read_json

- src/python/turicreate/test/test_recommender.py
- src/python/turicreate/toolkits/recommender/util.py
This PR resolves #2044 
recommend_from_interactions --exclude doesn't work properly
> issue fix for recommend_from_interactions --exclude doesn't work properly

- src/core/data/flexible_type/flexible_type_detail.hpp
- src/core/data/image/image_type.cpp
- src/core/data/image/image_type.hpp
- src/python/turicreate/test/test_sarray.py
- fix #2042 to allow comparing SArray with Image type
- Currently, implementation of the equality operator mirrors the python implementation where two images are equal *only* when every property (`m_height`, `m_width`, ..., `m_image_data`) are identical, but we might want to allow comparing two identical images with different lossless types (png vs. RAW) by decoding to RAW type
> Implement equality operator for image_type

- src/python/turicreate/toolkits/object_detector/_tf_model_architecture.py
The array passed from numpy in Python is being transposed to be converted in the correct CoreML format. But the numpy transpose just changes the strides, doesn't touch the actual array. This is then mapped to our `shared_float_array`(strides unaware) in pybind11. This will basically mix the trained weights because our shared_float_array reads the buffer without knowing the change made to the strides even though the shape being sent is correct.
> Export weights in pybind11 expects Contiguous Array

- src/python/turicreate/toolkits/activity_classifier/_activity_classifier.py
In C++ implementation, doing prediction with either 'per_row' and 'per_window' is using two different functions and thus, the check needs to be in the python layer.
> Adding argument check for output_frequency

- src/ml/neural_net/mps_layer_instance_norm_data_loader.mm
- src/ml/neural_net/style_transfer/mps_style_transfer.h
- src/ml/neural_net/style_transfer/mps_style_transfer.m
- src/python/turicreate/toolkits/style_transfer/style_transfer.py
Added necessary changes to make TCMPS Style Transfer converge.
- Changed weight export from Instance Norm Data Loader
- Added `resultImages` to training graph definition
- Change the the weight reshape in Python
> TCMPS Style Transfer Fixes

- src/ml/neural_net/CMakeLists.txt
The target flags for the Obj-C module should be separated out so they are passed
in as individual flags.  Also, since it is exposed through C headers, they
should be private to restrict them to only compilation of that module.
> Fixed CMakeLists typo with arguments.

- src/ml/neural_net/tf_compute_context.cpp
Would print out the errors from Python side correctly. Won't show vague errors like #2373 anymore.
> Adds error logging for pybind11

- CMakeLists.txt
- configure
- src/CMakeLists.txt
- src/ml/neural_net/CMakeLists.txt
Currently, compilation with --no-python is broken in master, as some modules that depend on python are compiled even when that flag is specified.  This fixes that.
> Cleaned up compilation of python flags

- userguide/package.json
- Newer versions of `MathJax` don't play well with `MathJax-Node`.
- Pegging dependencies solves these conflicts.
> Pegged MathJax version

- src/ml/neural_net/mps_graph_trainer.mm
- src/ml/neural_net/style_transfer/mps_style_transfer_backend.hpp
- src/ml/neural_net/style_transfer/mps_style_transfer_backend.mm
Renamed the `style_transfer` class to the `mps_style_transfer` class.
> Rename ST to MPS_ST for contexts

- src/ml/neural_net/model_spec.cpp
- src/ml/neural_net/model_spec.hpp
- src/python/turicreate/toolkits/object_detector/object_detector.py
- src/toolkits/object_detection/object_detector.cpp
- src/toolkits/object_detection/object_detector.hpp
- src/toolkits/object_detection/od_serialization.cpp
In this PR I did several things:
1. Import for C++ saved model:
Mainly in od_serialization.cpp::init_darknet_yolo(),
I add max pooling layer, preprocessing layer, and change the input of the network,
in order to make the nn_spec exactly the same as which we get when we train a model in c++.
So in model_spec.cpp, I added pooling layer and preprocessing layer in order to use them. 
2. Import for Python saved model:
Mainly in object_detector.cpp:import_from_custom(),
It basically move the weight from saved Python model to c++.
3. Add "use_tensorflow" flag for Python model:
Since currently when we evaluate a c++model, the code request a "use_tensorflow" flag,
which wasn't presented in python model when it is trained with _advance_param =  
{'use_tensorflow':false}. I simply add it to the …
> [C++ OD] Add import function for Python saved model. Fix import function for C++ saved model.

- src/toolkits/CMakeLists.txt
- src/toolkits/style_transfer/CMakeLists.txt
- src/toolkits/style_transfer/style_transfer_data_iterator.cpp
- src/toolkits/style_transfer/style_transfer_data_iterator.hpp
- test/CMakeLists.txt
- test/toolkits/CMakeLists.txt
- test/toolkits/style_transfer/CMakeLists.txt
- test/toolkits/style_transfer/test_style_transfer_data_iterator.cxx
- test/toolkits/style_transfer/utils.cpp
- test/toolkits/style_transfer/utils.hpp
Setup the class for the Style Transfer Data Iterator. It takes in data iterator params. and the relevant method on this iterator is `next_batch`. `next_batch` returns a batch containing a tie of `content_image`, `style_image`, and `style_index`.
> Style transfer Data Iterator

- src/python/turicreate/test/test_text_analytics.py
- src/python/turicreate/test/test_text_classifier.py
- src/python/turicreate/toolkits/text_analytics/_util.py
- src/toolkits/feature_engineering/word_trimmer.cpp
otherwise it will cause segfault. #2402 
Current, behavior will be during the model training session, it will throw ToolkitError to remind user using dropna to clean up data.
> skip missing values when dropping words

- test/unity/toolkits/object_detection/one_shot_object_detection/test_parameter_sampler.cxx
Tested and fixed now.
C++ test build was failing because of this. Fixed now.
> Fixed incorrect call to sampler.sample in unit test.

- src/toolkits/object_detection/object_detector.cpp
Fixes #2436 
Added a const qualifier in the comparison function to pass Linux builds.
Waiting for internal builds to pass.
> Fixed comparison function in Object Detector C++

- src/python/turicreate/test/test_one_shot_object_detector.py
This is a temporary workaround for #2406 so our unit tests run faster. These tests seem to take up almost an hour and I'm not sure why... Until we figure that out, let's skip these unit tests.
> Skipping two bottleneck Python unit tests for OSOD

- src/toolkits/object_detection/object_detector.cpp
- src/toolkits/object_detection/object_detector.hpp
- test/unity/toolkits/neural_net/neural_net_mocks.hpp
- test/unity/toolkits/object_detection/test_object_detector.cxx
While everyone is wrapping their head around unit tests and mocks, I thought this would be an opportune time to merge a PR with a preliminary stab at checkpointing support for OD, taking this opportunity to clean up the OD tests a bit. With `object_detector::train` now split into smaller pieces, especially `init_training` and `iterating_training`, the previous monolithic test can be decomposed a bit too.
Also moved all the task-agnostic mocks to a header, where they can be used by tests for ST, DC, etc.
> Add checkpointing support for OD

- src/ml/neural_net/tf_compute_context.cpp
I am returning 4GB as the memory as C++ side makes batch_size 32 then (which is what we want as MXNet uses always and we want to make TF comparable to MXNet as of now)
> Add memory budget to tf_compute_context

- src/ml/neural_net/model_spec.cpp
- src/ml/neural_net/model_spec.hpp
- src/toolkits/activity_classification/activity_classifier.hpp
- src/toolkits/coreml_export/neural_net_models_exporter.cpp
- src/toolkits/coreml_export/neural_net_models_exporter.hpp
- src/toolkits/drawing_classifier/drawing_classifier.cpp
- src/toolkits/drawing_classifier/drawing_classifier.hpp
- test/CMakeLists.txt
- test/unity/toolkits/drawing_classifier/CMakeLists.txt
- test/unity/toolkits/drawing_classifier/test_dc_serialization.cxx
model spec follows CoreML neural network spec format which describes ANN architecture to be used.
__MySuggestion__
You can skip reviewing `drawing_classifier.hpp` since it only has minor code style change, which is irrelevant to this topic.
__MyPlan__
__MySummary__
* [Y] adding unittest[Y/N]?
* [N] breaking current unittest[Y/N]?
> init/export model spec for DC

- src/python/turicreate/toolkits/_internal_utils.py
- src/python/turicreate/toolkits/activity_classifier/_activity_classifier.py
- src/python/turicreate/toolkits/object_detector/object_detector.py
**Usage:**
On CLI:
To enable C++ model codepath:
```
export TURI_OD_USE_CPP_PATH="1"
export TURI_AC_USE_CPP_PATH="1"
```
(or any input other than '0')
To disable C++ model codepath i.e. enable Python codepath:
```
export TURI_OD_USE_CPP_PATH="0"
export TURI_AC_USE_CPP_PATH="0"
```
By default or in the absence of the above env variables, the behavior is to use Python codepath.
_Setting these env variable will allow python unit testing to use the desired codepath._
> Added `USE_CPP` flag for AC and OD

- src/python/turicreate/toolkits/_model.py
These changes make use of the `use_cpp` flag to define the codepath taken. 
Both C++ and Python models (i.e. from the new and old implementations) are loaded correctly with the C++ codepath. 
_PS Models from the new implementations are not loaded corrected in the old Python loaded._
> Save and Load for C++ codepath for OD and AC

- src/core/util/test_macros.hpp
Use the correct form of the boost tests to test for approximate equality in TS_ASSERT_DELTA
> Correctly test for approximate equality and usefully report issues.

- src/core/storage/sframe_data/csv_writer.cpp
- test/sframe/sframe_csv_test.cxx
This PR resolves #860 
Column names containing commas should be wrapped in quotes when saving to CSV
> Column names containing commas should be wrapped in quotes

- src/python/turicreate/toolkits/object_detector/object_detector.py
- src/toolkits/object_detection/object_detector.cpp
- src/toolkits/object_detection/object_detector.hpp
- test/unity/toolkits/neural_net/neural_net_mocks.hpp
- test/unity/toolkits/object_detection/test_object_detector.cxx
Change several things in this PR:
1.Add confidence_threshold, iou_threshold arguments for predict() and evaluate().
2.Enable different input data types (sframe, array, image) for predict().
3.Enable different output data types (dict, sframe) for evaluate().
4.Change the output attribute "bounding box" to "coordinate" for predict() in order to pass the python unit test.
5.Add output attribute "type" for predict() in order to pass the python unit test. 
6.Change several lines in the unit test for OD regarding the additional arguments for perform_evaluation()
> Additional arguments for OD's predict and evaluate function

- src/python/turicreate/toolkits/activity_classifier/_activity_classifier.py
- src/python/turicreate/toolkits/object_detector/object_detector.py
`_native_name()` implementation in both Python and C++ classes set such that when using the C++ codepath the Python model will not be registered and vice versa. This will enable the model to be wrapped in the correct class.
> Fixes Load model for AC and OD

- src/toolkits/drawing_classifier/dc_data_iterator.cpp
- src/toolkits/drawing_classifier/dc_data_iterator.hpp
- test/unity/toolkits/drawing_classifier/test_dc_data_iterator.cxx
- test/unity/toolkits/drawing_classifier/test_drawing_classifier.cxx
fix the bugs in dc_iterator implementation:
* has_next_batch (original bug design flaw)
* next_batch (introduced by read_batch_size bug)
fix test break of test_dc_data_iterator.cxx.
__MY REVIEW SUGGESTION__
since I have some style change mixed in, I explicitly commented near the critical sections you need to know about all the bug fixes.
__MY SUMMERY__
* [Y] __PASS ALL RELEVANT TEST__? [Y/N]
* [Y] __CAN COMPILE__? [Y/N]
> A bunch of bug fix for dc_iterator

- src/python/turicreate/toolkits/image_similarity/image_similarity.py
The documentation for `create` in `image_similarity` didn't make sense. I flipped two lines to make a legible sentence. Also, added the word _one_ to clarify that exactly one column of the Image type is expected.
```
feature : string
indicates that the SFrame has only column of Image type and that will
Name of the column containing the input images. 'None' (the default)
be used for similarity.
```
```
feature : string
Name of the column containing the input images. 'None' (the default)
indicates that the SFrame has only one column of Image type and that will
be used for similarity.
```
> flip two lines in image_similarity documentation

- src/core/util/test_macros.hpp
- test/timer/timer_test.cxx
Changed namespace of `boost::test` to `boost::test_tools`.
Running pipelines internally and on Travis CI to see if there are any issues with the namespace changes.
> Changed macros to test_tools from test

- src/ml/neural_net/model_spec.cpp
- src/ml/neural_net/model_spec.hpp
- src/toolkits/style_transfer/style_transfer_model_definition.cpp
- test/toolkits/style_transfer/utils.mm
- The scale used in OD and Style Transfer are slightly different. To handle theses different use_cases, and match the CoreML specs a new `add_scale` is proposed.
> Added Fixes For single Scale value in CoreML

- test/unity/toolkits/drawing_classifier/test_drawing_classifier.cxx
a small fix for test break of `test_drawing_classifier.cxx` to unblock #2480.
model state `feature` type of string is changed to state `features` with type list. We should make sure all existing test cases pass in master so that we won't block other people's pipeline validation process.
one suspicious part is that there's a model state called `classes`. I'm not sure it's used. @shantanuchhabra may spend some time investigating.
> fix for test break

- src/python/turicreate/toolkits/_pre_trained_models.py
- src/python/turicreate/toolkits/style_transfer/_tf_model_architecture.py
- src/python/turicreate/toolkits/style_transfer/style_transfer.py
- src/toolkits/style_transfer/style_transfer.cpp
This PR does the following -
- Prints device name its training on (added in `style_transfer.cpp`)
- Pretrained models hosted on developer.apple.com are being pulled in the frontend and being passed to C++
- Added calculation `num_styles` also to python side
- Introduced a environment variable like for AC/OD for style_transfer
- Added the style_transfer_beta class
> Python frontend for style transfer

- src/python/turicreate/data_structures/sarray.py
- src/python/turicreate/test/test_sframe.py
This PR resolves #2221 
dict_keys and dict_values types do not work with filter_by
> dict_keys and dict_values types do not work with filter_by #2221

- src/toolkits/object_detection/object_detector.cpp
- src/toolkits/object_detection/od_data_iterator.cpp
- src/toolkits/object_detection/od_data_iterator.hpp
- test/unity/toolkits/object_detection/test_object_detector.cxx
- test/unity/toolkits/object_detection/test_od_data_iterator.cxx
Modify OD data iterator in order to read data with no annotations.
And also skip the data which has invalid labels.
> OD iterator fixed: missing annotations and invalid labels.

- src/python/turicreate/toolkits/sound_classifier/sound_classifier.py
We just need to do the same for the data iterator, alongside Fareeha's changes for the actual NN training, and we should be in good shape to flip the switch for SC.
> Provide TF alternative to MXNet accuracy metric during SC training

- src/core/storage/fileio/fileio_constants.cpp
This PR resolves #789 
Default value used for TURI_CACHE_FILE_LOCATIONS if that path does not exist
> Handle error message with path info

- src/ml/neural_net/mps_compute_context.mm
This should simplify testing TensorFlow implementations on Macs (albeit slowly, with CPU-only computation)
> Setting TURI_NUM_GPUS=0 should disable MPS backend

- src/toolkits/drawing_classifier/drawing_classifier.cpp
- test/unity/toolkits/drawing_classifier/CMakeLists.txt
- test/unity/toolkits/drawing_classifier/test_dc_evaluation.cxx
Just realized that dc doesn't have a special evaluator since it uses widely used `evaluation::compute_classifier_metrics`. So the test should be really for `evaluation::compute_classifier_metrics`.
The general prediction result generator is what I want to promote to `dc_data_utils.hpp`. Let's merge this and I will apply the data generator to my test for prediction.
__MY MANIFEST__
__MY SUMMARY__
> evaluate & test

- src/python/turicreate/test/test_drawing_classifier.py
- Marking a test_export_coreml as an expected failure.
> Marked a test as expected failure.

- src/python/turicreate/test/test_style_transfer.py
- Test failure for get_styles passes so unmarked as failures.
> PyTest failures for `get_styles` updated.

- src/python/turicreate/test/test_style_transfer.py
- src/toolkits/coreml_export/neural_net_models_exporter.cpp
- src/toolkits/coreml_export/neural_net_models_exporter.hpp
- src/toolkits/style_transfer/style_transfer.cpp
- Added prefix to style image to avoid naming conflicts
- Added `num_styles` to index to add support for multiple styles
> PyTest failures for `export_to_coreml` updated. 

- src/ml/neural_net/mps_compute_context.hpp
- src/ml/neural_net/mps_compute_context.mm
We never ported this Python logic, governing when to use MPS, to the C++ code path: https://github.com/apple/turicreate/blob/879e82ebcb2d3f0bc4f3694d83eff5b8063d084f/src/python/turicreate/toolkits/_mps_utils.py#L190
These changes implement that logic, as well as incorporate new support in macOS 10.15 Catalina for Skylake and later Intel integrated GPUs.
Fixes #919
> C++ code paths should only use MPS backend for supported Metal devices

- src/ml/neural_net/style_transfer/mps_style_transfer.m
- src/python/turicreate/test/test_style_transfer.py
- src/toolkits/style_transfer/style_transfer.cpp
- Added a batch size of one to predict due to Tensorflow ND array limitations.
> Pytest `test_stylize_success` removed xfail

- src/ml/neural_net/mps_compute_context.hpp
- src/ml/neural_net/mps_compute_context.mm
- test/unity/toolkits/neural_net/test_mps_image_augmentation.cxx
#2609 broke our C++ test build (our CI did not propagate the error code)
First, provide a new way for the MPS image augmenter tests to instantiate `mps_image_augmenter`, without needing to instantiate `mps_compute_context`.
Also, disable a portion of this test that has become flaky.
> Fix broken/failing test_mps_image_augmenter.cxxtest

- src/python/turicreate/test/test_object_detector.py
- src/toolkits/object_detection/od_data_iterator.cpp
Check if the coordinate has valid dictionary type for OD data iterator.
This should fix the segfault for `test_create_with_invalid_annotations_list_coord ` on gitlab,
but still running.....
> Od list coordinate

- src/toolkits/style_transfer/style_transfer.cpp
- changed `index` to `i` in order to not overwrite the existing index value we use later on
> Index to i

- src/toolkits/activity_classification/ac_data_iterator.cpp
- src/toolkits/activity_classification/ac_data_iterator.hpp
- src/toolkits/activity_classification/activity_classifier.cpp
- src/toolkits/activity_classification/activity_classifier.hpp
- test/unity/toolkits/activity_classifier/test_activity_classifier.cxx
Adds this column for `predict` and updates the semantics for `classify`. Unlike 5.8, this column now gives the index of the prediction within the session (instead of the index overall, which is just the row number in the result table)
Also fixes some places where the result SFrame should use the user's column name for the session ID, not the string "session_id"
Fixes #1706
> Implement "prediction_id" column for "per_window" prediction for AC

- src/ml/neural_net/style_transfer/mps_style_transfer.m
- src/ml/neural_net/style_transfer/mps_style_transfer_backend.mm
- src/python/turicreate/toolkits/style_transfer/_tf_model_architecture.py
- src/toolkits/style_transfer/style_transfer.cpp
- Added shape to float array in predict.
- removed explicit shape in `process_output`
- compute_contexts should take care of sizing themselves
- Added crop to TF (It was present previously in the MxNet implementation since padding is added in both the TF and MxNet implementations from the way Reflective Padding is done)
- The four failing Unit Tests in the TF implementation of ST.
- Tests Passing in both TF and MPS
> Fixed Resizing issue in TensorFlow for Style Transfer

- .gitlab-ci.yml
- scripts/Dockerfile-CentOS-6
The root cause of the S3 Cert issue is that during the compilation of curl, the path /etc/ssl/certs/ is only added as a search path for certificates if it is present on the machine at build time.  Without that, CURL does not build with that enabled as a search path.  When we switched our build environment to CentOS 6 to support the manylinux2010 standard, it didn't have this directory on the resulting build machine and so our resulting egg did not search that path.
> Fix for issue #2648, SSL cert issue.

- .travis.yml
- src/python/turicreate/test/test_drawing_classifier.py
- src/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py
Since the C++ layer can only accept values = "auto", an SFrame, or an empty SFrame (so no validation info is computed), we sanitize the `validation_data` value passed in to the C++ layer from Python by translating a `None` on the Python side into an empty SFrame on the C++ side.
Fixes #2605
> DC: Sanitize validation_data value passed in to C++

- test/toolkits/style_transfer/CMakeLists.txt
- test/toolkits/style_transfer/utils.cpp
Rename .mm to .cpp and remove inclusion of Foundation; this file doesn't
appear to need ObjC at all, and we don't need to introduce an ObjC
compiler dependency on Linux.
This fixes the build for any Linux machines that don't have an ObjC
compiler toolchain.
> Fix Linux build in style_transfer/utils

- .travis.yml
- src/python/turicreate/toolkits/_model.py
- src/python/turicreate/toolkits/activity_classifier/_activity_classifier.py
This will check off the box for AC in the issue #2606
```
In [4]: model                                                                                                                                                        
Out[4]: 
Class                                    : ActivityClassifier_beta
Schema
------
Number of examples                       : 748406
Number of sessions                       : 56
Number of classes                        : 6
Number of feature columns                : 6
Prediction window                        : 100
Training summary
----------------
Log-likelihood                           : 1.3202
Training time (sec)                      : 35.9083
```
> Adding __repr__ in AC_beta

- .travis.yml
- src/ml/neural_net/tf_compute_context.cpp
- src/python/turicreate/test/test_drawing_classifier.py
- src/python/turicreate/toolkits/drawing_classifier/_tf_drawing_classifier.py
TL;DR, `ascontiguousarray` is preferrable over `copy`.
---
~This is [WIP] because I want to leave my debug trace for people who want to repro and have a deep understanding of the issue is.~
The root cause for inconsistency of weights exported from TF to TC is:
```
net_params.update({var.name.replace(":0", ""): _np.transpose(val, (3, 2, 0, 1))})
```
The numpy `ufunc` transpose doesn't change the memory layout of numpy array. When we load the python object to TC CPP backend, we use this logic here
```
pybind11::buffer_info buf = kv.second.request();
turi::neural_net::shared_float_array value =
turi::neural_net::shared_float_array::copy(
static_cast<float*>(buf.ptr),
std::vector<size_t>(buf.shape.begin(), buf.shape.end()));
```
The shape is correct but the `buf.ptr` points to the actually …
> Align numpy memory view when exporting weights from TF to TC

- src/ml/neural_net/CMakeLists.txt
- src/ml/neural_net/mps_weight.h
- src/ml/neural_net/mps_weight.mm
- src/ml/neural_net/style_transfer/mps_style_transfer.h
- src/ml/neural_net/style_transfer/mps_style_transfer.m
- src/ml/neural_net/style_transfer/mps_style_transfer_backend.mm
- src/ml/neural_net/style_transfer/mps_style_transfer_decoding_node.h
- src/ml/neural_net/style_transfer/mps_style_transfer_decoding_node.mm
- src/ml/neural_net/style_transfer/mps_style_transfer_encoding_node.h
- src/ml/neural_net/style_transfer/mps_style_transfer_encoding_node.mm
- src/ml/neural_net/style_transfer/mps_style_transfer_residual_node.h
- src/ml/neural_net/style_transfer/mps_style_transfer_residual_node.mm
- src/ml/neural_net/style_transfer/mps_style_transfer_transformer_network.h
- src/ml/neural_net/style_transfer/mps_style_transfer_transformer_network.mm
- src/ml/neural_net/style_transfer/mps_style_transfer_weights.h
- src/ml/neural_net/style_transfer/mps_style_transfer_weights.m
- converting weights from MPS and CoreML and CoreML and MPS in style transfer.
- MPS and CoreML are in different weight formats. CoreML is `OIHW` and MPS is in `OHWI`.
- `NSData*` wasn't enough information to make the transposes work. All data now in TCMPS has a shape associated with it. This includes all input and output images as well as the weights being shuttled in and out of TCMPS Style Transfer.
- `TCMPSStyleTransferWeights` couldn't be in `mps_style_transfer_utils.mm` because an interface in that file extends an interface and we need `TCMPSStyleTransferWeights` before we define the interface. Therefore we place `TCMPSStyleTransferWeights` in it's own file so that it can be imported with ease.
> Style Transfer MPS to CoreML and CoreML to MPS converters

- test/unity/toolkits/drawing_classifier/test_dc_serialization.cxx
There was a mismatch in the type of the warm start option in `drawing_classifier.cpp` versus `test_dc_serialization.cxx`.
> Fixed C++ unit test failure in test_dc_serialization

- src/toolkits/coreml_export/neural_net_models_exporter.cpp
- test/unity/toolkits/drawing_classifier/test_dc_serialization.cxx
We did not have support for integer class labels, which caused an assertion failure in `test_export_coreml_with_predict` Python unit test.
Thank you @shreyajain17 and @Jarvi-Izana for pointing this out.
For reviewers, please review src/toolkits/coreml_export/neural_net_models_exporter.cpp.
The changes in test/unity/toolkits/drawing_classifier/test_dc_serialization.cxx are approved as of #2700
> DC: Add support for integer class labels in Core ML export.

- src/toolkits/drawing_classifier/drawing_classifier.cpp
- test/unity/toolkits/coreml_export/test_neural_nets_model_exporter.cxx
- test/unity/toolkits/drawing_classifier/test_dc_serialization.cxx
In #2656, the signature for `export_object_detector_model` and `drawing_classifier::export_to_coreml` was changed. While the PR also addressed any user-facing code paths that accessed those functions, the C++ tests were not modified to access this functionality differently. This PR makes those changes in the C++ tests to make our C++ unit tests build and run successfully.
> Fixed test build failures introduced in #2656.

- src/visualization/annotation/image_classification.cpp
Break caused by #2715 -- in release mode, the unused variable causes a
warning-as-error.
> Fix build in release mode

- src/toolkits/style_transfer/style_transfer_data_iterator.cpp
- Style Transfer requires all of the channels to be of size 3 as the network depends on this.
- Calling the resize method in image_utils get's us this functionality
- It was added upstream in the data loader because that's where the data for the style transfer model is prepared.
> Added resizing to channels to get them to match for ST

- src/python/turicreate/test/test_image_classifier.py
Until 5.8, `test_export_coreml` was skipped for Image Classifier.
The unit test has been failing for `VisionFeaturePrint_Scene` since before 5.8 and is tracked in #2744.
> XFail the VisionFeaturePrint_Scene export_coreml failure

- src/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py
- src/python/turicreate/toolkits/image_classifier/_evaluation.py
Previously Drawing Classifier explore was unimplemented in 6.0
- Parity of `.explore` with 5.8 in 6.0
- `is` to using `==` for key comparison for robustness. Compare value rather than identity.
> Added model evaluate to 6.0 matching behavior from 5.8

- test/toolkits/style_transfer/test_style_transfer_data_iterator.cxx
- test/toolkits/style_transfer/utils.cpp
Unit test failure present in `style_transfer_data_iterator` due to images being decoded by the data_iterator. This change was brought about by realizing that the images were going to eventually be decoded anyway and calling `decode_image` on an image that was already decoded was a `no-op`.
The `style_transfer_data_iterator::test_initialization` test checked image equality. So encoded images were passed into the data iterator and previously encoded images would come out. Because of #2740, the default behavior of the data iterator changed, and encoded images were now being returned as decoded images.
This was causing the unit test failure we see in `style_transfer_data_iterator`.
Ensure that the images being compared are either all `encoded` or all `decoded`. Since the data loader now …
> Switched to decoded image

- src/python/turicreate/toolkits/audio_analysis/audio_analysis.py
Reverts apple/turicreate#2751
This was merged incorrectly.
> Revert "turicreate.load_audio does not fail on invalid path"

- src/python/turicreate/toolkits/sound_classifier/_tf_sound_classifier.py
Closes #2688 
1) Softmax was being applied twice: `self.predictions` which had softmax activation applied on it was being passed to `tf.nn.softmax_cross_entropy_with_logits_v2` to compute loss. Fixed this by passing last layer activations to `softmax_cross_entropy_with_logits_v2` instead.
2) Optimizer for TF changed from Adam to NAG to match MXNET. 
**ESC-10 on MXNet 6.0**
```
+-------------------+-------------------+-------------------+
| Iteration         | Training Accuracy | Elapsed Time      |
+-------------------+-------------------+-------------------+
| 1                 | 0.372             | 451.111           |
+-------------------+-------------------+-------------------+
| 2                 | 0.592             | 451.459           | …
```
> SC MXNet to TF Regression Fix

- src/ml/neural_net/image_augmentation.cpp
- src/ml/neural_net/image_augmentation.hpp
- src/ml/neural_net/tf_compute_context.cpp
- Parallelize data augmentation across CPU cores
- Refactor `float_array_image_augmenter` to allow for map-reduce-style parallelization
- Dispatch training to a task queue, to allow augmentation to occur in parallel with NN operations
To minimize risk, the async training is only implemented for OD training, for now
> Performance improvements for TF OD

- src/ml/neural_net/tf_compute_context.cpp
On machines with a high thread count, there would be an out-of-bounds segfault on writing augmented images.
> Fixed typo in image augmentation.

- src/toolkits/recsys/recsys_model_base.hpp
- test/capi/capi_models.cxx
The PR contains 2 commits
- Fixed the C++ test for export_coreml to include calling with the user defined metadata
- Added an additional test to preserve the original behavior and added default parameters
> Fixed C++ unit test for export-coreml

- src/ml/neural_net/image_augmentation.cpp
- src/ml/neural_net/image_augmentation.hpp
- src/ml/neural_net/tf_compute_context.cpp
- Revert "Fixed typo in image augmentation. (#2816)"
- Revert "Performance improvements for TF OD (#2807)"
@nickjong @hoytak I'm putting up a PR just in case the parallel changes interact not so well with the augmentation. I'd like this change to be ready and tested just in case.
> Reverting parallel augmentation change

- LinuxGPU.md
- README.md
Let's wait for 6.0 to release before merging, but please review now.
> Documentation Updates for 6.0

- src/python/turicreate/test/test_activity_classifier.py
- src/python/turicreate/test/test_audio_functionality.py
- src/python/turicreate/test/test_drawing_classifier.py
- src/python/turicreate/test/test_image_classifier.py
- src/python/turicreate/test/test_image_similarity.py
- src/python/turicreate/test/test_object_detector.py
- src/python/turicreate/test/test_style_transfer.py
- src/python/turicreate/toolkits/_model.py
fix https://github.com/apple/turicreate/issues/2871
> Invalid summary input

- .gitlab-ci.yml
Since [coremltools has fixed their issues with 10.13 macOS](https://github.com/apple/coremltools/issues/408) and we now depend on the most recent version, we can enable our 10.13 tests again.
> Enable 10.13 macOS Tests

- CMakeLists.txt
- src/external/coremltools_wrap/CMakeLists.txt
Currently, we hide the CoreML:: namespace in order to allow our internal source drop of coremltools to exist alongside the coremltools python package in the same python process.  However, this needs to be done carefully in order to allow us to still call into the CoreML framework.  When this is messed up, then the CoreML framework has issues loading.
> FIx for CoreML import issues: Finer grain CoreML namespace mangling.

- src/python/turicreate/toolkits/sound_classifier/_audio_feature_extractor.py
#2873 
hmmmm so the error comes from that `_mac_ver()` method is destroyed before the object is destroyed.
I think this PR is just a workaround tho.
@TobyRoseman @nickjong any thoughts?
> del error for sound classifier

- .gitlab-ci.yml
- src/deployment/CMakeLists.txt
- src/deployment/recommender_initialization.cpp
- src/model_server/CMakeLists.txt
- src/python/turicreate/CMakeLists.txt
This fixes the coreml custom model issues on 10.14, and disable the tests (temporarily) on 10.13.  The 10.13 libraries are failing due to a missing symbol in libSystem.B.dylib, which appears to be a compilation sdk issue.
> Fix coreml import issues.

- src/python/turicreate/toolkits/_data_zoo.py
- src/python/turicreate/toolkits/one_shot_object_detector/util/_augmentation.py
Fixes #2005 
**Summary**
- We move the logic to unzip the backgrounds tarball to when the tarball is downloaded the first time.
- We save the unzipped tarball in the data cache instead of the current directory. This facilitates looking up in the data cache and avoiding multiple downloads and unzips.
> Better tarfile management for OSOD.

- src/python/turicreate/toolkits/_model.py
#2859 
change the `name()` function to `_name()` for `custom_model` class,
in order to remove the `name` function from all documentations.
> clean up models name function.

- src/python/turicreate/toolkits/drawing_classifier/drawing_classifier.py
- src/toolkits/drawing_classifier/drawing_classifier.cpp
> Dc evaluate perf

- src/python/turicreate/test/test_one_shot_object_detector.py
Until #2936 gets resolved, marked the failing non-deterministic test as xfail.
> Marked OSOD test_create_with_empty_dataset as XFAIL

- src/core/storage/fileio/dmlcio/filesys.h
- src/core/storage/fileio/file_download_cache.cpp
- src/core/storage/fileio/fs_utils.cpp
- src/core/storage/fileio/fs_utils.hpp
- src/core/storage/fileio/s3_api.cpp
- src/core/storage/fileio/sanitize_url.cpp
- src/core/storage/fileio/union_fstream.cpp
- test/fileio/general_fstream_test.cxx
resolve #394 
protocol in the url remains its original case, which should be handled by the remote fs.
```cpp
dir_archive_impl::archive_index_information read_index_file(std::string index_file) {
general_ifstream fin(index_file);
...
```
> enable case-insensitive protocol

- src/python/turicreate/test/test_audio_functionality.py
Workaround until #2949 gets resolved.
> Marked two test_audio_functionality non-deterministic unit test failures as XFAIL

- src/python/turicreate/toolkits/_image_feature_extractor.py
- src/python/turicreate/toolkits/object_detector/_tf_image_augmenter.py
close #2865 
6.0's CPU and GPU has prediction regression.
For the same image,
GPU:
```
#predictions
{'confidence': 0.6841502785682678, 'type': 'rectangle', 'coordinates': {'y': 167.98015236854553, 'x': 289.0607535839081, 'height': 238.21115112304688, 'width': 301.1848449707031}, 'label': 'Croissant'}
{'confidence': 0.5636424422264099, 'type': 'rectangle', 'coordinates': {'y': 168.73490810394287, 'x': 351.99418142437935, 'height': 183.61944580078125, 'width': 161.6607208251953}, 'label': 'Croissant'}
{'confidence': 0.5182375311851501, 'type': 'rectangle', 'coordinates': {'y': 101.34550631046295, 'x': 123.91261160373688, 'height': 176.6996612548828, 'width': 241.56607055664062}, 'label': 'Croissant'}
{'confidence': 0.4028134346008301, 'type': 'rectangle', 'coordinates': {'y': …
```
> [OD] 6.0 inference regression between CPU and GPU.

- src/python/turicreate/test/test_json.py
The long-term change needed here is tracked by https://github.com/apple/turicreate/issues/2934
> Disable flaky unit test for JSON parsing

- test/ml_data/CMakeLists.txt
The test ml_data/dml_test_row_bounds.cxx appears to have random intermediate failures due to some threading issue.  This PR disables this test. 
Tracked by https://github.com/apple/turicreate/issues/2966.
> Disable test with random intermittent failure.

- src/python/turicreate/toolkits/drawing_classifier/_tf_drawing_classifier.py
- src/toolkits/drawing_classifier/dc_data_iterator.cpp
- src/toolkits/drawing_classifier/dc_data_iterator.hpp
- src/toolkits/drawing_classifier/drawing_classifier.cpp
- test/unity/toolkits/drawing_classifier/test_dc_data_iterator.cxx
- test/unity/toolkits/drawing_classifier/test_dc_prediction.cxx
To make it consistent with all other toolkits, DC should also have consistent batch_size in the entire epoch. This can be done by using weights. Weights are arrays of 0/1 of the size of targets. For example, the last batch in the epoch is smaller than the specified batch_size then weights are zeros for the rest of the batch. While calculating loss and accuracy, the data corresponding the zeros is not taken into consideration.
> Adding weights to DC

- src/python/CMakeLists.txt
- src/python/turicreate/CMakeLists.txt
Fixes #2477 
Removes a dependency on a target which no longer exists (`numpy_integration`).
Also removes some very outdated comments.
> make bulding python_source fast again

- src/python/turicreate/toolkits/style_transfer/_tf_model_architecture.py
- Updated the conditional InstanceNorm implementation to get a better stylization.
- Gradients in the previous stylization were incorrectly being propagated.
All styles are merged together.
Styles have distinct seperation
- Removed `split` in `beta` and `gamma` in instanceNorm
- Removed loop in instanceNorm layer
> Updated Conditional InstanceNorm

- src/python/turicreate/test/test_one_shot_object_detector.py
- src/python/turicreate/toolkits/_data_zoo.py
- src/python/turicreate/toolkits/one_shot_object_detector/one_shot_object_detector.py
- src/python/turicreate/toolkits/one_shot_object_detector/util/_augmentation.py
Fixes: #2936
This is in many ways just an extension of #2901. There is [evidence](https://github.com/apple/turicreate/issues/2936#issuecomment-582182773) to suggest it's possible for an SArray to be incorrect extracted from a tar file and still be loadable.
This change checks the md5 of each extracted file.
This change also remove the xfail from the unit test and makes other minor changes.
> Fix flakey 1SOD test

- src/python/turicreate/test/test_activity_classifier.py
- src/toolkits/activity_classification/activity_classifier.cpp
Closes #2945 
Currently AC expects input data to include >=2 input feature columns. For this a concat layer is used to concatenate all input feature columns. When a single input column is provided, `export_coreml` breaks due to NN spec `validateConcatLayer` check failing.
This change checks number of input feature columns and **does not** add concat layer if feature columns are of size 1.
> Added support for AC to use single input feature column

- src/ml/neural_net/weight_init.cpp
- src/ml/neural_net/weight_init.hpp
- src/python/turicreate/toolkits/style_transfer/style_transfer.py
- src/toolkits/style_transfer/style_transfer.cpp
- src/toolkits/style_transfer/style_transfer_model_definition.cpp
- src/toolkits/style_transfer/style_transfer_model_definition.hpp
Initialization for style transfer is a uniform between -0.7 and 0.7. Previously only pertained weights were used for this in TensorFlow.
- Weight initialization in style transfer to use uniform between -0.7 and 0.7
- Random Seed values for initialization
> Updated Initialization for Style Transfer

- src/ml/neural_net/combine.hpp
- src/ml/neural_net/combine_base.hpp
- src/ml/neural_net/combine_futures_subscriber.hpp
- src/ml/neural_net/combine_iterator.hpp
- src/ml/neural_net/combine_map.hpp
- src/ml/neural_net/combine_mock.hpp
- test/unity/toolkits/neural_net/CMakeLists.txt
- test/unity/toolkits/neural_net/test_combine_base.cxx
- test/unity/toolkits/neural_net/test_combine_futures_subscriber.cxx
- test/unity/toolkits/neural_net/test_combine_iterator.cxx
- test/unity/toolkits/neural_net/test_combine_map.cxx
The main goal is make it easier to reason about the various portions of our
deep-learning training pipelines. For example, in Object Detection, we have a
data iterator that produces raw training examples, an image augmenter that
performs data augmentation, and a model backend that consumes a stream of
augmented training examples and produces progress updates and models.
As we integrate this framework, it should be easier to maintain unit tests for
these evolving pipelines and to manipulate threading and concurrency. For
example, if done right, this can replace our implementations of "double
buffering" currently copied across each model toolkit.
This PR turned out to be quite large, but FWIW it introduces no additions or modifications to the Turi Create release binaries, just headers (not …
> Introduce a minimal reactive streams framework, inspired somewhat by Swift's Combine

- test/unity/toolkits/neural_net/test_combine_futures_subscriber.cxx
I missed these test failures (pre-integration of my last couple of PRs) which seem specific to older versions of macOS
> Fix test_combines_futures_subscriber.cxx build failures on macOS 10.13

- src/ml/neural_net/model_spec.cpp
- src/ml/neural_net/model_spec.hpp
- src/toolkits/coreml_export/neural_net_models_exporter.cpp
- src/toolkits/coreml_export/neural_net_models_exporter.hpp
- src/toolkits/object_detection/CMakeLists.txt
- src/toolkits/object_detection/object_detector.cpp
- src/toolkits/object_detection/object_detector.hpp
- src/toolkits/object_detection/od_darknet_yolo_model_trainer.cpp
- src/toolkits/object_detection/od_darknet_yolo_model_trainer.hpp
- src/toolkits/object_detection/od_model_trainer.cpp
- src/toolkits/object_detection/od_model_trainer.hpp
- src/toolkits/object_detection/od_serialization.cpp
- src/toolkits/object_detection/od_serialization.hpp
- test/unity/toolkits/coreml_export/test_neural_nets_model_exporter.cxx
- test/unity/toolkits/object_detection/test_object_detector.cxx
- test/unity/toolkits/object_detection/test_od_serialization.cxx
- Rename the new "Model" type to "ModelTrainer" since we have too many types called "model" something or other already
- Change `object_detection::Checkpoint` from a simple struct to a polymorphic type that can instantiate a `ModelTrainer`. In this way, we can consolidate our logic that maps to multiple inner implementations/architectures into fewer places.
- Move CoreML export functionality into `Checkpoint`, since the CoreML representation will always depend on the backend architecture
> Migrate Object Detection export to CoreML to new Checkpoint type

- src/core/storage/fileio/block_cache.cpp
- src/core/storage/fileio/block_cache.hpp
- src/core/storage/fileio/fixed_size_cache_manager.cpp
- src/core/storage/fileio/fixed_size_cache_manager.hpp
`block_cache` is the front end of `fixed_size_cache_manager`, which means the former one relies on the later.
If `fiex_size_cache_manager` is destroyed before `block_cache`, bad access will show up.
The motivation here is that to enable the client to use `general_fstream` directly without any global setup and tear down, where the destruction order is explicitly handled.
> dependency injection on block_cache

- .gitignore
I realize that there's no way to ignore this `.pre-commit-config.yaml` while everybody can pull it from GitHub, which requires file to be tracked (not ignored) by git.
In relation to #2920.
> remove redundant ignore

- src/python/turicreate/test/test_activity_classifier.py
- src/python/turicreate/toolkits/activity_classifier/_tf_model_architecture.py
* Initialize TensorFlow variables when they are created.
* Added test to check predicton probabilities are the same after a save/load.
* Removed an `add` operation that was only adding zeros; those weights were never set.
* Added a comment about what is still preventing TensorFlow V2 behavior.
* Other minor clean ups.
> Activity Classifier Almost Works with TensorFlow V2 Behavior.

- src/python/turicreate/data_structures/sframe.py
Also removed redundant first parameter to `range`.
> Make docstring example code compatible with Python 3

- src/core/logging/assertions.hpp
- src/core/parallel/mutex.hpp
```
ERROR:    mutex.hpp(operator():67): Mutex lock error 221584233379 : ERROR:    mutex.hpp(operator():67): Check failed: !error:
ERROR:    mutex.hpp(operator():67): Mutex lock error 221584233379 : ERROR:    mutex.hpp(operator():67): Check failed: !error:
```
after pr
```
ERROR:    mutex.hpp(operator():67): Mutex lock error code: 22
1584233379 : ERROR:    mutex.hpp(operator():67): Check failed: !error:
ERROR:    mutex.hpp(operator():67): Mutex lock error code: 22
1584233379 : ERROR:    mutex.hpp(operator():67): Check failed: !error:
```
> better debug assert output

- src/core/storage/fileio/general_fstream.hpp
- src/core/storage/fileio/s3_api.hpp
```
def _try_inject_s3_credentials(url):
"""
Inject aws credentials into s3 url as s3://[aws_id]:[aws_key]:[bucket/][objectkey]
If s3 url already contains secret key/id pairs, just return as is.
"""
```
Bucket format should be consistent. Some places use `[/bucket]` and some places use `[bucket]`
Related to #2920.
> unify the format for the encoded s3 url through our codebase

- .clang-format
Some versions of clang-format are apparently merging them all into one block
> Always preserve existing header-include blocks

- src/core/storage/fileio/s3_api.cpp
sub-commit from #2920.
this resolves inconsistent representation of directory path used in our S3 path. 
```
SFrame("s3://dir/") # throw exception
SFrame("s3://dir")  # works
```
This misleading behavior is counter-intuitive to the use of the Unix-like filesystem, in which both cases should be valid.
In general, `/` is only used to visually distinguish directories from files. Under Unix philosophy, a directory is also a file, and this understanding is applied throughout the codebase. A close example is the `list_objects_impl` that is used under the hood, which removes the ending `/`. Also our `dir_archive` implementation follows this pattern.
All in all, directories except root (in S3, there's no root) should remove the ending `/`.
> resolve bug that inconsistent representation on directories

- src/core/storage/fileio/get_s3_endpoint.cpp
- src/core/storage/fileio/get_s3_endpoint.hpp
- src/core/storage/fileio/s3_api.cpp
- src/core/storage/fileio/s3_api.hpp
client SDK handles retry for network level.
> Each AWS SDK implements automatic retry logic. The AWS SDK for Java automatically retries requests, and you can configure the retry settings using the ClientConfiguration class. For example, you might want to turn off the retry logic for a web page that makes a request with minimal latency and no retries. Use the ClientConfiguration class and provide a maxErrorRetry value of 0 to turn off the retries.
But we need to handle our internal logic explicitly after network error is handled by SDK. 
429 is retried here explicitly, which stands for TOO MANY REQUESTS due to some rate limits.
> retry on S3 error code 429

- .pre-commit-config.yaml
- scripts/requirements.txt
- src/python/turicreate/test/test_sframe_s3.py
add test for frame s3 download and upload.
define env var `DTURI_ENDBALE_SF_S3` to enable the test.
add listed env vars in CI,
```
TURI_S3_REGION
TURI_S3_ENDPOINT
AWS_SECRET_ACCESS_KEY
AWS_ACCESS_KEY_ID
```
to run the test.
> test sframe s3 download and upload

- test/fileio/CMakeLists.txt
- test/fileio/s3_filesys_test.cpp
part of #2920. 
facilitate the manual test and check the logs in the command line.
```
$ ./s3_filesys_test tc_qa "integration/manual/sframes/small_sframe_dc/"
...
1585258409 : INFO:     block_cache.cpp(operator():226): Storing S3 Block Caches in memory cache
1585258409 : DEBUG:    fixed_size_cache_manager.cpp(get_cache:211): Get cache block cache://block_caches-C7C2F3601AFE05AEC51B750A18824C41
1585258409 : INFO:     read_caching_device.hpp(fetch_block:214): Fetching s3://tc_qa/integration/manual/sframes/small_sframe_dc/dir_archive.ini Block 0
1585258409 : DEBUG:    s3_filesys.cpp(Reset:63): reset position: 0. curr_bytes_: 0
1585258409 : DEBUG:    s3_filesys.cpp(Read:46): AWSReadStreamBase::Read, current pos: 0
1585258409 : INFO:     s3_filesys.cpp(FillBuffer:78): FillBuffer: 135 bytes …
```
> add extra manual test to view debug logs

- src/python/turicreate/test/test_audio_functionality.py
Fixes #2949 
All the other Sound Classifier models where correctness of predictions are checked, have their max iterations set to 100. It just seems like an oversight that this model wasn't having that set too.
Without this change, I was only able to run the test 16 times before I got a failure. With this change, I've been able to run it 100 times without failure.
The "training data" is only six examples that seems to be why we need the large number of iterations. Also because the data is so small, increasing the number of iteration doesn't seem to have an appreciable affect on running time of the unit tests.
> Fix non-deterministic sound classifier unit test

- scripts/update_version_number.sh
Fixes #2997.
With the switch to using the black python format, we've replaced single quotes, for string literals, with double quotes . Also for in line comments we add two spaces before the `#` and one space after it. Both of these broke our `update_version_number.sh` script. This change fixes the script to work with the new format.
> Fix script to work with black formatting

- .gitlab-ci.yml
It seems the 429 restrictions are based on the IP address for the internal S3 integration environment.
| platform | py ver |
| ---- | --- |
| mac | 2.7, 3.6 |
|linux | 2.7, 3.6 |
For each platform, the integration tests tend to start at the same time on the same machine, so it will likely trigger the rate limitation. 
The S3 component is fully self-contained, meaning s3 SDK is linked with our own source drop of OpenSSL and curl. The only difference is that on different OS, the binary code is different. So we need to test the S3 binary on each OS platform. But for python language, it's not necessary to test on both python3 and python2 on each platform because S3 related operation is almost all done at the binary level. 
The test after this change will be,
| platform | py ver |
| ---- | --- …
> bypass 429 limitations for s3 test

- src/core/storage/fileio/general_fstream.cpp
- src/core/storage/fileio/union_fstream.cpp
The root cause for Linux segfault might be caused by `fin` continues to read and deserialize garbage data when underlying file IO fails.
```
void block_manager::init_segment(std::shared_ptr<block_manager::segment>& seg) {
...
// read 8 bytes
fin->read(reinterpret_cast<char*>(&footer_size), sizeof(footer_size));
// deserialize the block information
fin->clear();
fin->seekg(filesize - footer_size - sizeof(footer_size), std::ios_base::beg);
iarchive iarc(*fin);
iarc >> seg->blocks;
seg->inited = true;
seg->file_size = filesize;
}
```
One should always check `fin.good()` after using it. As @ylow mentioned, most designs are based on the assumption that the retry logic (exception handling may involve) happens at very low-level IO operations and those IO will succeed in the end, people tend to …
> propagate exception

- src/core/storage/fileio/s3_api.cpp
- src/python/turicreate/test/test_sframe_s3.py
path style: host/bucket/key
virtual address: bucket.host/key
The new SDK uses a virtual address by default which causes backward compatible issues (because virtual address DNS is not available for normal dev environment).
Well, at least it works for all production environments.
related to https://github.com/aws/aws-sdk-cpp/issues/1357
> only use path style be default

- src/core/storage/fileio/s3_filesys.cpp
fix issue that uploaded sarray is not readable.
```python
gui = tc.SArray([1])
gui.save("tiny_array")
gui.save("s3://tc_qa/integration/manual/sarrays/tiny_array/")
gui.SArray("s3://tc_qa/integration/manual/sarrays/tiny_array/")
```
Unfortunately, this code still not work.
```
objc[88730]: Class TCRecommender is implemented in both /Users/guihaoliang/Work/guicreate-2/debug/src/python/turicreate/libunity_shared.dylib (0x11f34dd18) and /Users/guihaoliang/Work/gui-2-36/debug/src/python/turicreate/libRecommender.dylib (0x156dd0950). One of the two will be used. Which one is undefined.
Traceback (most recent call last):
File "hao.py", line 5, in <module>
gui = tc.load_sarray("s3://tc_qa/integration/manual/sarrays/tiny_array/")
File …
```
> fix SArray upload issue

- src/core/storage/fileio/s3_api.cpp
- src/core/storage/fileio/s3_api.hpp
- test/fileio/s3_filesys_test.cpp
`ShouldRetry` is using 
```
inline bool IsRetryableHttpResponseCode(HttpResponseCode responseCode)
{
switch (responseCode)
{
case HttpResponseCode::INTERNAL_SERVER_ERROR:
case HttpResponseCode::SERVICE_UNAVAILABLE:
case HttpResponseCode::TOO_MANY_REQUESTS:
case HttpResponseCode::BANDWIDTH_LIMIT_EXCEEDED:
case HttpResponseCode::REQUEST_TIMEOUT:
case HttpResponseCode::AUTHENTICATION_TIMEOUT:
case HttpResponseCode::LOGIN_TIMEOUT:
case HttpResponseCode::GATEWAY_TIMEOUT:
case HttpResponseCode::NETWORK_READ_TIMEOUT:
case HttpResponseCode::NETWORK_CONNECT_TIMEOUT:
return true;
default:
return false;
}
}
```
which is better for replacing my hardcoded approach.
Also, I reduce the connection time as well.
> better retry approach

- src/core/storage/fileio/s3_api.cpp
I should blame myself. I should read the source files instead of their [documentation](http://sdk.amazonaws.com/cpp/api/LATEST/class_aws_1_1_client_1_1_a_w_s_error.html#a6262c30a4967119d1730cb23dbe30d6f).
It's using `S3Errors` to wrap `CoreErrors`. We should only rely on Http code to do retry on our own.
> get the retry logic back

- scripts/install_python_toolchain.sh
disable command trace when linking a huge amount of files. Build log shown below will be omitted.
```
+ for f in ../../env/include/"$PYTHON_FULL_NAME"/*
++ basename ../../env/include/python3.6m/Python-ast.h
+ ln -Ffs ../../env/include/python3.6m/Python-ast.h Python-ast.h
+ for f in ../../env/include/"$PYTHON_FULL_NAME"/*
++ basename ../../env/include/python3.6m/Python.h
+ ln -Ffs ../../env/include/python3.6m/Python.h Python.h
+ for f in ../../env/include/"$PYTHON_FULL_NAME"/*
++ basename ../../env/include/python3.6m/abstract.h
+ ln -Ffs ../../env/include/python3.6m/abstract.h abstract.h
+ for f in ../../env/include/"$PYTHON_FULL_NAME"/*
++ basename ../../env/include/python3.6m/accu.h
+ ln -Ffs ../../env/include/python3.6m/accu.h accu.h
+ for f in ../../env/include/"$PYTHON_FULL_NAME"/*
++ …
```
> trim build log

- src/ml/neural_net/float_array.cpp
- src/ml/neural_net/float_array.hpp
- src/ml/neural_net/style_transfer/mps_style_transfer_backend.hpp
- src/ml/neural_net/style_transfer/mps_style_transfer_backend.mm
- src/toolkits/activity_classification/activity_classifier.cpp
- src/toolkits/drawing_classifier/drawing_classifier.cpp
- src/toolkits/object_detection/od_serialization.cpp
- src/toolkits/style_transfer/style_transfer.cpp
- src/toolkits/util/CMakeLists.txt
- src/toolkits/util/float_array_serialization.cpp
- src/toolkits/util/float_array_serialization.hpp
This PR is the first step to allowing the `neural_net` directory to build as a standalone library, which some of us have been doing in a hacky way for debugging/development purposes. The main change is to move the Turi serialization code outside, to the toolkits library.
> Allow float_array.cpp to build without other dependencies

- scripts/requirements.txt
llvmlite was updated transitively and has broken some builds. This change pins llvmlite to 0.31.0.
> Pin llvmlite to fix build error.

- scripts/requirements.txt
- src/python/setup.py
This pins the llvmlite version to one that compiles correctly with python 2.7.
> Pinned llvm version to one that compiles correctly with python 2.7

- src/toolkits/coreml_export/neural_net_models_exporter.cpp
- src/toolkits/coreml_export/neural_net_models_exporter.hpp
- src/toolkits/object_detection/object_detector.cpp
- test/unity/toolkits/coreml_export/test_neural_nets_model_exporter.cxx
Also add some experimental support for the NMS NN layer added in Catalina. This is mostly for development/experimental purposes, since it's not clear that the Vision API we tell developers to use to deploy OD models is compatible with the new NMS layer.
> Clean up OD CoreML export some more

- scripts/requirements.txt
- src/python/setup.py
llvmlite dropped support for python 3.5 as well, breaking installation.  Pinning it to v. 0.31.0 in python 3.5 as well.
> 2020 04 llvmlite version

- src/python/turicreate/toolkits/text_analytics/__init__.py
I was testing API availability for #3139 and I got,
```bash
"API Surface mis-matched. "
2020             "expected: %s\nactual: %s\nactual - expected: %s\nexpected - actual: %s"
2021             % (e_set, a_set, a_set - e_set, e_set - a_set)
2022         )
2023 E       AssertionError: API Surface mis-matched. expected: {'count_words', 'parse_sparse', 'count_ngrams', 'stop_words', 'random_split', 'tokenize', 'bm25', 'drop_words', 'parse_docword', 'tf_idf'}
2024 E         actual: {'extract_parts_of_speech', 'count_words', 'parse_sparse', 'count_ngrams', 'stop_words', 'random_split', 'tokenize', 'drop_words', 'bm25', 'parse_docword', 'split_by_sentence', 'tf_idf'}
2025 E         actual - expected: {'extract_parts_of_speech', 'split_by_sentence'}
2026 E         expected - actual: set()
2027 E …
```
> remove dead code from text_analytics

- .clang-tidy
- CMakeLists.txt
- configure
- src/.clang-tidy
- src/external/.clang-tidy
clang-tidy support enables the llvm extras linter to catch a wide array of problems and improve the build. It is off by default. Currently all rules are enabled, but this will fail the build. We will need to turn these rules on one by one.
Usage:
install llvm from homebrew, and make sure clang-tidy is in your path
./configure --with-clang-tidy
Clang build metrics enables a new features in Clang 9.0 which generates chrome://tracing (and similar tools) compatible json files for every compiled object that details where time was spent for that particular target. There are additional tools (such as ClangBuildAnalyzer) that will combine these files to give an overall high-level view of where time is spent in the build. I will share the detailed output from this internally.
Usage:
./configure …
> Add build support for clang-tidy and clang build metrics

- src/core/storage/fileio/s3_api.cpp
To avoid collisions (HTTP code 429) when 2 - 3 runners running tests at the same time.
> Customized s3 error handlings when encountering non-standard errors

- src/python/setup.py
we can customize the install when we call `bdist_wheel` by
```
python setup.py bdist_wheel install --minimal
running bdist_wheel
running build
running build_py
running build_ext
installing to build/bdist.macosx-10.14-x86_64/wheel
running install
```
It will customize the install information `install_requires`, which will be then used by `wheel` to write to `turicreate-6.2.dist-info/METADATA`.
> minimal build install

- src/python/setup.cfg
- src/python/turicreate/test/test_linear_regression.py
- src/python/turicreate/toolkits/object_detector/_tf_image_augmenter.py
will reduce roughly 1300 lines of warnings in pytest warning summary section. Save some time scrolling through the logs.
PendingDeprecattionWarning is okay to ignore for now.
> reduce some warnings

- scripts/create_docker_images.sh
```shell
+ docker pull registry.gitlab.com/zach_nation/turicreate/build-image-18.04:1.0.6
490 1.0.6: Pulling from zach_nation/turicreate/build-image-18.04
491 2746a4a261c9: Pulling fs layer
492 4c1d20cdee96: Pulling fs layer
493 0d3160e1d0de: Pulling fs layer
494 c8e37668deea: Pulling fs layer
495 c86b38401bd4: Pulling fs layer
496 ed23e6555ee4: Pulling fs layer
497 a47932478297: Pulling fs layer
498 f7e933d0319a: Pulling fs layer
499 a019a076f7b2: Pulling fs layer
500 9062cc6314d3: Pulling fs layer
501 2202575fb5a6: Pulling fs layer
502 346943f5a26d: Pulling fs layer
...
```
No need to show docker pull details. The information is useless most of the time and jams the build pipeline log.
> suppress docker pull prompts

- src/python/turicreate/toolkits/object_detector/_tf_image_augmenter.py
Fixes #3148 
#3093 incorrectly set the range for saturation and contrast. This reverts to the previous behavior.
> Fix color augmentation in TensorFlow object detection

- src/python/turicreate/data_structures/sarray.py
- src/python/turicreate/test/test_sarray.py
> SArray Shuffle

- .gitlab-ci.yml
the newly added minimal pkg pipeline for Linux is using dind 18. This needs to be updated due to #3154 this change.
> update the minimal package dind to 19.03

- src/ml/neural_net/weight_init.cpp
- src/ml/neural_net/weight_init.hpp
Adding normal distribution as a way of initializing weights for neural networks.
> Add normal distribution for weight initialization

- src/ml/neural_net/CMakeLists.txt
- src/ml/neural_net/GrandCentralDispatchQueue.cpp
- src/ml/neural_net/GrandCentralDispatchQueue.hpp
- src/ml/neural_net/PosixTaskQueue.cpp
- src/ml/neural_net/PosixTaskQueue.hpp
- src/ml/neural_net/TaskQueue.cpp
- src/ml/neural_net/TaskQueue.hpp
- src/ml/neural_net/combine.hpp
- src/ml/neural_net/combine_base.hpp
- src/ml/neural_net/combine_mock.hpp
- src/ml/neural_net/combine_queue.hpp
- src/ml/neural_net/mps_image_augmentation.mm
- test/unity/toolkits/neural_net/CMakeLists.txt
- test/unity/toolkits/neural_net/GrandCentralDispatchQueueTests.cxx
- test/unity/toolkits/neural_net/PosixTaskQueueTests.cxx
- test/unity/toolkits/neural_net/test_combine_queue.cxx
This is just for the deep-learning based toolkits, which are adopting combine-style reactive-streams patterns
> Introduce abstraction around Grand Central Dispatch or pthread-based thread pools

- scripts/requirements-minimal.txt
- scripts/requirements.txt
Update dependencies (TensorFlow and Pillow). Must still rely on the old version TensorFlow for Python 2.7; it is the last version to support 2.7.
> Update a couple of python dependencies

- scripts/use_ccache.sh
We should instead honor the ccache settings on the machine we run on. Some machines have less disk and should thus do less caching.
> Don't set ccache to use 100G of disk in Gitlab CI

- src/ml/neural_net/CMakeLists.txt
- src/ml/neural_net/float16.h
- src/ml/neural_net/model_spec.cpp
- src/ml/neural_net/model_spec.hpp
- src/ml/neural_net/quantization_utils.cpp
- src/ml/neural_net/quantization_utils.hpp
- src/toolkits/object_detection/od_serialization.cpp
Adds option to quantize weights post training fp32 to fp16 (only for MacOS)
Enables it for Object Detector model 
Also adds pooling types to model_spec
> Quantize weights from fp32 to fp16

- src/ml/neural_net/combine_queue.hpp
Analysis found a missing header include; this was relying on implementation-specific recursive includes before
> Add missing include of cassert in combine_queue.hpp

- src/core/data/sframe/gl_sarray.hpp
- src/core/storage/sframe_interface/CMakeLists.txt
- src/core/storage/sframe_interface/unity_sarray.cpp
- src/core/storage/sframe_interface/unity_sarray.hpp
- src/core/storage/sframe_interface/unity_sframe.cpp
- src/ml/sketches/quantile_sketch.hpp
- src/ml/sketches/streaming_quantile_sketch.hpp
- src/ml/sketches/unity_sketch.cpp
- src/ml/sketches/unity_sketch.hpp
- src/model_server/lib/api/unity_sarray_interface.hpp
- src/model_server/server/registration.cpp
- src/model_server/server/unity_server_init.cpp
- src/python/turicreate/_cython/cy_sarray.pxd
- src/python/turicreate/_cython/cy_sarray.pyx
- src/python/turicreate/data_structures/sarray.py
- src/python/turicreate/test/test_sarray.py
> SArray Median

- src/visualization/client/CMakeLists.txt
The latest beta of Xcode 12 results in link errors for the visualization
client, due to an under-specified destination in how we build:
```
Undefined symbols for architecture arm64:
"__swift_FORCE_LOAD_$_swiftCompatibility50", referenced from:
__swift_FORCE_LOAD_$_swiftCompatibility50_$_Turi_Create_Visualization in NSWindowWorkaround.o
__swift_FORCE_LOAD_$_swiftCompatibility50_$_Turi_Create_Visualization in CustomWebKitView.o
__swift_FORCE_LOAD_$_swiftCompatibility50_$_Turi_Create_Visualization in Error.o
__swift_FORCE_LOAD_$_swiftCompatibility50_$_Turi_Create_Visualization in ViewController.o
__swift_FORCE_LOAD_$_swiftCompatibility50_$_Turi_Create_Visualization in AppDelegate.o
__swift_FORCE_LOAD_$_swiftCompatibility50_$_Turi_Create_Visualization in JSON.o …
```
> Fix visualization build on Xcode 12 Beta

- src/python/turicreate/test/test_image_classifier.py
- src/python/turicreate/test/test_image_similarity.py
- src/python/turicreate/toolkits/image_analysis/__init__.py
- src/python/turicreate/toolkits/image_analysis/image_analysis.py
- src/python/turicreate/toolkits/image_classifier/image_classifier.py
- src/python/turicreate/toolkits/image_similarity/image_similarity.py
@TobyRoseman, please have a look and let me know what you think.
Thank you!
> Feature extraction

- src/python/turicreate/toolkits/text_classifier/_text_classifier.py
The change proposed in this merge request adds `l2_penalty` property to the `create()` method of `text_classifier`, allowing anyone to set custom weight on l2 regularization of the created models.
This property is optional, and **0.2** is left as the default value (this has previously been the hard-coded value passed once creating the `logistic_classifier`).
Relevant description has also been added to the **docstring**.
> Add l2_penalty property to text_classifier's create() method

- src/python/setup.py
Based on research done for #3003, only TensorFlow 2.1.0 and 2.1.1 have an issue on Linux when imported from PyBind.
> Relax TensorFlow Requirement

- scripts/install_python_toolchain.sh
* Newer `virtualenv` don't include header files.
* Also add back debugging output.
> Fix bulid for newer versions of virtualenv

- scripts/install_python_toolchain.sh
- scripts/requirements.txt
- scripts/test_wheel.sh
* Add `--use-feature=2020-resolver` to our Python build/test setup to ensure we stay compatible with the new dependency resolver.
* Also in our Python build/test setup, pin TensorFlow version (for a few Python versions and OS combinations). Without this one of our packages used for unit testing causes a SciPy version conflict.
> New pip dependency resolver

- src/toolkits/drawing_classifier/dc_data_iterator.cpp
Fixes #3236. 
This is an update to #3313. An image resize is already happening inside of `image_util::copy_image_to_memory_impl`.
> Drawing Classifier: input image resize fix

- .gitlab-ci.yml
- scripts/requirements.txt
- src/python/setup.py
Now that apple/coremltools#372 is fixed, we can use the latest coremltools beta.
> Use new coremltools beta

- src/toolkits/drawing_classifier/drawing_classifier.cpp
The first parameter to `table_printer::print_progress_row` is a "tick" parameter, i.e. some indication of the amount of done. So passing in the index, rather than the count, causes off by one issues in what gets printed.
> Drawing Classifier: print progress at round increments
